### PR TITLE
Teuchos: throw exception at duplicate YAML names

### LINKED ISSUE #2306: Teuchos Yaml Parser with duplicate names
Should this be allowed or should it throw an error

```
Foo:
  Bar: 
    Val:1
  Bar:
    Val:2
```

When I ask for Bar in the PL I get one entry, Val=2

Shouldn't this throw an error?
@ibaned

### PR DESCRIPTION
**Pull request by ibaned**
[#2306]

@trilinos/teuchos

## Description
Please see issue #2306 . I also did some unrelated cleanup.

## Motivation and Context

@bathmatt requested that there should be an error (exception) thrown when the same name shows up twice in the same ParameterList. This is a useful debugging tool to catch user error.

## Related Issues

* Closes #2306

## How Has This Been Tested?

A custom build of Teuchos passed all tests.

### CODE REVIEW

File: packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp [hunk 1]
```diff
@@ -277,8 +278,8 @@ class Reader : public Teuchos::Reader {
         break;
       }
       case Teuchos::YAML::PROD_BMAP_FSEQ: {
-        TEUCHOS_ASSERT(rhs.at(4).type() == typeid(Array<Scalar>) ||
-            rhs.at(4).type() == typeid(Array<Array<Scalar> >));
+        TEUCHOS_ASSERT(rhs.at(4).type() == typeid(std::vector<Scalar>) ||
```
Comment (bartlettroscoe) [inline packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp]: @ibaned, why are all of these being switched over from Teuchos::Array to std::vector?  Teuchos::Array just uses std::vector in non-debug checking mode but has very strong runtime checking in a debug-mode build.

Comment (bartlettroscoe) [reply packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp]: I just saw the comment "I also did some unrelated cleanup" in the description field.

Unless there is some technical reason to use std::vector instead of Teuchos::Array, the usage of Teuchos::Array should be kept for safety.  Even in this context, std::vector::operator[]() is completely unchecked.  And we can't turn on checked STL because we need to link against C++ TPLs that are built without checked STL turned on.  For the motivation for using Teuchos::Array over raw std::vector, see section "5.5.3 Teuchos::Array<T>" in:

* https://trilinos.org/docs/dev/packages/teuchos/doc/html/TeuchosMemoryManagementSAND.pdf

If you have questions about this, then let's talk.

Comment (ibaned) [reply packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp]: The motivation was to avoid having to define `std::ostream& operator<<(std::ostream&, Scalar const&)` and `std::ostream& operator<<(std::ostream&, std::vector<Scalar>&)`. It is possible to access `std::vector` in a checked way with `std::vector::at()`, I can make sure to use that if thats the main issue. Otherwise if `Teuchos::Array` still sounds better then I can put all that back.

Comment (bartlettroscoe) [reply packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp]: The problem with `std::vector::at()` is that it always checks.   There is no portable way to turn on and off array bounds checking with std::vector due to C++ TPLs that need to be linked in.

What is the issue with `operator<<()` exactly?

Comment (ibaned) [reply packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp]: It just seems like unnecessary boilerplate (recall the same issue with `Teuchos::any`). I used to have empty implementations for both. I can put them back just to get `Teuchos::Array` working just to have toggle-able bounds checking. Most of `TeuchosParser` already unconditionally calls `std::vector::at` since I don't consider it performance-critical.

Comment (bartlettroscoe) [reply packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp]: `std::vector::at()` does not completely make `std::vector` safe. YOu can also easily over-step and increment `std::vector` iterator returned from `std::vector::begin()`.  The motivation for `Teuchos::Array` as an off-by-one error I made in a code several years ago that segfaulted in a very strange place.  When I ran valgrind on it, it segfaulted inside of valgrind.  It took me several days to find the off-by-one error with std::vector and I only found it by staring at the code for days.  Teuchos::Array would have caught that defect in 1 sec.

**Comment by ibaned** [comment]
`Teuchos::Array` is back in.

**Comment by ibaned** [comment]
@bartlettroscoe we could use the same trick I used in `Teuchos::any`, in `Teuchos::Array`. Today I came across a drawback of that trick, however. `operator==` is technically defined for `std::vector<T>`, but doesn't get instantiated unless one calls it. So the compile-time test logic I put in `Teuchos::any` said that `std::vector<Scalar>` was comparable, therefore it instantiated that function. However, `Scalar` itself was not comparable, and it still failed to compile. So there are subtleties there for containers of containers that are not quite resolved. But we can make things a bit more usable.

**Comment by bartlettroscoe** [comment]
Can we put in recursive checks for "Is comparable"?  Can the check for "is comparable" for Teuchos::Array check to see if the type T is comparable and if not return false?

**Comment by ibaned** [comment]
Maybe... you may have to add a recursive definition for every existing container type, or come up with some common concept of a container they all satisfy. I'd say thats future work, and I intend to hit the merge button on this particular pull request unless someone objects.

**Comment by ibaned** [comment]
Hmm the autotester hasn't quite passed on the latest commit, so I did that a bit too early. Hopefully it does pass, otherwise we'll revert the merge.

**Comment by bartlettroscoe** [comment]
> Maybe... you may have to add a recursive definition for every existing container type, or come up with some common concept of a container they all satisfy. I'd say thats future work, and I intend to hit the merge button on this particular pull request unless someone objects.

Yes, I was not intending for this to hold up this PR.  Thanks.
