### PR TITLE
ROL: fix for Tpetra_DEPRECATED_CODE=OFF

### LINKED ISSUE #5738: ROL: Build and test errors when Tpetra deprecated code is turned off
There are many build and test errors when `-DTpetra_ENABLE_DEPRECATED_CODE=OFF`.

Part of #5602

### PR DESCRIPTION
**Pull request by tjfulle**
Closes #5738
Part of #5602

### CODE REVIEW

**Comment by tjfulle** [comment]
Related to #5540

File: packages/rol/adapters/teuchos/src/sol/ROL_SingletonTeuchosBatchManager.hpp [hunk 1]
```diff
@@ -52,7 +52,7 @@ namespace ROL {
 template<class Real, class Ordinal>
```
Comment (mhoemmen) [inline packages/rol/adapters/teuchos/src/sol/ROL_SingletonTeuchosBatchManager.hpp]: Does `Ordinal` only get used for `Comm`?

File: packages/rol/adapters/teuchos/src/sol/ROL_TeuchosBatchManager.hpp [hunk 2]
```diff
@@ -54,53 +54,53 @@ namespace ROL {
...
-    return Teuchos::size<Ordinal>(*comm_);
+    return Teuchos::size<int>(*comm_);
   }
 
   void reduceAll(Real* input, Real* output, int dim,
                  const Elementwise::ReductionOp<Real> &r) {
     int nB = this->numBatches();
     std::vector<Real> receiveBuffer(nB);
-    Teuchos::gather<Ordinal,Real>(input,1,&receiveBuffer[0],1,0,*comm_);
+    Teuchos::gather<int,Real>(input,1,&receiveBuffer[0],1,0,*comm_);
```
Comment (mhoemmen) [inline packages/rol/adapters/teuchos/src/sol/ROL_TeuchosBatchManager.hpp]: ROL devs should start using `data()` instead of `&vec[0]` : - )
