### PR TITLE
Fix 6246

### LINKED ISSUE #6246: Intrepid2 tests failing on several ATDM Trilinos builds on 'mutrino' (HSW and KNL), 'ride-cuda', 'sems-rhel7', 'serrano', and 'waterman-cuda', 'cts1' starting 2019-11-07
CC: @trilinos/intrepid2, @mperego (Trilinos Discretizations Product Lead), @bartlettroscoe, @fryeguy52

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-11-07&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=label&compare2=61&value2=Intrepid2&field3=status&compare3=62&value3=passed&field4=status&compare4=62&value4=notrun) the tests:

* `Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1`
* `Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1`
* `Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1`

are failing in the builds:

* `Trilinos-atdm-mutrino-intel-opt-openmp-HSW`
* `Trilinos-atdm-mutrino-intel-opt-openmp-KNL`
* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug`
* `Trilinos-atdm-serrano-intel-debug-openmp`
* `Trilinos-atdm-serrano-intel-opt-openmp`
* `Trilinos-atdm-waterman-cuda-9.2-debug`
* `Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug`
* `Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug`

starting 2019-11-07 where the list of failing tests and builds were:

| Build Name | Test Name | Status | Time |
| :-- | :-- | :-- | :-- |
| Trilinos-atdm-mutrino-intel-opt-openmp-HSW | Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1 | Failed | 9s 500ms |
| Trilinos-atdm-mutrino-intel-opt-openmp-HSW | Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1 | Failed | 1s 590ms |
| Trilinos-atdm-mutrino-intel-opt-openmp-KNL | Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1 | Failed | 55s 100ms |
| Trilinos-atdm-mutrino-intel-opt-openmp-KNL | Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1 | Failed | 5s 570ms |
| Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug | Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1 | Failed | 5s 20ms |
| Trilinos-atdm-waterman-cuda-9.2-debug | Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1 | Failed | 4s 810ms |
| Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug | Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1 | Failed | 10m 100ms |
| Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug | Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1 | Failed | 3s 680ms |

As shown in [this query](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2019-11-07&filtercount=5&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=label&compare2=61&value2=Intrepid2&field3=status&compare3=62&value3=passed&field4=status&compare4=62&value4=notrun&field5=testoutput&compare5=95&value5=The%20following%20tests%20FAILED%3A), most of the test failures appear to be due to diffs failing to meet tolerances.  The failing unit tests are:

**Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1:**
```
The following tests FAILED:
    4. AnalyticPolynomialsMatch_double_double_Hierarchical_HGRAD_LINE_UnitTest ... 
```

**Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1:**
```
The following tests FAILED:
    2. IntegratedLegendre_TwoPathsMatch_UnitTest ... 
    3. IntegratedLegendre_dtTwo
```

It looks like there are some pretty big diffs like with unit test `AnalyticPolynomialsMatch_double_double_Hierarchical_HGRAD_LINE_UnitTest` [shown here](https://testing.sandia.gov/cdash/testDetails.php?test=93181325&build=5866907) showing:

```
 Check: rel_err(actual, expected)
        = rel_err(1.11022e-17, 0) = 0.047619
          <= tol = 2.22045e-14 : FAILED
 values for -1 differ for field ordinal 3: expected 0; actual 1.11022e-17 (diff: -1.11022e-17)
 
 Check: rel_err(actual, expected)
        = rel_err(-1.58603e-17, 0) = 0.0666667
          <= tol = 2.22045e-14 : FAILED
 values for -1 differ for field ordinal 4: expected 0; actual -1.58603e-17 (diff: 1.58603e-17)
```

And then there is some hard-to-see-what-is-failing test output for the unit test `IntegratedLegendre_TwoPathsMatch_UnitTest` like [shown hear](https://testing.sandia.gov/cdash/testDetails.php?test=93181326&build=5866907) showing:

```
2. IntegratedLegendre_TwoPathsMatch_UnitTest ... 
 for polyOrder 2, x = 0, t = 0.2: -1.15648e-18 != 0 (diff = 1.15648e-18; tol = 2.22045e-14)
 for polyOrder 3, x = 0, t = 0.2: 1.83187e-19 != 9.71445e-21 (diff = 1.73472e-19; tol = 2.22045e-14)
 for polyOrder 4, x = 0, t = 0.2: -3.45953e-20 != -7.95495e-21 (diff = 2.66404e-20; tol = 2.22045e-14)
 for polyOrder 5, x = 0, t = 0.2: 8.39317e-21 != 2.01421e-22 (diff = 8.19175e-21; tol = 2.22045e-14)
 for polyOrder 6, x = 0, t = 0.2: -1.67405e-21 != -1.00874e-21 (diff = 6.65306e-22; tol = 2.22045e-14)
 for polyOrder 7, x = 0, t = 0.2: 3.82338e-22 != 3.25e-22 (diff = 5.73376e-23; tol = 2.22045e-14)
 for polyOrder 8, x = 0, t = 0.2: -8.77301e-23 != -5.72369e-23 (diff = 3.04932e-23; tol = 2.22045e-14)
 for polyOrder 9, x = 0, t = 0.2: 1.73751e-23 != 1.37628e-23 (diff = 3.61235e-24; tol = 2.22045e-14)
 for polyOrder 10, x = 0, t = 0.2: -3.53275e-24 != -3.4213e-24 (diff = 1.11452e-25; tol = 2.22045e-14)
 for polyOrder 2, x = 0, t = 0.4: -4.62593e-18 != 0 (diff = 4.62593e-18; tol = 2.22045e-14)
 for polyOrder 3, x = 0, t = 0.4: 1.46549e-18 != 7.77156e-20 (diff = 1.38778e-18; tol = 2.22045e-14)
 for polyOrder 4, x = 0, t = 0.4: -5.53525e-19 != -1.27279e-19 (diff = 4.26246e-19; tol = 2.22045e-14)
 for polyOrder 5, x = 0, t = 0.4: 2.68581e-19 != 6.44546e-21 (diff = 2.62136e-19; tol = 2.22045e-14)
 for polyOrder 6, x = 0, t = 0.4: -1.07139e-19 != -6.45595e-20 (diff = 4.25796e-20; tol = 2.22045e-14)
 for polyOrder 7, x = 0, t = 0.4: 4.89393e-20 != 4.16001e-20 (diff = 7.33921e-21; tol = 2.22045e-14)
 for polyOrder 8, x = 0, t = 0.4: -2.24589e-20 != -1.46526e-20 (diff = 7.80626e-21; tol = 2.22045e-14)
 for polyOrder 9, x = 0, t = 0.4: 8.89608e-21 != 7.04656e-21 (diff = 1.84952e-21; tol = 2.22045e-14)
 for polyOrder 10, x = 0, t = 0.4: -3.61754e-21 != -3.50341e-21 (diff = 1.14127e-22; tol = 2.22045e-14)
 for polyOrder 3, x = 0, t = 0.6: 1.42109e-18 != -1.35447e-18 (diff = 2.77556e-18; tol = 2.22045e-14)
 for polyOrder 4, x = 0, t = 0.6: -1.79856e-18 != 1.8398e-19 (diff = 1.98254e-18; tol = 2.22045e-14)
 for polyOrder 5, x = 0, t = 0.6: 1.01203e-18 != 2.51651e-20 (diff = 9.86865e-19; tol = 2.22045e-14)
 for polyOrder 6, x = 0, t = 0.6: -7.92033e-19 != 1.54018e-20 (diff = 8.07435e-19; tol = 2.22045e-14)
 for polyOrder 7, x = 0, t = 0.6: 5.68643e-19 != 1.88687e-20 (diff = 5.49774e-19; tol = 2.22045e-14)
 for polyOrder 8, x = 0, t = 0.6: -2.61462e-19 != -1.6288e-20 (diff = 2.45174e-19; tol = 2.22045e-14)
 for polyOrder 9, x = 0, t = 0.6: 1.42095e-19 != -8.92826e-21 (diff = 1.51023e-19; tol = 2.22045e-14)
 for polyOrder 10, x = 0, t = 0.6: -7.99345e-20 != 6.80169e-21 (diff = 8.67362e-20; tol = 2.22045e-14)
 for polyOrder 2, x = 0, t = 0.8: -1.85037e-17 != 0 (diff = 1.85037e-17; tol = 2.22045e-14)
 for polyOrder 3, x = 0, t = 0.8: 1.1724e-17 != 6.21725e-19 (diff = 1.11022e-17; tol = 2.22045e-14)
 for polyOrder 4, x = 0, t = 0.8: -8.85641e-18 != -2.03647e-18 (diff = 6.81994e-18; tol = 2.22045e-14)
 for polyOrder 5, x = 0, t = 0.8: 8.59461e-18 != 2.06255e-19 (diff = 8.38835e-18; tol = 2.22045e-14)
 for polyOrder 6, x = 0, t = 0.8: -6.8569e-18 != -4.13181e-18 (diff = 2.72509e-18; tol = 2.22045e-14)
 for polyOrder 7, x = 0, t = 0.8: 6.26423e-18 != 5.32481e-18 (diff = 9.39419e-19; tol = 2.22045e-14)
 for polyOrder 8, x = 0, t = 0.8: -5.74948e-18 != -3.75108e-18 (diff = 1.9984e-18; tol = 2.22045e-14)
 for polyOrder 9, x = 0, t = 0.8: 4.55479e-18 != 3.60784e-18 (diff = 9.46955e-19; tol = 2.22045e-14)
 for polyOrder 10, x = 0, t = 0.8: -3.70436e-18 != -3.5875e-18 (diff = 1.16866e-19; tol = 2.22045e-14)
 [FAILED]  (0.00569 sec) IntegratedLegendre_TwoPathsMatch_UnitTest
 Location: /lscratch1/jenkins/mutrino-slave/workspace/Trilinos-atdm-mutrino-intel-opt-openmp-HSW/SRC_AND_BUILD/Trilinos/packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/IntegratedLegendreTests.cpp:233
```

(I can't see why this failed because it looks like all of the `diff`s are smaller than the `tol`s.)

And then the test `Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1` failed in the cuda-10.1 build as shown [here](https://testing.sandia.gov/cdash/testDetails.php?test=93165538&build=5866489) with the error output:

```
[Intrepid2] Error in file /home/jenkins/ride/workspace/Trilinos-atdm-white-ride-cuda-10.1-gnu-7.2.0-release-debug/SRC_AND_BUILD/Trilinos/packages/intrepid2/src/Discretization/Basis/Intrepid2_BasisDef.hpp, line 781
            Test that evaluated to true: ( (spaceDim == 3) && ( (operatorType == OPERATOR_DIV) || (operatorType == OPERATOR_CURL) ) )
            >>> ERROR: (Intrepid2::getValues_HGRAD_Args) DIV and CURL are invalid operators for rank-0 (scalar) fields in 3D. 
```
Looking at the new commits pulled on 2019-11-07 [here](https://testing.sandia.gov/cdash/viewNotes.php?buildid=5866484#not34), it seems pretty likely that the commit 5d2a1c6:

```
5d2a1c6:  Intrepid2: implemented hierarchical bases on hexahedron, quadrilateral, and line, along with components to allow efficient implementation of tensor-product bases. (#5996)
Author: Nate Roberts <nvrober@sandia.gov>
Date:   Wed Nov 6 14:41:06 2019 -0700
```

triggered these failures.

## Current Status on CDash

* [Failures in theses three tests in all ATDM Trilinos builds over last 30 days](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=30%20days%20ago&end=now&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=block&field3count=3&field3field1=testname&field3compare1=61&field3value1=Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1&field3field2=testname&field3compare2=61&field3value2=Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1&field3field3=testname&field3compare3=61&field3value3=Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1&field4=status&compare4=61&value4=failed)

* [Status of these tests in all ATDM Trilinos builds for current testing day](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=Trilinos-atdm-&field2=block&field2count=3&field2field1=testname&field2compare1=61&field2value1=Intrepid2_unit-test_Discretization_Basis_HierarchicalBases_Hierarchical_Basis_Tests_MPI_1&field2field2=testname&field2compare2=61&field2value2=Intrepid2_unit-test_Discretization_Basis_HVOL_HEX_Cn_FEM_Serial_Test_01_SLFadDFad_MPI_1&field2field3=testname&field2compare3=61&field2value3=Intrepid2_unit-test_Shared_Polylib_LegendreJacobiPolynomials_JacobiLegendrePolynomial_Tests_MPI_1)

## Steps to Reproduce

One should be able to reproduce these failures on any of the above listed machines described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system <supported-atdm-system> are provided at:

The exact commands to reproduce this issue on any of these machines should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh <build-name>

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Intrepid2=ON \
 $TRILINOS_DIR

$ make NP=16

$ <command-to-run-on-compute-node> ctest -j4
```

where you just fill in the `<build-name> ` and the `<command-to-run-on-compute-node>` for the given build and machine as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#specific-instructions-for-each-system

### PR DESCRIPTION
**Pull request by CamelliaDPG**
@trilinos/intrepid2 

## Motivation
These changes reduce sensitivity to platform differences in floating point comparisons employed in recently-introduced tests in Intrepid2.  I have reproduced reported test failures on serrano and waterman, and confirmed that these changes eliminate those failures.

## Related Issues
* Closes #6246

### CODE REVIEW

File: packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp [hunk 1]
```diff
@@ -66,9 +66,11 @@ static const double TEST_TOLERANCE_TIGHT = 1.e2 * std::numeric_limits<double>::e
 template<typename ScalarType>
 using ViewType = Kokkos::DynRankView<ScalarType,Kokkos::DefaultExecutionSpace>;
 
-inline bool valuesAreSmall(double a, double b, double epsilon)
+template<typename ScalarType>
+inline bool valuesAreSmall(ScalarType a, ScalarType b, double epsilon)
 {
-  return (std::abs(a) < epsilon) && (std::abs(b) < epsilon);
+  using namespace std;
```
Comment (mhoemmen) [inline packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp]: The usual idiom for making argument-dependent lookup (ADL) work is this:
```c++
using std::abs;
return (abs(a) < epsilon) && (abs(b) < epsilon);
```

Comment (CamelliaDPG) [reply packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp]: Thanks for the note, @mhoemmen!  That is cleaner, and I've made that change.

**Comment by CamelliaDPG** [comment]
> @CamelliaDPG I'm fine with this, but in general I think it would be better to have an error check using absolute and relative tolerances so that small values are taken care of. Something like:
> abs(a-b) < abs(a+b)/2* rel_tol + abs_tol

Thanks, @mperego!  I thought we were aiming to use the standard Teuchos unit test floating equality comparisons as much as possible; I think you mentioned that these would soon (if they don't already) gain better support for comparing Sacado types — that comment is what led me to make this change in the particular way I did.  My present approach allows us to use the  `TEST_FLOATING_EQUALITY` macro from Teuchos while also allowing large relative differences if the absolute values are small.

**Comment by mperego** [comment]
> > @CamelliaDPG I'm fine with this, but in general I think it would be better to have an error check using absolute and relative tolerances so that small values are taken care of. Something like:
> > abs(a-b) < abs(a+b)/2* rel_tol + abs_tol
> 
> Thanks, @mperego! I thought we were aiming to use the standard Teuchos unit test floating equality comparisons as much as possible; I think you mentioned that these would soon (if they don't already) gain better support for comparing Sacado types — that comment is what led me to make this change in the particular way I did. My present approach allows us to use the `TEST_FLOATING_EQUALITY` macro from Teuchos while also allowing large relative differences if the absolute values are small.

Oh, OK, I understand now. I thought Teuchos implemented also a version with absolute/relative tolerances. I think it would be a better test in general. @jwillenbring @bartlettroscoe  what do you think?
Anyway, go ahead and merge this. Thanks!
