### PR TITLE
Ifpack2: Speedup additive schwarz, fix #9606

### LINKED ISSUE #9606: Ifpack2: RILUK with overlap iteration counts increase with repeated solves
@jhux2 

Observed on a test problem that with repeated reuse of an Ifpack2 RILUK preconditioner with "schwarz: overlap level" set to 1 led to a gradual increase in the linear solver iteration counts over time. If we restarted the simulation partway through the solver iteration counts immediately dropped back down. Running with "schwarz: overlap level" set to 0 the iteration counts also remain roughly constant for the full simulation. It appears there is some internal state associated with overlap that is not being reset between uses of the preconditioner and causing problems with repeated use. I can provide access to files to reproduce to an appropriate developer.

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/ifpack2 

## Motivation

- Fix #9606: make ``AdditiveSchwarz::compute()`` re-import the overlapping part of the matrix (halo) so that the inner preconditioner can see the new values.
- Fuse LocalFilter, ReorderFilter and SingletonFilter into a single class called "Details::AdditiveSchwarzFilter" that constructs the filtered matrix on device. This benefits AdditiveSchwarz with KokkosKernels ILUK because KokkosKernels needs this filtered matrix to be constructed explicitly (it can't use the Tpetra::RowMatrix interface). 
- Make OverlappingRowMatrix use only the matrix on device; avoid host-device transfers.

## Stakeholder Feedback

Required for Sierra milestone
## Testing

OverlappingRowMatrix and AdditiveSchwarz are tested in Ifpack2.

### CODE REVIEW

**Comment by brian-kelley** [comment]
@csiefer2 Like we talked about at today's Tpetra meeting, I just added a debug check in ``CrsGraph::setAllIndices`` to check that columns are in bounds.

**Review by csiefer2 — DISMISSED** [review]

**Review by srajama1 — APPROVED** [review]
@brian-kelley Thanks!

As you know, I would like Ifpack2 inner preconditioner to change to directly use Kokkos Crs matrices as opposed to Tpetra/Xpetra matrices. The use cases for distributed inner preconditioners are very theoretical and we might be able to extract more performance if we skip one more layer of abstraction. However, no need to worry about it in this PR yet as it is a big redesign.

**Comment by brian-kelley** [comment]
@vbrunini It's not posting to CDash so I don't know what's failing. I opened a helpdesk ticket about it. But I fixed the actual issues with my changes from the last time it posted, so it might just be random failures now.

**Comment by jhux2** [comment]
I don't see failures in the cdash reports.  Can someone post where we might find the results?

**Comment by brian-kelley** [comment]
@jhux2 The results aren't being posted to CDash correctly, so I opened a ticket about that. Framework gave me the Jenkins output directly. There was a real build error in my changes that didn't happen on my compiler, but I just pushed a fix.

**Comment by brian-kelley** [comment]
@jhux2 @csiefer2 Could you give this a fresh review? I don't think there have been major changes since you each reviewed before.

**Comment by jhux2** [comment]
> Could you give this a fresh review? I don't think there have been major changes since you each reviewed before.

@brian-kelley I'm looking at this now.

File: packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp [hunk 1]
```diff
@@ -0,0 +1,769 @@
...
+  localMap_ = rcp (new map_type (numLocalRows, 0, localComm, Tpetra::GloballyDistributed));
+  //Create the inner filtered matrix.
+  auto crsParams = rcp(new Teuchos::ParameterList);
+  crsParams->template set<bool>("sorted", true);
+  //NOTE: this is the fastest way to construct A_ - it's created as fillComplete,
+  //and no communication needs to be done since localMap_ uses a local comm.
+  //It does need to copy the whole local matrix to host when DualViews are constructed
+  //(only an issue with non-UVM GPU backends) but this is just unavoidable when creating a Tpetra::CrsMatrix.
+  //It also needs to compute local constants (maxNumRowEntries) but this should be a
+  //cheap operation relative to what this constructor already did.
```
Comment (jhux2) [inline packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp:320]: My understanding:   This copy-to-host only happens once, at construction.  The matrix graph is fixed, and if matrix values are later updated, no copy to host occurs.

**Review by jhux2 — APPROVED** [review]
lgtm -- have one question that I think I know the answer to

File: packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp (hunk 1 above)
Comment (brian-kelley) [reply packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp:320]: @jhux2 Unfortunately it also copies when I do setAllValues, since that re-constructs the WrappedDualViews in the matrix and graph. I don't think there's any other legal way to replace all the values without doing resumeFill/fillComplete, which I wanted to avoid.

Comment (jhux2) [reply packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp:320]: Oh, that's too bad.  Perhaps fodder for discussion at a future Tpetra meeting.

Comment (brian-kelley) [reply packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp:320]: In future, if Karen's suggestion #9655 gets implemented, that would make this really easy because the WrappedDualView will handle it automatically. I already get a ReadWrite view of the matrix values, so I can just change them and then be done. No copying to host or fillComplete needed.
