### PR TITLE
Tpetra: Fix #3971

### LINKED ISSUE #3971: Tpetra: Minor build errors due to PR #3952
@trilinos/tpetra @DrBooom @csiefer2 Minor build error (Mac, Clang, OpenMPI 1.10.1) due to PR #3952:
```
In file included from .../Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_convert.cpp:50:
.../Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp:8200:66: error: use of undeclared identifier 'MPI'
        immRedErr = MPI_Iallreduce(&mismatch,&reduced_mismatch,1,MPI::BOOL,MPI_LOR,rawComm,&rawRequest);
                                                                 ^
1 error generated.
```
I'm working on a fix.  The fix should also restore backwards compatibility with ancient MPI implementations (such that `MPI_VERSION < 3`).

## Related Issues

* Related to #3952

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra Fix #3971 (minor build errors due to PR #3952).

### CODE REVIEW

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp [hunk 1]
```diff
@@ -59,32 +59,42 @@
...
 #include <memory>
 #include <sstream>
 #include <typeinfo>
 #include <vector>
 
-#include <Teuchos_RCP.hpp>
-
-#include <Teuchos_FancyOStream.hpp>
-
 using Teuchos::rcpFromRef;
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: Woah, who put this here?!?  I definitely didn't.  Let's not do that in the future, k?

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp [hunk 2]
```diff
@@ -59,32 +59,42 @@
...
 
+  std::shared_ptr< ::Tpetra::Details::CommRequest>
+  iallreduceIntRaw (const int& localValue,
+		    int& globalValue,
+		    const ::Teuchos::EReductionType op,
+		    const Teuchos::Comm<int>& comm)
+  {
+    Kokkos::View<const int*, Kokkos::HostSpace> localView (&localValue);
+    Kokkos::View<int*, Kokkos::HostSpace> globalView (&globalValue);
+    return ::Tpetra::Details::iallreduce (localView, globalView, op, comm);
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: This has a nonblocking fall-back implementation in case `MPI_VERSION < 3`.  (It just defers the all-reduce until `wait()`.)

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp (hunk 1 above)
Comment (bartlettroscoe) [reply packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: Would not be hard to figure that out

Comment (mhoemmen) [reply packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: Haha, I don't mean to blame specific parties; I just mean to scold generally ;-)

**Comment by mhoemmen** [comment]
Thanks @bartlettroscoe ! :D
