### PR TITLE
Stop throwing from destructors

### LINKED ISSUE #1303: All: Throwing from destructors
Early signs of this are seen in #449 and #577, but I think its a broader problem than those issues make it seem. This is not a clang-specific problem but rather goes down to the C++ standard.

Basically, because destructors need to be safe to call during the stack unwinding as a response to an exception being throw, they should not themselves be able to throw exceptions. 

It is worthwhile to read libMesh's experience with this problem using GCC 6.1, see libMesh/libmesh#1073. This quote from that discussion sums up the relevant language in the various C++ standards as well as the sensible solution of taking out any throw statements from destructors:

> No, not undefined behavior. In the C++03 standard, sections 15.2 and 15.5.1 make it clear that an exception which escapes a destructor results in an immediate call to std::terminate().
>
> In C++11 it's even a bit looser, as best as I can tell: if you override the default "noexcept" specification on your destructor, and your destructor isn't currently being called as part of stack unwinding during another exception throw, and the object being destroyed isn't static or TLS, then the exception is allowed to propagate and be handled normally; otherwise you get std::terminate().
>
> Nitpicking aside, though, after a little more thought my vote is to just remove the libmesh_parallel_only() macro call here. The hypothetical advantage of maybe being able to more easily debug MPI sync failures at LibMeshInit destruction time isn't worth the definite annoyance of a false positive warning or of trying to work around the warning.

Here is a warning thrown by GCC 6.1 on Teuchos:

```
/projects/AppComp/alexa/nightly/cee-compute011/src/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:183:28: warning: throw will always call terminate() [-Wterminate]
     throw Exception(omsgstr); \
                            ^
/projects/AppComp/alexa/nightly/cee-compute011/src/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:305:3: note: in expansion of macro ‘TEUCHOS_TEST_FOR_EXCEPTION’
   TEUCHOS_TEST_FOR_EXCEPTION(throw_exception_test, std::logic_error, "Error!")
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/projects/AppComp/alexa/nightly/cee-compute011/src/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp:655:5: note: in expansion of macro ‘TEUCHOS_TEST_FOR_EXCEPT’
     TEUCHOS_TEST_FOR_EXCEPT(0==rcp_node_list());^M
     ^~~~~~~~~~~~~~~~~~~~~~~
/projects/AppComp/alexa/nightly/cee-compute011/src/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:183:28: note: in C++11 destructors default to noexcept
     throw Exception(omsgstr); \
                            ^
/projects/AppComp/alexa/nightly/cee-compute011/src/Trilinos/packages/teuchos/core/src/Teuchos_TestForException.hpp:305:3: note: in expansion of macro ‘TEUCHOS_TEST_FOR_EXCEPTION’
   TEUCHOS_TEST_FOR_EXCEPTION(throw_exception_test, std::logic_error, "Error!")
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/projects/AppComp/alexa/nightly/cee-compute011/src/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp:655:5: note: in expansion of macro ‘TEUCHOS_TEST_FOR_EXCEPT’
     TEUCHOS_TEST_FOR_EXCEPT(0==rcp_node_list());^M
     ^~~~~~~~~~~~~~~~~~~~~~~
```

The way I see it, here are the options Teuchos has:
1. Remove `TEST_FOR_EXCEPT` calls from destructors.
2. Replace those calls with the equivalent of `assert()`.
3. Try to override the `noexcept` specification. Note that doing this will not guarantee a proper unwinding exception in all cases.

#449 and #577 seem to indicate that there are Teuchos tests which rely on exception throwing from destructors to cause unwinding. Given that this is only standards-conforming with C++11 and even then only under certain special conditions, those tests should be looked at carefully to see if they actually conform to the restrictions mentioned in the standard and if not then expected behavior should be re-evaluated and tests changed.

@trilinos/teuchos @MicheldeMessieres @bartlettroscoe @mhoemmen

### PR DESCRIPTION
**Pull request by ibaned**
@trilinos/teuchos 
@trilinos/thyra 
@trilinos/belos 
@trilinos/ml 
@lxmota 

## Description

From the first commit message:

This is the foundation for fixing #1303.
First, the macro TEUCHOS_TEST_FOR_TERMINATION
is introduced, which calls std::terminate()
instead of throwing an exception.

I think std::terminate() is the most appropriate
exit call here, because it is exactly what the
compiler would have done anyway. In particular,
the warnings we were getting said
"warning: throw will always call terminate() [-Wterminate]"
As such, if we explicitly call std::terminate ourselves,
we are preserving the existing behavior while silencing
the warning.

TEUCHOS_TEST_FOR_TERMINATION takes stream message code,
and that message will be sent to std::cerr.

This commit also replaces all calls in Teuchos, Belos, Thyra, and ML to
TEUCHOS_TEST_FOR_EXCEPTION (and similar macros) from
within destructors with TEUCHOS_TEST_FOR_TERMINATION.

## Motivation and Context

See #1303 for general discussion, but here is some data to put this issue into perspective, also from the first commit message:

The most important change is the one in ~RCPNodeTmpl()
in Teuchos_RCPNode.hpp which is guarded by TEUCHOS_DEBUG.
When TEUCHOS_DEBUG is defined, this instance alone emitted
its warning at least 136702 times in one user's reported build
of Trilinos, due to the ubuquitous use of RCP in Trilinos.
Given that one warning and its associated notes are close to 1KB
of text, this dominated and bloated all other build output
for a total of around 100MB of text output from the build.

## Related Issues

* Closes #1303 

## How Has This Been Tested?

A debug build of only Teuchos with `-Werror` and `TEUCHOS_DEBUG` defined built successfully and passed all Teuchos tests. Will rely on PR testing as well.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by aprokop** [comment]
Just 31 lines of code address the issue that has been going on for years... make your own conclusions.

**Comment by ibaned** [comment]
I'd like @bartlettroscoe to look this over before it goes in, but if others would like it in earlier just let me know and I'll go ahead with the merge.

**Comment by lxmota** [comment]
We have been waiting for years, so I guess it's OK to wait a little while longer.

File: packages/teuchos/core/src/Teuchos_RCPNode.hpp [hunk 1]
```diff
@@ -586,7 +586,7 @@ class RCPNodeTmpl : public RCPNode {
   ~RCPNodeTmpl()
     {
 #ifdef TEUCHOS_DEBUG
-      TEUCHOS_TEST_FOR_EXCEPTION( ptr_!=0, std::logic_error,
+      TEUCHOS_TEST_FOR_TERMINATION( ptr_!=0,
```
Comment (bartlettroscoe) [inline packages/teuchos/core/src/Teuchos_RCPNode.hpp]: I think I can write a unit test that triggers this termination.  That would at least provide some test of this new macro.  We want to make sure that we test this somehow.

File: packages/teuchos/core/src/Teuchos_TestForException.cpp [hunk 2]
```diff
@@ -109,3 +110,8 @@ bool Teuchos::TestForException_getEnableStacktrace()
 {
   return loc_enableStackTrace();
 }
+
+void Teuchos::TestForTermination_terminate(const std::string &msg) {
+  std::cerr << msg;
+  std::terminate();
```
Comment (bartlettroscoe) [inline packages/teuchos/core/src/Teuchos_TestForException.cpp]: When MPI is enabled, should this not be MPI_Abort() instead of std::terminate()?

File: packages/teuchos/core/src/Teuchos_RCPNode.hpp (hunk 1 above)
Comment (ibaned) [reply packages/teuchos/core/src/Teuchos_RCPNode.hpp]: Thats a good idea, thanks. Just let me know when you have it.

File: packages/teuchos/core/src/Teuchos_TestForException.hpp [hunk 3]
```diff
@@ -75,6 +75,9 @@ TEUCHOSCORE_LIB_DLL_EXPORT void TestForException_setEnableStacktrace(bool enable
  * exceptions are thrown. */
 TEUCHOSCORE_LIB_DLL_EXPORT bool TestForException_getEnableStacktrace();
 
+/** \brief Prints the message to std::cerr and calls std::terminate. */
+TEUCHOSCORE_LIB_DLL_EXPORT [[noreturn]] void TestForTermination_terminate(const std::string &msg);
```
[the remark this answers is not in the document]
Comment (ibaned) [reply packages/teuchos/core/src/Teuchos_TestForException.hpp]: As of 22 hours ago, we have dropped C++98:
https://github.com/trilinos/Trilinos/issues/1390#issuecomment-352913138
And in fact it was already broken for Teuchos:
https://github.com/trilinos/Trilinos/issues/1390#issuecomment-352819700
I don't know if this is the right approach, but my preference would just be to start using C++11 features freely, and remove any existing `CXX11` guards over time.

[the remark this answers is not in the document]
Comment (bartlettroscoe) [reply packages/teuchos/core/src/Teuchos_TestForException.hpp]: I agree.  I was just cheering the non-ifdefed usage of C++11 is TeuchosCore code.

File: packages/teuchos/core/src/Teuchos_TestForException.cpp (hunk 2 above)
Comment (ibaned) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: I actually spent a good amount of time considering `MPI_Abort`, and I don't think its the right choice here. The most important reason is covered in [this blog post](https://akrzemi1.wordpress.com/2011/10/05/using-stdterminate/) while explaining why `std::terminate()` cannot call `std::exit()`:

"This poses a risk that in case std::terminate is called as a consequence of throwing exception from global destructor (say, the very last global destructor), calling std::exit would launch the process of calling all destructors again… Therefore, C++ Standard defines the situation of calling std::exit after the clean-up of globals has started, an undefined behavior."

If `TEUCHOS_TEST_FOR_TERMINATION` were to call anything that calls `exit()` (and `MPI_Abort()` does indeed call `exit()`), then it would invoke this undefined behavior if it gets triggered from a global destructor, and it exists primarily for error handling within destructors.

Comment (bartlettroscoe) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: There is no mention at all of MPI in [that blog post](https://akrzemi1.wordpress.com/2011/10/05/using-stdterminate/).  I would be concerned that having just one process calling `std::terminate()` would result in the other MPI processes hanging.  To avoid that, I would rather just call MPI_Abort() and guarantee that the whole MPI program will come down and just burn the whole thing down.

I guess I could write some multi-process tests that calls this macro and then see what happens.  I just worry that some of those tests might hang with some C++ and MPI  implementation pairs.

What do you think?

Comment (bartlettroscoe) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: I can't find any hits on Google for the expected or proper interaction of `std::terminate()` with MPI programs.  But from looking at [this item](http://comp.parallel.mpi.narkive.com/1XiQoFZH/calling-exit-or-mpi-abort-in-an-mpi-program), we should expect modern MPI implementations and runtime environments to kill the other MPI processes of one MPI process is terminated (either by exit() or abort()).

So hopefully my tests will show that calling std::terminate() on one process of a multi-process system will bring down all of the processes.

But then should we not at least give the MPI proc-ID in the std::cerr output line in debugging?  We can get that from Teuchos::GlobalMPISession.  I can add that to the automated tests.

I will push an updated commit to your branch.

Comment (ibaned) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: I looked at the source code of MPICH and it calls `exit()`. Every MPI implementation I've ever dealt with would terminate all other ranks if one of them stops in any way, including `abort()` (which is what my library usually does when something goes wrong) or even segfault, or throwing an exception like `std::bad_alloc` when out of memory. Most of them also give an indication of which rank (or ranks) ended badly, even if Teuchos doesn't do it explicitly. I don't mind trying to print the global rank though.

Comment (ibaned) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: Also this branch is on my fork, I've invited you as a collaborator so we don't have to do tedious things like another pull request into the branch.

Comment (bartlettroscoe) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: @ibaned, turns out that you don't need push access to people's GitHub clones anymore.  It turns out that a while back that GitHub implemented a feature that when you create a PR, that you by default given permission for the developers of that target GitHub repo to push to your branch.  Next time you create a PR, look for the check-box where you are giving this permission.

Comment (mhoemmen) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: @ibaned ok that makes sense

Comment (ibaned) [reply packages/teuchos/core/src/Teuchos_TestForException.cpp]: @bartlettroscoe  oh, I didn't know that included commits. I checked that box for this PR, so we should be good.

**Comment by ibaned** [comment]
I just pushed some comment typo fixes. I'm going to be a bit risky and assume that these did not affect the results of the tests, which have passed, and will go ahead and merge this PR now.

Thanks @bartlettroscoe and others for the quick and positive response!

Happy holidays!
