### PR TITLE
MueLu: fixing call to kokkos refactor method in Xpetra::EpetraMap, closes #5019

### LINKED ISSUE #5019: MueLu: Epetra unit-tests try to run with kokkos-refactored factories
## Bug Report
@trilinos/muelu 

### Description
Some unit-tests are currently being run with both Epetra and kokkos refactor, which is supported. But these tests are also asking for the kokkos factories in MueLu because of the `Kokkos_Refactor_On_By_Default` variable being set ON by default when `MueLu_ENABLE_KokkosCore` is ON too.

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/muelu 

## Description
We need to make sure that the ParameterListInterpreter does not call kokkos factories when we run with lib==Xpetra::UseEpetra

## Motivation and Context
This will allow our nightly builds to have test passing.

## Related Issues

* Closes #5019 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## How Has This Been Tested?
This has been tested locally and all MueLu tests pass

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.

### CODE REVIEW

File: packages/muelu/test/unit_tests/UserData/CreateXpetraPreconditioner.cpp [hunk 1]
```diff
@@ -145,6 +148,9 @@ namespace MueLuTests {
     myArrayLO[4] = 3;
     userParamList.set<Array<LO> >("Array<LO> myArray<LO>", myArrayLO);
 
+    out << "Parameter List:" << std::endl;
+    inParamList->print(out);
```
Comment (cgcgcg) [inline packages/muelu/test/unit_tests/UserData/CreateXpetraPreconditioner.cpp]: I think you forgot this.
