### PR TITLE
Tpetra: FEM Assembly - move code into functions

### LINKED ISSUE #2370: FEM Assembly Example: Fix CUDA Error Messages
@trilinos/tpetra

## Current Behavior
When running FEM Assembly examples on a GPU system (Power8, Pascall100 nodes), the output contains the following error messages at the end of a run when using 4 nodes:

```
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
End Result: TEST PASSED
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
```

When running on 1 core, the message is still there but only one of them.

The test still passes, but these error messages show up.

@mhoemmen @jhux2 @csiefer2 @crtrott 
I don't have a lot of experience running on the GPU systems, have any of you guys seen this before?  Any suggestions?

## Code Location
The code examples are generally the same, but the [fem_assembly_TotalElementLoop_SP.cpp][1] file is an exemplar of how they are all laid out currently.

[1]: https://github.com/trilinos/Trilinos/blob/develop/packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp

## Motivation and Context
The example(s) need to run cleanly on GPU systems.

## Definition of Done
- [ ] `Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized` should go away on CUDA platforms.

## Your Environment
On White:
```
module load devpack/openmpi/1.10.4/gcc/5.4.0/cuda/8.0.44
export TRILINOS_HOME=<path to my Trilinos clone>
export OMPI_CXX=${TRILINOS_HOME}/packages/kokkos/bin/nvcc_wrapper
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
export OMP_NUM_THREADS=4
export OMP_PROC_BIND=spread
```
It's possible that this is the wrong environment for running on the machine correctly which might be causing the messages too ??

## Related Issues
* Related to #2369 -- common main might affect or take care of this??

### PR DESCRIPTION
**Pull request by william76**
@trilinos/tpetra 
@mhoemmen 

## Description
Moving example code into functions to get rid of the error messages caused by the d'tor of `RCP<Tpetra::Map<...>>` being called after `Tpetra::finalize()`.  This was happening because they were both in the same scope.

## Solution
Fixed by moving the actual tasks into an `execute()` function.
- We might break this up later but that's a different issue ;)

@mhoemmen created issue #2372 to add a message to the d'tor if it's called after `finalize()` has been called to improve clarity.

## Related Issues
* Closes #2370
* Related to #2372

## How Has This Been Tested?
- Tested on local machine.
- Tested on White.

### CODE REVIEW

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp [hunk 1]
```diff
@@ -58,19 +58,17 @@
 
 using namespace TpetraExamples;
 
+#define COMM_T Teuchos::RCP<const Teuchos::Comm<int> >
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp]: Please don't do this (define a short, non-namespaced macro).  Make this a typedef, not a macro:
```
using comm_ptr_type = Teuchos::RCP<const Teuchos::Comm<int> >;
```

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp [hunk 2]
```diff
@@ -58,19 +58,17 @@
...
 
-int main (int argc, char *argv[]) 
+
+int execute(COMM_T& comm)
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp]: Make this a typedef, not a macro.  See above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp [hunk 3]
```diff
@@ -58,20 +58,18 @@
 
 using namespace TpetraExamples;
 
+#define COMM_T Teuchos::RCP<const Teuchos::Comm<int> >
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp]: See above.  Make this a typedef, not a macro.  Also, how much effort does this relabeling really save?

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp [hunk 4]
```diff
@@ -58,20 +58,18 @@
...
 
 
-int main (int argc, char *argv[]) 
+
+int execute( COMM_T& comm )
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp]: See above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp [hunk 5]
```diff
@@ -58,20 +58,18 @@
 
 using namespace TpetraExamples;
 
+#define COMM_T Teuchos::RCP<const Teuchos::Comm<int> >
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp]: Use a typedef instead of a macro here (see above).

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp [hunk 6]
```diff
@@ -58,20 +58,18 @@
...
 
 
-int main (int argc, char *argv[]) 
+
+int execute (COMM_T& comm)
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp]: Use a typedef instead of a macro here (see above).

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp [hunk 7]
```diff
@@ -308,18 +306,37 @@ int main (int argc, char *argv[])
...
+}
+
+
+int main (int argc, char *argv[]) 
+{
+  int status = EXIT_SUCCESS;
+  
+  // MPI boilerplate
+  Tpetra::initialize(&argc, &argv);
+  COMM_T comm = Tpetra::DefaultPlatform::getDefaultPlatform ().getComm();
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp]: Use a typedef instead of a macro here (see above).  Also, use `Tpetra::getDefaultComm()`; don't use `DefaultPlatform`.  The whole "Platform" idea was Chris Baker's original heterogeneous programming model that wasn't quite so fully baked.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp [hunk 8]
```diff
@@ -308,18 +306,37 @@ int main (int argc, char *argv[])
...
+
   // Print out timing results.
-  TimeMonitor::report(comm.ptr(), std::cout, "");
+  Teuchos::TimeMonitor::report(comm.ptr(), std::cout, "");
 
   // Finalize
   Tpetra::finalize();
 
   // This tells the Trilinos test framework that the test passed.
   if(0 == comm->getRank())
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp]: You can't call `Comm` methods after MPI has been finalized.  `Tpetra::finalize()` may finalize MPI (it does if and only if `Tpetra::initialize(...)` initialized MPI).

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp [hunk 9]
```diff
@@ -306,17 +304,37 @@ int main (int argc, char *argv[])
...
+
   // Print out timing results.
-  TimeMonitor::report(comm.ptr(), std::cout, "");
+  Teuchos::TimeMonitor::report(comm.ptr(), std::cout, "");
 
   // Finalize
   Tpetra::finalize();
 
   // This tells the Trilinos test framework that the test passed.
   if(0 == comm->getRank())
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp]: You can't call `Comm` methods after MPI has been finalized.  `Tpetra::finalize()` may finalize MPI (it does if and only if `Tpetra::initialize(...)` initialized MPI).

**Comment by william76** [comment]
@mhoemmen 
I checked in an update with the fixes you requested.

- Moved the Tpetra::finalize() to the end of main (oops!)
- Removed preprocessor macro `COMM_T` and replaced with
  Mark's suggestion.
- Fixed bug in `typedefs.hpp` brackets on namespace TpetraExamples
  brackets were wrong.
- MeshDatabase.hpp: Removed old 'TODO' comment since the feature
  had already been added.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp [hunk 10]
```diff
@@ -58,19 +58,18 @@
 
 using namespace TpetraExamples;
 
+using comm_ptr_t = Teuchos::RCP<const Teuchos::Comm<int> >;
 
-int main (int argc, char *argv[]) 
+
+
+int execute(comm_ptr_t& comm)
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp]: Next time, only pass by value or const reference (`const comm_ptr_t&`).  That conveys the intent not to reset the pointer.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp [hunk 11]
```diff
@@ -255,17 +254,36 @@ int main (int argc, char *argv[])
...
-  Tpetra::finalize();
+
+
+int main (int argc, char *argv[]) 
+{
+  int status=EXIT_SUCCESS;
+  
+  // MPI boilerplate
+  Tpetra::initialize(&argc, &argv);
+  comm_ptr_t comm = Tpetra::DefaultPlatform::getDefaultPlatform ().getComm();
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp]: Please use `Tpetra::getDefaultComm()` (in `Tpetra_Core.hpp`).

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.cpp [hunk 12]
```diff
@@ -58,20 +58,19 @@
 
 using namespace TpetraExamples;
 
+using comm_ptr_t = Teuchos::RCP<const Teuchos::Comm<int> >;
 
 
-int main (int argc, char *argv[]) 
+
+int execute (comm_ptr_t& comm)
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.cpp]: See note above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.cpp [hunk 13]
```diff
@@ -295,18 +294,37 @@ int main (int argc, char *argv[])
...
+
+
+
+int main (int argc, char *argv[]) 
+{
+  int status = EXIT_SUCCESS;
+  
+  // MPI boilerplate
+  Tpetra::initialize(&argc, &argv);
+  comm_ptr_t comm = Tpetra::DefaultPlatform::getDefaultPlatform ().getComm();
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.cpp]: See note above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp [hunk 14]
```diff
@@ -58,20 +58,18 @@
 
 using namespace TpetraExamples;
 
+using comm_ptr_t = Teuchos::RCP<const Teuchos::Comm<int> >;
 
 
-int main (int argc, char *argv[]) 
+
+int execute(comm_ptr_t& comm )
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp]: See note above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp [hunk 15]
```diff
@@ -306,17 +304,37 @@ int main (int argc, char *argv[])
...
-  Tpetra::finalize();
+
+
+int main (int argc, char *argv[]) 
+{
+  int status = EXIT_SUCCESS;
+
+  // MPI boilerplate
+  Tpetra::initialize(&argc, &argv);
+  comm_ptr_t comm = Tpetra::DefaultPlatform::getDefaultPlatform ().getComm();
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp]: See note above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp [hunk 16]
```diff
@@ -58,20 +58,18 @@
 
 using namespace TpetraExamples;
 
+using comm_ptr_t = Teuchos::RCP<const Teuchos::Comm<int> >;
 
 
-int main (int argc, char *argv[]) 
+
+int execute (comm_ptr_t& comm)
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp]: See note above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp [hunk 17]
```diff
@@ -308,18 +306,37 @@ int main (int argc, char *argv[])
...
-  // Finalize
-  Tpetra::finalize();
+
+int main (int argc, char *argv[]) 
+{
+  int status = EXIT_SUCCESS;
+  
+  // MPI boilerplate
+  Tpetra::initialize(&argc, &argv);
+  comm_ptr_t comm = Tpetra::DefaultPlatform::getDefaultPlatform ().getComm();
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp]: See note above.

**Comment by mhoemmen** [comment]
@william76 should we merge this?

**Comment by william76** [comment]
@mhoemmen Yeah.  I think so -- the motivation for this issue was to get the main code outside of main() so we could fix the messages that were getting spammed out on the GPUs... it also moves us more in the direction of using some of the existing infrastructure to drive tests, but that's a separate thing to take on ;)

Do you care if I hit the button?
