### PR TITLE
Ifpack2,Anasazi: Fix #3139; remove Tpetra_INST_INT_INT=ON requirement from Anasazi examples

### LINKED ISSUE #3139: Ifpack2 does not build with Tpetra_INST_INT_INT=OFF
## Current Behavior
When building Ifpack2 with Tpetra_INST_INT_INT=OFF, there are multiple failures.

In Ifpack2_UnitTestBlockTriDiContainer.cpp, Tpetra data structures are created with global ordinal explicitly set to int; this causes unresolved references at link time.  See, e.g., line 348
          run_performance_test<double, int, int>(*in);

Also, in Ifpack2_UnitTestOverlappingRowMatrix.cpp, the call to Teuchos::scan near line 317 doesn't compile due to differing types for the input and output buffers; this fix is easy:
-  int nlr = Teuchos::as<int>(numLocalRows);
+  GO nlr = Teuchos::as<GO>(numLocalRows);
   Teuchos::scan(*comm,Teuchos::REDUCE_SUM,1,&nlr,&gidOffset);

## Motivation
The Tpetra team is pursuing deprecation of global_ordinal=int.  If Ifpack2 requires global_ordinal=int, please tell the Tpetra team ASAP.  

## Definition of Done
build/test Ifpack2 with Tpetra_INST_INT_INT=OFF

## Possible Solution
I offer a solution to one problem above, but fixing the harder problems is probably best done by an Ifpack2 developer.

## Steps to Reproduce'
build/test Ifpack2 with Tpetra_INST_INT_INT=OFF

## Your Environment

Trilinos develop branch, linux workstation

## Related Issues

* Blocks #2548 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/ifpack2 @trilinos/anasazi 

## Description

Ifpack2: Fix #3139; work around #3192

  - Ifpack2 now builds with `Tpetra_INST_INT_INT=OFF`; this fixes #3139
  - Removed `Tpetra_INST_INT_INT=ON` requirement from an unrelated test
  - Found a likely Epetra64 bug (#3192) and worked around it

Anasazi: Remove `Tpetra_INST_INT_INT` requirement from examples

Remove `Tpetra_INST_INT_INT AND NOT Anasazi_ENABLE_TSQR` requirement.
For `Tpetra_INST_INT_INT`, see #2548.

## Motivation and Context

Fix #3139; work around #3192; work on #2548.

## Related Issues

* Closes #3139 
* Related to #3192 
* Part of #2548 

## How Has This Been Tested?

Linux, GCC, OpenMPI.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

File: packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp [hunk 1]
```diff
@@ -106,33 +102,95 @@ RCP<const Epetra_CrsMatrix> create_testmat_e(const Epetra_Map& rowmap)
...
 #endif
-    Epetra_Map emap(localRows, 0, ecomm);
-    auto emat = create_testmat_e(emap);
+    Epetra_Map emap(static_cast<int> (localRows), 0, ecomm);
+    Teuchos::RCP<const Epetra_CrsMatrix> emat;
+    try {
+      // mfh 26 Jul 2018: This function call throws.  That means the
+      // test is broken; I didn't write that code.  This blocks #3139,
+      // so I'm going to just let this test build for now, but not
+      // actually run it.
```
Comment (jhux2) [inline packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp]: @mhoemmen This should be recorded somewhere besides a comment so that we know the test is not running.  Maybe a separate issue?

File: packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp [hunk 2]
```diff
@@ -106,33 +102,95 @@ RCP<const Epetra_CrsMatrix> create_testmat_e(const Epetra_Map& rowmap)
...
 {
+  constexpr bool debug = true;
+  auto myOutPtr = debug ?
+    Teuchos::getFancyOStream (Teuchos::rcpFromRef (std::cerr)) :
+    Teuchos::rcpFromRef (out);
+  auto& myOut = *myOutPtr;
+
+  myOut << "Ifpack2 BlockRelaxation performance comparison: Epetra vs. Tpetra"
+        << std::endl;
+
```
Comment (jhux2) [inline packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp]: Why create a new ostream instead of using `out`?

File: packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp [hunk 3]
```diff
@@ -310,15 +310,15 @@ TEUCHOS_UNIT_TEST_TEMPLATE_3_DECL(Ifpack2OverlappingRowMatrix, getLocalDiag, Sca
...
   Array<scalar_type> val(3);
   Array<global_ordinal_type> ind(3);
-  scalar_type zero=0;
-  scalar_type one=1;
-  val[0] = as<scalar_type>(-1);
-  val[1] = as<scalar_type>(2);
-  val[2] = as<scalar_type>(-1);
+  scalar_type zero=0.0;
+  scalar_type one=1.0;
+  val[0] = static_cast<scalar_type>(-1.0);
```
Comment (jhux2) [inline packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp]: I'm curious, why is `static_cast` preferred over `Teuchos::as`?

File: packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp (hunk 1 above)
Comment (mhoemmen) [reply packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp]: @jhux2 Oops, I forgot to take that comment out.  There's an Epetra64 issue: https://github.com/trilinos/Trilinos/issues/3192 .  Fun fact: Epetra breaks if you give `Epetra_Map`'s constructor `long long` instead of `int`.

File: packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp (hunk 2 above)
Comment (mhoemmen) [reply packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp]: @jhux2 I was trying to debug the test; this led to discovery of #3192.  The test was bombing out before it could print any useful information, so I replaced `out` with a `FancyOStream` that wraps `std::cerr`.  I think I've tried just overwriting `out` before, but it didn't work.

File: packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp (hunk 3 above)
Comment (mhoemmen) [reply packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp]: @jhux2 I'm trying to move to more standard language features as much as possible, partly in hopes of saving build time and partly because they are easier for novice developers to understand.  Also, the main value of `Teuchos::as` is that it may check for overflow in a debug build.  If the cast can't overflow, then there's no reason to use `Teuchos::as`.

Comment (jhux2) [reply packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp]: Thanks, that's good to know.
