### PR TITLE
ShyLU: fixed test failures with deprecated off (#5617)

### LINKED ISSUE #5617: ShyLU: Tests failures with Tpetra's deprecated code is disabled
## Bug Report
@trilinos/shylu 

Part of: #5602 

### Description

With Tpetra's deprecated code disabled, 2 ShyLU tests fail for `GlobalOrdinal=int`:

- ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_DIM2_DPN2_ORD0_TPETRA_MPI_4
- ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_DIM2_DPN2_ORD1_TPETRA_MPI_4

See the full configuration for `GlobalOrdinal=int` at https://github.com/trilinos/Trilinos/issues/5602#issuecomment-516593697

### PR DESCRIPTION
**Pull request by brian-kelley**
Fixed test failures:
...IPOUHarmonic_DIM2_DPN2_ORD0_TPETRA_MPI_4 and
...IPOUHarmonic_DIM2_DPN2_ORD1_TPETRA_MPI_4 in ShyLu_DDFROSch
by changing Xpetra matrix construction to use StaticProfile.

@trilinos/shylu 
@trilinos/xpetra 

## Description

At FROSch_CoarseOperator_def.hpp:235, changed the creation of Xpetra::Matrix to use StaticProfile and exact entry counts. This is effectively a deep copy from tmpCoarseMatrix to CoarseMatrix_, except with 1.0 inserted on the diagonal in rows which are empty in tmpCoarseMatrix.

As part of this, implemented
Xpetra::Matrix::getNumEntriesInGlobalRow(GO) because without it,
counting entries in each row of tmpCoarseMatrix requires an additional call to
getGlobalRowView() for every row. Like Xpetra::Matrix::getNumEntriesInLocalRow(LO),
this function is a trivial one-line wrapper for the same function on
the underlying matrix.
## Motivation and Context

Fixes the test failures: ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_DIM2_DPN2_ORD0_TPETRA_MPI_4 and ShyLU_DDFROSch_test_thyra_xpetra_laplace_TLP_IPOUHarmonic_DIM2_DPN2_ORD1_TPETRA_MPI_4 when Tpetra_ENABLE_DEPRECATED_CODE=OFF.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp [hunk 1]
```diff
@@ -231,17 +231,30 @@ namespace FROSch {
...
+                  GO globalRow = CoarseSolveMap_->getGlobalElement(i);
+                  size_t numEntries = tmpCoarseMatrix->getNumEntriesInGlobalRow(globalRow);
+                  if(numEntries == 0)
+                  {
+                    //Always add the diagonal for empty rows
+                    numEntries = 1;
+                  }
+                  elemsPerRow[i] = numEntries;
+                }
+                CoarseMatrix_ = Xpetra::MatrixFactory<SC,LO,GO,NO>::Build(CoarseSolveMap_, elemsPerRow, Xpetra::StaticProfile);
```
Comment (mhoemmen) [inline packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp]: Does this invoke a deprecated constructor that takes ArrayRCP instead of ArrayView?  Perhaps it's not deprecated for Xpetra.

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp [hunk 2]
```diff
@@ -231,17 +231,30 @@ namespace FROSch {
...
+                for (LO i = 0; i < numRows; i++) {
+                    GO globalRow = CoarseSolveMap_->getGlobalElement(i);
+                    tmpCoarseMatrix->getGlobalRowView(globalRow,indices,values);
                     if (indices.size()>0) {
-                        CoarseMatrix_->insertGlobalValues(CoarseSolveMap_->getGlobalElement(i),indices,values);
+                        CoarseMatrix_->insertGlobalValues(globalRow,indices,values);
                     } else { // Add diagonal unit for zero rows // Todo: Do you we need to sort the coarse matrix "NodeWise"?
-                        GOVec indices(1,CoarseSolveMap_->getGlobalElement(i));
+                        GOVec indices(1,globalRow);
                         SCVec values(1,1.0);
```
Comment (mhoemmen) [inline packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp]: This probably won't build for `Scalar=complex<float>`, but not your problem :-)

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp (hunk 1 above)
Comment (brian-kelley) [reply packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp]: It's the only constructor for xpetra. Might as well switch over because arrayRCP has operator() to get a view.
