### PR TITLE
Ifpack2 coordinates scalar template

### LINKED ISSUE #2551: Ifpack2: coordinates passed to the block relaxation line partitioner need to be `double`
@trilinos/ifpack2 
@mhoemmen @csiefer2 

## Expectations
It seems a reasonable assumption that coordinates will be passed as `double` for line detection. We should be able to use that algorithm when `Scalar=std::complex<double>`

## Current Behavior
Currently the coordinates are templated on `Scalar` which leads to a type mismatch when the multivector of coordinates coming from an app/MueLu is templated on `double`

## Motivation and Context
The line detection algorithm is useful for problem exhibiting strong mesh anisotropy which happens often for cfd problem where a mesh is closely fitted and extruded in the normal direction to a solid surface. For instance this can happen when modelling the fluid flow around a wind turbine blade or an aircraft wing.

## Definition of Done
There is a test in MueLu that uses the line detection algorithm and that test is failing when `Scalar=std::compled<double>` this should actually run correctly with proper templates.

## Possible Solution
Switch `MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>` to `MultiVector<double, LocalOrdinal, GlobalOrdinal, Node>` where appropriate so that the coordinates can go through Ifpack2 without problems.

## Steps to Reproduce
Compile Trilinos with complex on and run the MueLu tests.

## Related Issues
* Follows #2528
* Related to #2520

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/ifpack2 

## Description
This pull request is fixing a templating issue for the multivector of coordinates passed to Ifpack2 when the line partitioner is being used.

## Motivation and Context
This will allow MueLu users to access the line detection algorithm implemented for Block Relaxation in Ifpack2. This is useful as a smoother in certain situations. 

## Related Issues
* Closes #2551 
* Follows #2520 #2523 

## How Has This Been Tested?
A unite test in MueLu is using this capability and now passes for both double and std::complex<double>

## Checklist
- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

**Comment by lucbv** [comment]
@mhoemmen, @csiefer2, I did an old school run of the checkin script with the default build and the complex build turned on and this passed all the tests. It looks pretty solid to me.

```
Build/Test Cases Summary
Enabled Packages: Ifpack2, MueLu
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Forward Packages
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=823,notpassed=0 (15.74 min)
1) MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX => passed: passed=826,notpassed=0 (15.87 min)
Other local commits for this build/test group: 9978a49
```

File: packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp [hunk 1]
```diff
@@ -151,7 +151,7 @@ getValidParameters () const
 
   validParams->set("partitioner: line detection threshold",(double)0.0);
   validParams->set("partitioner: PDE equations",(int)1);
-  Teuchos::RCP<Tpetra::MultiVector<typename MatrixType::scalar_type,
+  Teuchos::RCP<Tpetra::MultiVector<double,
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp]: Are coordinates always double?  Could they perhaps be float?

File: packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp [hunk 2]
```diff
@@ -67,7 +67,7 @@ This implementation is derived from the related routine in ML.
 Supported parameters:
   <ul>
     <li> \c "partitioner: line detection threshold": if \f$||x_j - x_i||^2 < thresh * \max_k||x_k - x_i||^2\f$, then the points are close enough to line smooth <Scalar>
-    <li> \c "partitioner: coordinates"  : coordinates of local nodes  < Teuchos::MultiVector<Scalar> >
+    <li> \c "partitioner: coordinates"  : coordinates of local nodes  < Teuchos::MultiVector<double> >
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp]: See above question.

File: packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp [hunk 3]
```diff
@@ -80,8 +80,8 @@ class LinePartitioner : public OverlappingPartitioner<GraphType> {
   typedef typename GraphType::global_ordinal_type global_ordinal_type;
   typedef typename GraphType::node_type node_type;
   typedef Tpetra::RowGraph<local_ordinal_type, global_ordinal_type, node_type>  row_graph_type;
-  typedef Tpetra::MultiVector<Scalar,local_ordinal_type, global_ordinal_type, node_type>  multivector_type;
-  typedef typename Teuchos::ScalarTraits<Scalar>::magnitudeType MT;
+  typedef Tpetra::MultiVector<double,local_ordinal_type, global_ordinal_type, node_type>  multivector_type;
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp]: See above question.

File: packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp [hunk 4]
```diff
@@ -80,8 +80,8 @@ class LinePartitioner : public OverlappingPartitioner<GraphType> {
...
+  typedef typename Teuchos::ScalarTraits<double>::magnitudeType MT;
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp]: The magnitudeType of double is always double.  If you meant to use MT only for coordinates, give it a more relevant name.  For example:
```
using coordinate_type = double;
```

File: packages/ifpack2/src/Ifpack2_LinePartitioner_def.hpp [hunk 5]
```diff
@@ -110,11 +110,11 @@ template<class GraphType,class Scalar>
 int LinePartitioner<GraphType,Scalar>::Compute_Blocks_AutoLine(Teuchos::ArrayView<local_ordinal_type> blockIndices) const {
   typedef local_ordinal_type LO;
   const LO invalid  = Teuchos::OrdinalTraits<LO>::invalid();
-  const Scalar zero = Teuchos::ScalarTraits<Scalar>::zero();
+  const double zero = Teuchos::ScalarTraits<double>::zero();
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_LinePartitioner_def.hpp]: See above.

File: packages/ifpack2/src/Ifpack2_LinePartitioner_def.hpp [hunk 6]
```diff
@@ -139,18 +139,18 @@ int LinePartitioner<GraphType,Scalar>::Compute_Blocks_AutoLine(Teuchos::ArrayVie
...
-    Scalar x0 = (!xvals.is_null()) ? xvals[i/NumEqns_] : zero;
-    Scalar y0 = (!yvals.is_null()) ? yvals[i/NumEqns_] : zero;
-    Scalar z0 = (!zvals.is_null()) ? zvals[i/NumEqns_] : zero;
+    double x0 = (!xvals.is_null()) ? xvals[i/NumEqns_] : zero;
+    double y0 = (!yvals.is_null()) ? yvals[i/NumEqns_] : zero;
+    double z0 = (!zvals.is_null()) ? zvals[i/NumEqns_] : zero;
 
     LO neighbor_len=0;
     for(size_t j=0; j<nz; j+=NumEqns_) {
       MT mydist = mzero;
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_LinePartitioner_def.hpp]: If MT comes from Scalar, MT could be float instead of double.

Either use double everywhere, or make a typedef for the coordinate type and use that consistently.

File: packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp (hunk 1 above)
Comment (lucbv) [reply packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp]: We have had a discussion around that issue in MueLu, on possible option to fix this would be to create a new template type called `Real` that would be essentially the same as `Scalar` but forbidding complex. I guess we could also manually template on more types but that would lead to some cumbersome checks when pulling data off the parameter list.

Overall we decided that coordinates will always be `double` for the time being so the above code should be fine.

File: packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp (hunk 4 above)
Comment (lucbv) [reply packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp]: Yes, I decided to consistently switch everything to double.
