### PR TITLE
Xpetra mv

### LINKED ISSUE #9206: xpetra: multivector getLocalView uses deprecated interface
## Bug Report
@trilinos/xpetra

@fnrizzi @ppebay

### Description
In the current develop and also tpetraCrsRefactor branches xpetra getLocalView does the old way of just getting a view without read/write traits assigned.  We should make the new interface take the traits and propagate that code through the stack..  
Because of this xpetra will have some dummy classes which map to the tpetra ones with read, write, ...  The names will be the same

This can be built and tested off develop with a few patches from @csiefer2 to fix up thyra.

We will probably only merge this into the crs refactor branch unless it gets merged first which I doubt.

Thoughts?

### PR DESCRIPTION
**Pull request by bathmatt**
Not ready to merge, but this is matching changes for xpetra from the latest develop MR which added a lot of deprecated code to tpetra

@trilinos/<teamName>

## Testing

@ppbay

### CODE REVIEW

**Comment by bathmatt** [comment]
@jhux2  here is the starting effort, hoping to review it next week, this code doesn't yet compile with dep code off but I'll have that patched up early this week.

**Review by ppebay — COMMENTED** [review]
Eliminating warnings due to missing `override` statements.

File: packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp [hunk 1]
```diff
@@ -265,24 +265,24 @@ class BlockCrsMatrix :
   //@{
 
   //! Get the (point) domain Map of this matrix.
-  Teuchos::RCP<const map_type> getDomainMap () const;
+  Teuchos::RCP<const map_type> getDomainMap () const override;
```
Comment (bathmatt) [inline packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp:269]: @ppebay can you see this

Comment (ppebay) [reply packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp:269]: @bathmatt Yes I can. Thanks.

File: packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp [hunk 2]
```diff
@@ -1234,13 +1234,13 @@ class BlockCrsMatrix :
   getGlobalRowCopy (GO GlobalRow,
                     nonconst_global_inds_host_view_type &Indices,
                     nonconst_values_host_view_type &Values,
-                    size_t& NumEntries) const;
+                    size_t& NumEntries) const override;
 #ifdef TPETRA_ENABLE_DEPRECATED_CODE
```
Comment (ppebay) [inline packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp:1238]: I am assuming that these `#ifdef TPETRA_ENABLE_DEPRECATED_CODE` directives will be removed later on, right?

Comment (bathmatt) [reply packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp:1238]: Not until they go away from tpetra, we'll remove all of them at the same time

**Comment by bathmatt** [comment]
@jhux2 i can't test MueLu on my mac with develop, i have 6 test failures.  Not sure if I need to turn something on.

can you review my cmake script and see what I have wrong?

These are the failures

```
	 21 - MueLu_MasterList_MPI_1 (Failed)
	 48 - MueLu_UnitTestsTpetra_MPI_1 (Failed)
	 49 - MueLu_UnitTestsTpetra_MPI_4 (Failed)
	 50 - MueLu_UnitTestsBlockedTpetra_MPI_1 (Failed)
	 90 - MueLu_ParameterListInterpreterEpetra_MPI_1 (Failed)
	 94 - MueLu_ParameterListInterpreterEpetraHeavy_MPI_1 (Failed)
```

[temp.txt](https://github.com/trilinos/Trilinos/files/6603232/temp.txt)

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp [hunk 3]
```diff
@@ -486,41 +486,66 @@ namespace Xpetra {
...
     }
 
 
     template<class Scalar, class LocalOrdinal, class GlobalOrdinal, class Node>
     void 
     TpetraBlockCrsMatrix<Scalar,LocalOrdinal,GlobalOrdinal,Node>::
     getGlobalRowCopy(GlobalOrdinal GlobalRow, 
-                     const ArrayView< GlobalOrdinal > &indices, 
-                     const ArrayView< Scalar > &values, 
-                     size_t &numEntries) const
```
Comment (ppebay) [inline packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:511]: Just to make sure regarding code style in Trilinos (or maybe only Xpetra): is first letter capitalization and mixed/camel case for subsequent words a requirement? Or just a matter of preference here?

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp [hunk 4]
```diff
@@ -486,41 +486,66 @@ namespace Xpetra {
...
+        typename Tpetra::CrsGraph<LocalOrdinal,GlobalOrdinal,Node>::nonconst_global_inds_host_view_type indices("indices",Indices.size());
+        typename Tpetra::CrsMatrix<Scalar,LocalOrdinal,GlobalOrdinal,Node>::nonconst_values_host_view_type values("values", Values.size());
 
-    template<class Scalar, class LocalOrdinal, class GlobalOrdinal, class Node>
-    void 
-    TpetraBlockCrsMatrix<Scalar,LocalOrdinal,GlobalOrdinal,Node>::
-    getLocalRowView(LocalOrdinal LocalRow, ArrayView< const LocalOrdinal > &indices, 
-                    ArrayView< const Scalar > &values) const
-    { XPETRA_MONITOR("TpetraBlockCrsMatrix::getLocalRowView"); mtx_->getLocalRowView(LocalRow, indices, values); }
+        mtx_->getGlobalRowCopy(GlobalRow, indices, values, NumEntries);
```
Comment (ppebay) [inline packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:543]: Is there a defined meaning for the underscore in the Trilinos naming scheme?  Is this used in order to name member variables (and therefore remove the need to use the `this` pointer)?

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp (hunk 3 above)
Comment (bathmatt) [reply packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:511]: It's a mixed bag, i try to keep the same local scope,

MyClass and myVar seems to be the standard

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp (hunk 4 above)
Comment (bathmatt) [reply packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:543]: Trilinos packages have a mixed set of standards. every class means a different code standard, but typically var_ is a member var, but not always, _t is also almost always a type

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp (hunk 3 above)
Comment (ppebay) [reply packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:511]: Okay noted, so `MyVar` for member vars, and `myVar` for local vars?

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp (hunk 4 above)
Comment (ppebay) [reply packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:543]: Okay noted. The latter is _almost_ part of the standard; so it's good practice to self-enforce it. 

Regarding the latter, I favor using the `this` pointer rather than non-standardized underscore-based mangling. But if it's not a Trilinos requirement I will just stop being pedantic right here.

**Comment by jhux2** [comment]
> @jhux2 i can't test MueLu on my mac with develop, i have 6 test failures. Not sure if I need to turn something on.
> 
> can you review my cmake script and see what I have wrong?
> 
> These are the failures
> 
> ```
> 	 21 - MueLu_MasterList_MPI_1 (Failed)
> 	 48 - MueLu_UnitTestsTpetra_MPI_1 (Failed)
> 	 49 - MueLu_UnitTestsTpetra_MPI_4 (Failed)
> 	 50 - MueLu_UnitTestsBlockedTpetra_MPI_1 (Failed)
> 	 90 - MueLu_ParameterListInterpreterEpetra_MPI_1 (Failed)
> 	 94 - MueLu_ParameterListInterpreterEpetraHeavy_MPI_1 (Failed)
> ```
> 
> [temp.txt](https://github.com/trilinos/Trilinos/files/6603232/temp.txt)

@bathmatt Were these due to Amesos2 being off?  Otherwise, can you rerun `ctest -V` so we can see the details?

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp (hunk 4 above)
Comment (bathmatt) [reply packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:543]: this pointer can get overly verbose.  
Matts style is MyClass/myFunc/my_var_/my_arg
if you're uniform then you can really understand what the code is doing.  

You want the code readable but you want it to fit on a screen and a line so there's a balance.

**Comment by bathmatt** [comment]
> > @jhux2 i can't test MueLu on my mac with develop, i have 6 test failures. Not sure if I need to turn something on.
> > can you review my cmake script and see what I have wrong?
> > These are the failures
> > ```
> > 	 21 - MueLu_MasterList_MPI_1 (Failed)
> > 	 48 - MueLu_UnitTestsTpetra_MPI_1 (Failed)
> > 	 49 - MueLu_UnitTestsTpetra_MPI_4 (Failed)
> > 	 50 - MueLu_UnitTestsBlockedTpetra_MPI_1 (Failed)
> > 	 90 - MueLu_ParameterListInterpreterEpetra_MPI_1 (Failed)
> > 	 94 - MueLu_ParameterListInterpreterEpetraHeavy_MPI_1 (Failed)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [temp.txt](https://github.com/trilinos/Trilinos/files/6603232/temp.txt)
> 
> @bathmatt Were these due to Amesos2 being off? Otherwise, can you rerun `ctest -V` so we can see the details?

Here is the output from the testing full verbose
[LastTest.log](https://github.com/trilinos/Trilinos/files/6611381/LastTest.log)

**Review by bathmatt — COMMENTED** [review]
@jhux2 this is ready to review, i've not tested with cuda yet because of lack of resources (my cryptocard round 2 is on it's way).  I'm still doing a bit more testing but . . . let's have a looksee and see if you have any big feedback issues.

**Comment by bathmatt** [comment]
@rppawlo why isn't the autotester firing off on this MR?

**Comment by rppawlo** [comment]
> @rppawlo why isn't the autotester firing off on this MR?

Not sure. I'll add the retest label to see if that triggers it. @trilinos/framework any ideas why this is not starting?

**Comment by prwolfe** [comment]
The autotester will not run until the code has been reviewed because the fork it is coming from is not a Trilinos developer in our list.

File: packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp [hunk 5]
```diff
@@ -368,6 +369,7 @@ namespace Xpetra {
       return test;
```
Comment (kyungjoo-kim) [inline packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp:369]: If t_dev_um is unmanaged device view of a dual view, this interface is problematic in my opinion. Tpetra with UVM removal does not allow users taking a pointer nor unmanaged view. This is because we want to communicate host and device sync be comparing reference counts. If this pattern is used widely, this interface needs to be fixed.

@kddevin

Comment (kyungjoo-kim) [reply packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp:369]: Oh... I am sorry that I misunderstand this code. I don't know why we need this interface returning a dummy view. This is not an actual Tpetra member dual view. So the code itself is fine. If this dummy view is used to get unmanaged view to take Tpetra internal member variable, it is still a bit dangerous as it removes reference counting.

**Review by kyungjoo-kim — APPROVED** [review]
Looks fine to me for the changes. One concern from the existing code (not related to this PR) is the usage of the unmanaged views. With UVM removal, using unmanaged views might be dangerous.

File: packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp (hunk 5 above)
Comment (bathmatt) [reply packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp:369]: I didn't really change that code, I just put it in the ifdef deprecated code and might have cleaned it up some.  It was all over, now it is deprecated,

Comment (kyungjoo-kim) [reply packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp:369]: Ah... this interface will be gone. Good~.

**Comment by bathmatt** [comment]
i realized I can clean up the interface a lot more so i'm working that right now

**Comment by bathmatt** [comment]
@jhux2 i systematically went through and cleaned up all the getLocalView variants, removed about 600 lines, pushed this today,

File: packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp [hunk 6]
```diff
@@ -1086,16 +1080,6 @@ namespace Xpetra {
...
-    template<class TargetDeviceType>
-    typename Kokkos::Impl::if_c<
-      std::is_same<
-        typename dual_view_type::t_dev_um::execution_space::memory_space,
-        typename TargetDeviceType::memory_space>::value,
-        typename dual_view_type::t_dev_um,
-        typename dual_view_type::t_host_um>::type
-    getLocalView () const {
-      return this->MultiVector< Scalar, LocalOrdinal, GlobalOrdinal, Node >::template getLocalView<TargetDeviceType>();
-    }
```
Comment (bathmatt) [inline packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp]: This is gone everywhere but in the two classes that need it

File: packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp [hunk 7]
```diff
@@ -359,6 +353,88 @@ class MultiVector
...
+    /// \tparam TargetDeviceType The Kokkos Device type whose data to return.
+    ///
+    /// \warning Be aware that the view on the multivector data is non-persisting, i.e.
+    ///          only valid as long as the multivector does not run of scope!
+    template<class TargetDeviceType, class AccessType>
+    typename Kokkos::Impl::if_c<std::is_same<typename dev_execution_space::memory_space, typename TargetDeviceType::memory_space>::value,
+                                typename dual_view_type::t_dev_um,
+                                typename dual_view_type::t_host_um>::type
+    getLocalView(AccessType access_type) const
+    {
```
Comment (bathmatt) [inline packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp]: Not virtual anymore,

**Comment by bathmatt** [comment]
squashed MR

**Review by jhux2 — CHANGES_REQUESTED** [review]
@bathmatt Just a few minor comments.

File: packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp [hunk 8]
```diff
@@ -327,42 +327,6 @@ const Epetra_IntMultiVector & toEpetra(const MultiVector<int, int, GlobalOrdinal
...
-        typename TargetDeviceType::memory_space>::value,
-        typename dual_view_type::t_dev_um,
-        typename dual_view_type::t_host_um>::type
-    getLocalView () const {
-      return this->MultiVector< Scalar, LocalOrdinal, GlobalOrdinal, Node >::template getLocalView<TargetDeviceType>();
-    }
-#endif
-
-    //@}
-
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp:365]: Is this not tested in MueLu?  We pass all of them, I'm pretty sure this will call the MutliVector call...

[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp:365]: I can put this back but looking at the code I don't see why the call here which just calls the multivector instance is any different than calling the one from the class hierarchy defined here

  class EpetraIntMultiVectorT
    : public MultiVector<int,int,EpetraGlobalOrdinal, Node>

Since MultiVector<> has a concrete def of getLocalView it will be defined without the reference.

Let me know if you want the explicit nature of this but my feeling is if we can compile the full stack and the tests pass then it isn't needed.  I'm close to building EMPIRE and that will test it as well

File: packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_decl.hpp [hunk 9]
```diff
@@ -461,8 +461,14 @@ class CrsMatrixWrap :
 
 #ifdef HAVE_XPETRA_KOKKOS_REFACTOR
 #ifdef HAVE_XPETRA_TPETRA
-  /// \brief Access the underlying local Kokkos::CrsMatrix object
-  local_matrix_type getLocalMatrix () const;
+#ifdef TPETRA_ENABLE_DEPRECATED_CODE
+  virtual typename local_matrix_type::HostMirror getLocalMatrix () const{
+    return getLocalMatrixHost();
+  }
+#endif
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_decl.hpp:468]: moved

File: packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp [hunk 10]
```diff
@@ -1072,61 +1014,6 @@ namespace Xpetra {
...
-    typename dual_view_type::t_dev_um getDeviceLocalView() const {
-      throw std::runtime_error("Epetra does not support device views!");
-#ifndef __NVCC__ //prevent nvcc warning
-      typename dual_view_type::t_dev_um ret;
-#endif
-      TEUCHOS_UNREACHABLE_RETURN(ret);
-    }
-
-#endif
-
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp:1129]: same as above

**Comment by bathmatt** [comment]
@jhux2 I fixed some of the comments but didn't readd those defs.  I think it is a mistake and should let the auto-tester find any issues.  I ran the tests by hand up to panzer and it looks good (panzer/xpetra/muelu) 

I get the identical behavior between develop and my branch.

If you are o.k. w/ this hit approve and we'll test and merge, if you really want those defs back in let me know and I'll readd them

**Review by jhux2 — DISMISSED** [review]
Let's see what the autotester thinks.

**Comment by bathmatt** [comment]
I found cuda issues with some of the tests, let this run and if it passes CPU that's good, but it will fail GPU

**Comment by bathmatt** [comment]
> I found cuda issues with some of the tests, let this run and if it passes CPU that's good, but it will fail GPU

Turns out those were only required cuz i have UVM off, going to be part of the UVM free branch which I have only two sub-tests failing

**Comment by bathmatt** [comment]
@trilinos/framework  is the auto tester down?  Ihave an approved review and this PR sat all weekend w/o running any tests. 
Thanks

File: packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp [hunk 11]
```diff
@@ -803,6 +828,20 @@ getLocalMatrix () const
...
 }
 
+template<class Scalar, class LocalOrdinal, class GlobalOrdinal, class Node>
+typename CrsMatrix<Scalar,LocalOrdinal,GlobalOrdinal,Node>::local_matrix_type::HostMirror
+TpetraBlockCrsMatrix<Scalar,LocalOrdinal,GlobalOrdinal,Node>::
+getLocalMatrixHost () const
+{
+    throw std::runtime_error("Xpetra::TpetraBlockCrsMatrix does not support getLocalMatrix due to missing Kokkos::CrsMatrix in Tpetra's experimental implementation in "+std::string(__FILE__)+":"+std::to_string(__LINE__));
+
+#ifndef __NVCC__
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp:838]: I coded to the style that was near by, i cut and paste that in from another throw

File: packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp [hunk 12]
```diff
@@ -1486,14 +1486,27 @@ namespace Xpetra {
...
+    }
+#endif
+    /// \brief Access the underlying local Kokkos::CrsMatrix object
+    local_matrix_type getLocalMatrixDevice () const {
+      if (Rows() == 1 && Cols () == 1) {
+        return getMatrix(0,0)->getLocalMatrixDevice();
+      }
+      throw Xpetra::Exceptions::RuntimeError("BlockedCrsMatrix::getLocalMatrix(): operation not supported.");
+    }
     /// \brief Access the underlying local Kokkos::CrsMatrix object
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp:1501]: Isn't it just below on line 1502?

File: packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp [hunk 13]
```diff
@@ -1177,7 +1203,18 @@ class EpetraCrsGraphT<long long, EpetraNode>
...
 #ifdef HAVE_XPETRA_TPETRA
-  local_graph_type getLocalGraph () const {
+  local_graph_type getLocalGraphHost () const {
+    TEUCHOS_TEST_FOR_EXCEPTION(true, Xpetra::Exceptions::NotImplemented,
+                               "Epetra does not support Kokkos::StaticCrsGraph!");
+    TEUCHOS_UNREACHABLE_RETURN((local_graph_type()));
+  }
+#else
+#ifdef __GNUC__
+#warning "Xpetra Kokkos interface for CrsGraph is enabled (HAVE_XPETRA_KOKKOS_REFACTOR) but Tpetra is disabled. The Kokkos interface needs Tpetra to be enabled, too."
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp:1213]: This choice was made for getLocalGraph before, not sure why it was made honestly.  Just copied the code for host and device versions

File: packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp [hunk 14]
```diff
@@ -265,24 +265,24 @@ class BlockCrsMatrix :
   //@{
 
   //! Get the (point) domain Map of this matrix.
-  Teuchos::RCP<const map_type> getDomainMap () const;
+  Teuchos::RCP<const map_type> getDomainMap () const override;
```
[the remark this answers is not in the document]
Comment (bathmatt) [reply packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp:268]: clang complained so I added them, I can remove them if you really want

**Comment by jwillenbring** [comment]
@bathmatt Yes, there is a problem with the autotester that is being looked at.

**Comment by bathmatt** [comment]
able to reproduce the build failures, will get them fixed,

**Comment by bathmatt** [comment]
It was issues of building with complex and casting from kokkos::complex to std::complex...

**Comment by bathmatt** [comment]
@trilinos/framework question on the PR testing, I followed the instructions but I am seeing errors in Panzer which are related to python errors

I tried using /usr/bin/python and then I loaded anaconda3 and both gave errors.  What python is required?

Thanks
Matt

**Comment by bathmatt** [comment]
@jhux2 this is ready now.
I created a PR, 9290, where I was able to run the PR tester and it passed last night.  

I think this is ready for one last look over, approval and merge.

**Review by lucbv — DISMISSED** [review]
Let me approve this to see how the auto-tester like it.

**Comment by bathmatt** [comment]
UGH, the PR tester glitched on gcc8 config of all things


https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-9230-test&field2=buildstarttime&compare2=84&value2=NOW

can someone add the retest flag please,

**Comment by bathmatt** [comment]
@jhux2  can you hit the merge button if you're o.k. with the changes.  All the tests pass

**Comment by bathmatt** [comment]
So, the tests all passed then someone pushed a conflicting push so I just pushed a fix for the conflict.  Someoen will have to approve and I'd like to get this merged soon so we don't have more conflicts.

File: packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp [hunk 15]
```diff
@@ -1486,14 +1486,27 @@ namespace Xpetra {
 
 #ifdef HAVE_XPETRA_KOKKOS_REFACTOR
     typedef typename CrsMatrix::local_matrix_type local_matrix_type;
-
+#ifdef TPETRA_ENABLE_DEPRECATED_CODE
```
[the remark this answers is not in the document]
Comment (lucbv) [reply packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp:1489]: This code does not rely on deprecated code from Tpetra so why not use `XPETRA_ENABLE_DEPRECATED_CODE` here?
Same question applies to a few more spots below.

File: packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp [hunk 16]
```diff
@@ -326,8 +326,12 @@ namespace Xpetra {
     void getLocalRowView(LocalOrdinal LocalRow, ArrayView< const LocalOrdinal > &indices) const;
 
 #ifdef HAVE_XPETRA_KOKKOS_REFACTOR
-    /// \brief Access the local KokkosSparse::StaticCrsGraph data
-    local_graph_type getLocalGraph () const;
```
Comment (lucbv) [inline packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp:330]: We do not keep this one within a `TPETRA_ENBALE_DEPRECATED_CODE` scope like we do for the CrsMatrix?

File: packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp [hunk 17]
```diff
@@ -726,7 +739,19 @@ class EpetraCrsGraphT<int, EpetraNode>
 
 #ifdef HAVE_XPETRA_KOKKOS_REFACTOR
 #ifdef HAVE_XPETRA_TPETRA
-  local_graph_type getLocalGraph () const {
```
Comment (lucbv) [inline packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp:729]: Same as below (I'm going bottom to top for some reason...) why not keep in `TPETRA_ENABLE_DEPRECATED_CODE` scope?

File: packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp [hunk 18]
```diff
@@ -244,7 +244,14 @@ namespace Xpetra {
     ///
     /// This is only a valid representation of the local graph if the
     /// (global) graph is fill complete.
-    virtual local_graph_type getLocalGraph () const = 0;
```
Comment (lucbv) [inline packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp:247]: Same as below

File: packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp (hunk 16 above)
Comment (bathmatt) [reply packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp:330]: Because this wasn't used anywhere in the code so I could get rid of it, I can add it and have it return device graph but it isn't tested or used

Comment (bathmatt) [reply packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp:330]: @lucbv you o.k. with the way it is?

Comment (lucbv) [reply packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp:330]: Yes, I am fine with it, I actually think it's good to remove the old mechanics when it is not needed.
I have reviewed all the changes and I think this can be merged, let me ask quickly the rest of the team before I press the merge button.
