### PR TITLE
Intrepid2: fix 13945 (MKL Failures PYR_QuadFace, PYR_TriFace)

### LINKED ISSUE #13945: Intrepid2: MKL Failures in PYR_QuadFace_newBasis_Serial_DOUBLE, PYR_TriFace_newBasis_Serial_DOUBLE tests
## Bug Report
@trilinos/intrepid2 As documented in PR #13881 and previously recorded in issue #12390, tests `PYR_QuadFace_newBasis_Serial_DOUBLE` and `PYR_TriFace_newBasis_Serial_DOUBLE` fail when run with MKL.  

### Description
This has now been diagnosed as a more general failure that is simply obscured with other LAPACK implementations; MKL checks matrix values during a call to `dgels`, and aborts due to a combination of Inf and/or NaN values.  The presenting issue is that the prescribed vertices for the pyramid element used include a single vertex twice, leading to a singular Jacobian.  For reasons that are not entirely clear, the tests have been passing for LAPACK implementations that do not check the matrix prior to invocation of `dgels`, despite the fact that inspection shows that these too have intermediate Inf and NaN values.  However, simply fixing that issue is insufficient to get the test to pass.  Outside of some offline tests against a separate implementation (posed on a different reference pyramid), the H(div) pyramid basis is essentially only tested by these two tests; so the fact that they were not executing as expected means that these have not been tested.  These tests require substantial revision, as they assume a basis that is polynomial not just in the normal direction from a specified interface (the actual guarantee from the H(div) basis), but one that is polynomial on the interior.  This assumption is not satisfied by the higher-order bases on the pyramid.

### Steps to Reproduce
1. See discussion under #13881.

### PR DESCRIPTION
**Pull request by CamelliaDPG**
Intrepid2: Fix #13945

This PR addresses both #13945 and a number of issues with the H(div) pyramid basis and tests against it revealed in the course of fixing the test failures.

@trilinos/intrepid2

## Related Issues
#13881 
Closes #13945 

## Additional Information
@sebrowne I have confirmed in the context of the Docker container referred to in #13881 that these changes allow the PYR_QuadFace, PYR_TriFace orientation tests to be re-enabled (i.e., they pass there).

### CODE REVIEW

File: packages/intrepid2/unit-test/Orientation/test_orientation_PYR_QuadFace_newBasis.hpp [hunk 1]
```diff
@@ -501,32 +565,32 @@ int OrientationPyrQuadFaceNewBasis(const bool verbose) {
...
-              for(ordinal_type j=0; j<numRefCoords; ++j)
-                for(std::size_t k=0; k<pyramid.getNodeCount(); ++k)
-                  physRefCoords(i,j,d) += vertices[pyrs[i][k]][d]*pyramidLinearBasisValuesAtRefCoords(k,j);
-            }
-        }
-
-
         //HGRAD BASIS
         {
+          //compute reference points: use a lattice on the quad base of the pyramid
```
Comment (CamelliaDPG) [inline packages/intrepid2/unit-test/Orientation/test_orientation_PYR_QuadFace_newBasis.hpp:570]: Inaccurate; fix this.

**Comment by sebrowne** [comment]
Could you re-enable the two Intrepid2 tests in `config-specs.ini` for the `oneapi-intelmpi` build as part of this change?

**Review by mperego — APPROVED** [review]
Thanks Nate. It looks good to me.

**Review by mperego — APPROVED** [review]
Thanks @CamelliaDPG  for adding comments to the tests.
