### PR TITLE
Import stk

### LINKED ISSUE #3347: stk broken in clean Linux-gcc-4.8.4-MPI_Release_gcc_4.8.4_openmpi_1.8.7_DEV build
Looks like the recent import of stk (commit de635abc146449dc1c4dbbea65cefda91946755e) caused failures in the Linux-gcc-4.8.4-MPI_Release_gcc_4.8.4_openmpi_1.8.7_DEV build.

Gcc 4.8.4 does not support brace-list initialization which is used in one of the unit tests. This was turned off in the PR testing, but looks like it was missed in this build. See commit 465f04753fcb8e6bf7047cc03d1cce54e254d25f for details.

@trilinos/framework 
@trilinos/stk

### PR DESCRIPTION
**Pull request by prwolfe**
This should resolve issue #3347 and #3348 by importing new development from the Sierra stream.

@trilinos/stk 

## Description
Correction for a serial build issue
Correction for a 4.8.4 problem with initialization lists. Also re-enables the affected test.
New fix for a template specialization that was being handled incorrectly by all compilers and A lot of remedial work to get 4.8.4 to handle that.

## Motivation and Context
This should get the clean and continuous builds back to normal and resolve a test that was previously disabled.

## Related Issues

* Closes #3347 and #3348

### CODE REVIEW

File: packages/stk/stk_math/unit_tests/UnitTestStkMathMain.cpp [hunk 1]
```diff
@@ -0,0 +1,55 @@
+// Copyright (c) 2013, Sandia Corporation.
+// Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
```
Comment (mhoemmen) [inline packages/stk/stk_math/unit_tests/UnitTestStkMathMain.cpp]: We may need to update the copyright notices with the new contract information at some point.

File: packages/stk/stk_math/unit_tests/UnitTestStkMathMain.cpp [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    Kokkos::initialize(argc, argv);
+
+    testing::InitGoogleTest(&argc, argv);
+
+    gl_argc = argc;
+    gl_argv = argv;
+
+    int returnVal = RUN_ALL_TESTS();
+
+    Kokkos::finalize_all();
```
Comment (mhoemmen) [inline packages/stk/stk_math/unit_tests/UnitTestStkMathMain.cpp]: This function may have been deprecated.  Just call Kokkos::finalize, or use Kokkos::ScopeGuard as a replacement for initialize and finalize.

**Comment by prwolfe** [comment]
These results are off. This mornings had communication errors on 2 of the 3 jobs and the sets from overnight failed with no error output. The first tun failed in 4.9.3 and the second in 4.8.4 and with different objects.

From the 4.9.3 failure I see java io errors
{{{
FATAL: command execution failed
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2638)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3113)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Caused: java.io.IOException: Backing channel 'ascic142-trilinos' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
	at com.sun.proxy.$Proxy95.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1137)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1129)
	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1794)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
}}}
Which matches those from the overnight runs and we had almost identical issues from the 4.8.4 build. Surprised they reported to cdash really. I will talk with Jim Glenn again. - grrrr.
