### PR TITLE
RefMaxwell&Epetra stuff

### LINKED ISSUE #6434: MueLu:  DriverEpetra_CircNspDependency fails/hangs
## Bug Report
@trilinos/muelu 

### Description
The test ``MueLu_DriverEpetra_CircNspDependency_MPI_4`` in test/scaling fails because "P" is not stored in the level. Discovered while testing tpetra-remove-deprecated branch but it happens in develop too.

### Steps to Reproduce
1. SHA1: b339e54
2. [Configure script](https://gist.github.com/brian-kelley/49f7e06477054f0b4457b8b5c4be00ed) although several packages are unrelated and could be disabled.

Test output (prints the message and then hangs/times out)
```
...
Level 2
Laplace2D: Build (MueLu::RebalanceTransferFactory)
Laplace2D: Build (MueLu::RepartitionFactory)
Laplace2D: Computing Ac (MueLu::RAPFactory)
Laplace2D: Prolongator smoothing (MueLu::SaPFactory)
Laplace2D: Build (MueLu::TentativePFactory)
Laplace2D: Build (MueLu::UncoupledAggregationFactory)
Laplace2D: Build (MueLu::CoalesceDropFactory)
PreDropFunctionConstVal: threshold = 0
Laplace2D: Build (MueLu::AmalgamationFactory)
AmalagamationFactory::Build(): found fullblocksize=1 and stridedblocksize=1 from strided maps. offset=0
[empty list]

lightweight wrap = 1
algorithm = "classical": threshold = 0.00, blocksize = 1

******* WARNING *******
Level::Set: unable to store "Filtering" generated by factory CoalesceDropFactory[1](0xb134f0) on level 1, as it has not been requested and no keep flags were set for it
Detected 0 Dirichlet nodes
Number of dropped entries in unamalgamated matrix graph: 0/15318 (0.00%)
aggregation: drop tol = 0.00   [default]
aggregation: Dirichlet threshold = 0.00   [default]
aggregation: drop scheme = classical   [default]
lightweight wrap = 1

Laplace2D: Algo "Phase - (Dirichlet)"
BuildAggregates (Phase - (Dirichlet))
  aggregated : 0 (phase), 0/1700 [0.00%] (total)
  remaining  : 1700
  aggregates : 0 (phase), 0 (total)
Laplace2D: Algo "Phase 1 (main)"
BuildAggregates (Phase 1 (main))
  aggregated : 1638 (phase), 1638/1700 [96.35%] (total)
  remaining  : 62
  aggregates : 197 (phase), 197 (total)
Laplace2D: Algo "Phase 2a (secondary)"
BuildAggregates (Phase 2a (secondary))
  aggregated : 0 (phase), 1638/1700 [96.35%] (total)
  remaining  : 62
  aggregates : 0 (phase), 197 (total)
Laplace2D: Algo "Phase 2b (expansion)"
BuildAggregates (Phase 2b (expansion))
  aggregated : 62 (phase), 1700/1700 [100.00%] (total)
  remaining  : 0
  aggregates : 0 (phase), 197 (total)
Laplace2D: Algo "Phase 3 (cleanup)"
BuildAggregates (Phase 3 (cleanup))
  aggregated : 0 (phase), 1700/1700 [100.00%] (total)
  remaining  : 0
  aggregates : 0 (phase), 197 (total)
"UC": MueLu::Aggregates{nGlobalAggregates = 197}
aggregation: max agg size = -1   [default]
aggregation: min agg size = 2   [unused]
aggregation: max selected neighbors = 0   [unused]
aggregation: ordering = natural   [unused]
aggregation: enable phase 1 = 1   [default]
aggregation: enable phase 2a = 1   [default]
aggregation: enable phase 2b = 1   [default]
aggregation: enable phase 3 = 1   [default]
aggregation: preserve Dirichlet points = 0   [default]
aggregation: allow user-specified singletons = 0   [default]
aggregation: use interface aggregation = 0   [default]
aggregation: error on nodes with no on-rank neighbors = 0   [default]
aggregation: phase3 avoid singletons = 0   [default]
OnePt aggregate map name =    [default]
OnePt aggregate map factory =    [default]
Interface aggregate map name =    [default]
Interface aggregate map factory =    [default]

Laplace2D: Nullspace factory (MueLu::NullspaceFactory)
Fine level nullspace = Nullspace

Laplace2D: Build (MueLu::CoarseMapFactory)
Striding info = {}   [default]
Strided block id = -1   [default]
Domain GID offsets = {0}   [default]

Laplace2D: Build (MueLu::RebalanceTransferFactory)
MueLu_Driver: preconditioner setup crashed w/ message:/ascldap/users/bmkelle/DeprecatedTpetra/Trilinos/packages/muelu/src/Interface/../MueCentral/MueLu_Level.hpp:197:

Throw number = 3

Throw test that evaluated to true: !IsKey(fac, ename)

"P" not found
MueLu_Driver: Not solving system due to crash in preconditioner setup
```

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
- Create RefMaxwell timers only when requested, same as rest of MueLu.
- Fix failing TrilinosCouplings examples, see #6570 
- Fix #6434

### CODE REVIEW

**Comment by cgcgcg** [comment]
Yes, it should, but they are not getting passed along correctly. Since they aren't even needed at all, might as well skip them.

File: packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp [hunk 1]
```diff
@@ -743,8 +743,11 @@ namespace MueLu {
       GetOStream(Runtime0) << "RefMaxwell::compute(): nuking BC nodes of D0" << std::endl;
 
       D0_Matrix_->resumeFill();
-      // Scalar replaceWith = Teuchos::ScalarTraits<SC>::eps();
-      Scalar replaceWith = Teuchos::ScalarTraits<SC>::zero();
+      Scalar replaceWith;
+      if (D0_Matrix_->getRowMap()->lib() == Xpetra::UseEpetra)
+        replaceWith= Teuchos::ScalarTraits<SC>::eps();
+      else
+        replaceWith = Teuchos::ScalarTraits<SC>::zero();
```
Comment (jhux2) [inline packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp:750]: Why is this necessary?

Comment (cgcgcg) [reply packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp:750]: The implicit transpose matrix multiply in Epetra seems to produce an invalid matrix when we have explicit zeros in D0. I have not tried to track this down in Epetra.
