### PR TITLE
MueLu: fix for issue #4334

### LINKED ISSUE #4334: Albany build failing in MueLu: AggregationStructuredAlgorithm_kokkos
@trilinos/muelu 

## Current Behavior

```
.../Trilinos/packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_def.hpp:221:39: error: unknown type name 'AggregationStructuredAlgorithm_kokkos'; did you mean 'AggregationStructuredAlgorithm'?

      myStructuredAlgorithm = rcp(new AggregationStructuredAlgorithm_kokkos());
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      AggregationStructuredAlgorithm
/.../Trilinos/packages/muelu/src/Interface/../Headers/MueLu_UseShortNamesOrdinal.hpp:36:80: note: 'AggregationStructuredAlgorithm' declared here
typedef MueLu::AggregationStructuredAlgorithm<LocalOrdinal,GlobalOrdinal,Node> AggregationStructuredAlgorithm;
                                                                               ^
```

### PR DESCRIPTION
**Pull request by lucbv**
Forgot to add a forward declaration that triggers the correct definition of a short name in MueLu.

silencing warning from IndexManager_kokkos.cpp by removing unused declartion of GOInvalid.
silencing warning in CreatePreconditioner.cpp due to instantiation guards and variable early declaration.
silencing compiler warning in unit_tests/Utilities.cpp and unit_tests/Smoothers/Blocked{Smoothers,DirectSolver}.cpp due to pedantic comparison of a size_t variable with 0

@trilinos/muelu 

## Description
See above.

## Motivation and Context
This will fix an issue that is blocking a Cuda build of Sierra

## Related Issues

* Closes #4334 

## How Has This Been Tested?
Local build and tests were run on MueLu after fix.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

File: packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp [hunk 1]
```diff
@@ -439,7 +439,7 @@ namespace MueLuTests {
       Teuchos::ArrayRCP<const Scalar> xdata = XX->getData(0);
       bool bCheck = true;
       for(size_t i=0; i<XX->getLocalLength(); i++) {
-        if (i>=0  && i< 5) { if(xdata[i] != (SC) 1.0) bCheck = false; }
+        if (i< 5) { if(xdata[i] != (SC) 1.0) bCheck = false; }
```
Comment (mhoemmen) [inline packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp]: Preferred "promotion to SC" form is `SC (1.0)`.

File: packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp [hunk 2]
```diff
@@ -721,7 +721,7 @@ namespace MueLuTests {
       Teuchos::ArrayRCP<const Scalar> xdata = XX->getData(0);
       bool bCheck = true;
       for(size_t i=0; i<XX->getLocalLength(); i++) {
-        if (i>=0  && i< 10) { if(xdata[i] != (SC) (1.0/3.0)) bCheck = false; }
+        if (i<10) { if(xdata[i] != (SC) (1.0/3.0)) bCheck = false; }
```
Comment (mhoemmen) [inline packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp]: See above.

File: packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp (hunk 1 above)
Comment (lucbv) [reply packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp]: Yeah, I would probably go with `Teuchos::as<SC>(1.0)` or actually `Teuchos::ScalarTrait<SC>::one()`, but this does not bug me enough to fire the auto-tester a seond time x)

**Comment by mhoemmen** [comment]
Uh oh (this is the CUDA build):
```
g++: internal compiler error: Killed (program cc1plus) 0x40e3e8 execute 	../.././gcc/gcc.c:2823 0x40e734 do_spec_1 	../.././gcc/gcc.c:4615 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x40f468 do_spec_1 	../.././gcc/gcc.c:5374 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 Please submit a full bug report, with preprocessed source if appropriate. Please include the complete backtrace with any bug report. See <http://gcc.gnu.org/bugs.html> for instructions. | g++: internal compiler error: Killed (program cc1plus) 0x40e3e8 execute 	../.././gcc/gcc.c:2823 0x40e734 do_spec_1 	../.././gcc/gcc.c:4615 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x40f468 do_spec_1 	../.././gcc/gcc.c:5374 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 Please submit a full bug report, with preprocessed source if appropriate. Please include the complete backtrace with any bug report. See <http://gcc.gnu.org/bugs.html> for instructions.
-- | --
g++: internal compiler error: Killed (program cc1plus) 0x40e3e8 execute 	../.././gcc/gcc.c:2823 0x40e734 do_spec_1 	../.././gcc/gcc.c:4615 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x40f468 do_spec_1 	../.././gcc/gcc.c:5374 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 0x40f6de do_spec_1 	../.././gcc/gcc.c:5269 0x41123b process_brace_body 	../.././gcc/gcc.c:5872 0x41123b handle_braces 	../.././gcc/gcc.c:5786 Please submit a full bug report, with preprocessed source if appropriate. Please include the complete backtrace with any bug report. See <http://gcc.gnu.org/bugs.html> for instructions.
```

**Comment by lucbv** [comment]
@mhoemmen this is not even the Cuda build, this is the gcc-4.8.4 build...
