### PR TITLE
Tpetra: Fix #4827; make more Tpetra classes follow Rule of Five; fix Tpetra::deep_copy for aliasing MV arguments

### LINKED ISSUE #4827: Tpetra::Details::copyConvert doesn't build for conversions between Kokkos::complex<float> and double
@trilinos/tpetra 

This breaks `Tpetra::deep_copy` between `MultiVector<std::complex<float>, ...>` and `MultiVector<double, ...>`.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/tpetra @trilinos/stokhos @trilinos/anasazi 

This pull request supersedes #4828.

## Description

1. Fix #4827.
2. Make more Tpetra classes follow the Rule of Five (C++ Core Guidelines C.21).
3. Clean up FEMultiVector code, syntax, and documentation.
4. Make sure that `Tpetra::deep_copy` between partially aliasing MultiVectors works.

Regarding the last point: the only test in Trilinos that exercises `Tpetra::deep_copy` for partially aliasing `Tpetra::MultiVector` objects is one `Anasazi::TraceMinDavidson` test.  This PR fixes that issue and makes the Anasazi test pass.

## Related Issues

* Closes #4827 
* Related to #4196, #3946, #3574

### CODE REVIEW

**Comment by mhoemmen** [comment]
@trilinos/tpetra Could someone please review this one?  Thanks! :-)

File: packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp [hunk 1]
```diff
@@ -119,7 +119,7 @@ void mult_A_B_newmatrix_LowThreadGustavsonKernel(CrsMatrixStruct<Scalar, LocalOr
   typedef typename KCRS::values_type::non_const_type scalar_view_t;
 
   // Unmanaged versions of the above
-  typedef UnmanagedView<lno_view_t> u_lno_view_t;
+  //typedef UnmanagedView<lno_view_t> u_lno_view_t; // unused
```
Comment (lucbv) [inline packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp]: Eventually we should really just get rid of this if it is unused...

File: packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp [hunk 2]
```diff
@@ -486,7 +486,7 @@ void jacobi_A_B_newmatrix_LowThreadGustavsonKernel(Scalar omega,
...
```
Comment (lucbv) [inline packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp]: Same as above

File: packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp (hunk 1 above)
Comment (mhoemmen) [reply packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp]: @lucbv I agree, but I'm a little shy to delete this, since I didn't write it.

File: packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp (hunk 2 above)
Comment (mhoemmen) [reply packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp]: See above.

File: packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp (hunk 1 above)
Comment (mhoemmen) [reply packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp]: Also, this is totally _not_ the main point of this PR.  The main point is fixing #4827.

**Comment by mhoemmen** [comment]
Thanks @lucbv ! :D

File: packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp (hunk 1 above)
Comment (mhoemmen) [reply packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp]: In general, though, I agree that we shouldn't be shy about deleting code like this.
