### PR TITLE
Ifpack2/Tpetra: fix #14529 and re-do of #14337

### LINKED ISSUE #14529: Ifpack2: BlockTriDiContainer tries to allocate huge amount of memory
In some cases, ``Ifpack2::BlockTriDiContainer`` tries to allocate a huge amount of memory for the view with label ``amd.A_x_offsets``. This allocation happens inside ``BlockHelperDetails::precompute_A_x_offsets``, which is one of the steps in symbolic setup.

Example output from when this is triggered:
```
Kokkos ERROR: HIP memory space failed to allocate 205.1 TiB (label="amd.A_x_offsets").
```

It looks like there are 2 possible causes:
- the allocation is a 3D view. One dimension is the result of a ``Kokkos::Max`` reduction, which will return the minimum value for the type (a very large negative number for signed ints) if the policy has 0 elements
- some value that the size depends on is uninitialized or garbage when precompute_A_x_offsets is called

- [ ] Find reproducer
- [ ] Add unit test
- [ ] Fix

### PR DESCRIPTION
**Pull request by brian-kelley**
- move BTD symbolic phase to device again
  - including workaround for #14529, by splitting the rowptr prefix sums out into separate kernels from the graph fill.
- Make ``Tpetra::Map::lazyPushToHost`` private again.

@trilinos/ifpack2 
@trilinos/tpetra 

## Motivation

Putting symbolic on device improves performance. This also resolves the failures SPARC saw from #14337 .

## Related Issues

* Fixes #14529 
* Follows #14337 and #14551
* Issue's root cause: https://github.com/kokkos/kokkos/issues/8607

### CODE REVIEW

**Comment by brian-kelley** [comment]
@cgcgcg This is the exact same PR you reviewed a long time ago for moving BTD symbolic phase to device, except now it can actually be merged since the cuda builds don't time out :tada:

File: packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp [hunk 1]
```diff
@@ -2184,59 +2192,48 @@ void performSymbolicPhase(const Teuchos::RCP<const typename BlockHelperDetails::
...
-        Kokkos::deep_copy(amd.A_colindsub_remote, R_A_colindsub_remote);
+      {
+        // Check that the last elements of R_rowptr (aka amd.rowptr)
+        // and R_rowptr_remote (aka amd.rowptr_remote) match the expected entry counts
+        auto r_rowptr_end = Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace(), Kokkos::subview(R_rowptr, nrows));
+        TEUCHOS_ASSERT(r_rowptr_end() == R_nnz_owned);
+        if (overlap_communication_and_computation) {
+          auto r_rowptr_remote_end = Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace(), Kokkos::subview(R_rowptr_remote, nrows));
+          TEUCHOS_ASSERT(r_rowptr_remote_end() == R_nnz_remote);
+        }
```
Comment (cgcgcg) [inline packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: Could this step be avoided by using the result of the prefix sum on line 2196 and 2197?

Comment (brian-kelley) [reply packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: Yes, good call. The Kokkos exclusive_scan from StdAlgorithms doesn't return that result back to you, but KokkosKernels has a prefix sum utility that does. This also lets us skip including Kokkos_StdAlgorithms.hpp.

Just pushed those changes.

**Review by cgcgcg — APPROVED** [review]
Thanks!

**Review by cgcgcg — APPROVED** [review]
