### PR TITLE
TrilinosCouplings: adding guard in exmaple_maxwell.cpp

### LINKED ISSUE #2786: TrilinosCouplings build failure
@trilinos/muelu
@trilinos/framework @maherou ~~There is no GitHub team for TrilinosCouplings~~
Edit: there is now, not sure if I just missed it

## Expectations

TrilinosCouplings should compile without error

## Current Behavior

```
packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp(152): catastrophic error: cannot open source file "MueLu_AztecEpetraOperator.hpp"
  #include <MueLu_AztecEpetraOperator.hpp>
```

## Motivation and Context

This is preventing snapshotting a new Kokkos version

### PR DESCRIPTION
**Pull request by lucbv**
@trilinos/trilinoscouplings 

## Description
This guard makes sure that MueLu_Epetra is enabled before include the MueLu_AztecEpetraOperator.hpp header.

## Motivation and Context
This is will allow the new builds that set `MueLu_ENABLE_Epetra=OFF` to compile `TrilinosCouplings` without problems

## Related Issues

* Closes #2786 

## How Has This Been Tested?
I did a local build of the with the configure-testbed-jenkins configuration to check that everything compiles properly

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

File: packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp [hunk 1]
```diff
@@ -149,7 +149,9 @@
 
 // MueLu
 #include <MueLu_RefMaxwell.hpp>
+#ifdef HAVE_MUELU_EPETRA
```
Comment (ndellingwood) [inline packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp]: @lucbv would it be more consistent to ifdef like below (line 229-ish) as 
`#if defined(HAVE_MUELU_EPETRA) and defined(HAVE_TRILINOSCOUPLINGS_MUELU`?
The second check may be redundant/unnecessary, but just thought I'd check, changes approved either way :)

**Comment by ndellingwood** [comment]
Merged, thanks @lucbv !
