### PR TITLE
MueLu: add missing guards for kokkos refactor

### LINKED ISSUE #8503: MueLu: Build error when Epetra and Tpetra enabled
## Bug Report
@trilinos/muelu
@jhux2 

### Description

Due linking against an older code, I need to build with both `Epetra` and `Tpetra` enabled. Here's my configure script:

<details><summary>Configure script</summary>

```bash
#!/bin/sh

CMAKE_COMMAND=/imcs/public/compsim/opt/cmake-3.12.3-Linux-x86_64/bin/cmake

TRILINOS_HOME=../src-trilinos
EXTRA_ARGS=$@

MPI_DIR=/usr/lib/openmpi
MPI_BIN_DIR=/usr/bin
TPLDIR="/imcs/public/compsim/lib/Q4_2019/TPL"

$CMAKE_COMMAND \
    -GNinja -D Trilinos_ENABLE_Fortran:BOOL=OFF \
    -D CMAKE_BUILD_TYPE:STRING="RELEASE" \
    -D CMAKE_CXX_COMPILER:FILEPATH="$MPI_BIN_DIR/mpic++" \
    -D CMAKE_C_COMPILER:FILEPATH="$MPI_BIN_DIR/mpicc" \
    -D CMAKE_Fortran_COMPILER:FILEPATH="$MPI_BIN_DIR/mpif90" \
    -D CMAKE_CXX_FLAGS:STRING="-fdiagnostics-color=always -w" \
    -D CMAKE_INSTALL_PREFIX:STRING=`pwd` \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D CMAKE_COLOR_MAKEFILE:BOOL=ON \
    -D BUILD_SHARED_LIBS:BOOL=OFF \
    \   
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
    -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_TESTS:BOOL=OFF \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
    \   
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_Anasazi:BOOL=ON \
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
      -D Epetra_HIDE_DEPRECATED_CODE:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
      -D EpetraExt_BUILD_GRAPH_REORDERINGS:BOOL=ON \
      -D EpetraExt_ENABLE_HDF5:BOOL=OFF \
    -D Trilinos_ENABLE_Intrepid:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack:BOOL=ON \
    -D Trilinos_ENABLE_Isorropia:BOOL=ON \
    -D Trilinos_ENABLE_Kokkos:BOOL=ON \
      -D Kokkos_ENABLE_CUDA:BOOL=OFF \
      -D Kokkos_ENABLE_DEPRECATED_CODE:BOOL=OFF \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
      -D MueLu_ENABLE_DEPRECATED_CODE:BOOL=OFF \
      -D MueLu_ENABLE_Kokkos_Refactor:BOOL=OFF \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D Trilinos_ENABLE_Sacado:BOOL=ON \
    -D Trilinos_ENABLE_SEACASExodus:BOOL=ON \
    -D Trilinos_ENABLE_SEACASNemesis:BOOL=OFF \
    -D Trilinos_ENABLE_Shards:BOOL=ON \
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
      -D Teuchos_GLOBALLY_REDUCE_UNITTEST_RESULTS:BOOL=ON \
      -D Teuchos_HIDE_DEPRECATED_CODE:BOOL=ON \
    -D Trilinos_ENABLE_Teko:BOOL=OFF \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
      -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
      -D Tpetra_INST_INT_INT:BOOL=ON \
    -D Trilinos_ENABLE_Xpetra:BOOL=ON \
      -D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
      -D Xpetra_ENABLE_Epetra:BOOL=ON \
      -D Xpetra_ENABLE_EpetraExt:BOOL=ON \
      -D Xpetra_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan2:BOOL=OFF \
    \
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D TPL_ENABLE_ParMETIS:BOOL=ON \
      -D ParMETIS_INCLUDE_DIRS:PATH="$TPLDIR/include" \
      -D ParMETIS_LIBRARY_DIRS:PATH="$TPLDIR/lib" \
    -D TPL_ENABLE_Pthread:BOOL=ON \
    -D TPL_ENABLE_UMFPACK:BOOL=ON \
      -D UMFPACK_INCLUDE_DIRS:FILEPATH="$TPLDIR/include" \
      -D UMFPACK_LIBRARY_DIRS:FILEPATH="$TPLDIR/lib" \
    -D TPL_ENABLE_Netcdf:BOOL=ON \
    -D TPL_ENABLE_MATLAB:BOOL=OFF \
    -D TPL_ENABLE_SuperLU:BOOL=OFF \
    -D TPL_ENABLE_SuperLUDist:BOOL=ON \
      -D SuperLUDist_INCLUDE_DIRS:PATH="$TPLDIR/include" \
      -D SuperLUDist_LIBRARY_DIRS:PATH="$TPLDIR/lib" \
      -D SuperLUDist_LIBRARY_NAMES:STRING="superlu_dist_2.5" \
    $EXTRA_ARGS \
    ${TRILINOS_HOME}
```
</details>

I obtain this build error:
```
[1703/1826] Building CXX object packages/muelu/src/CMakeFi.../ExplicitInstantiation/MueLu_NotayAggregationFactory.cpp.o
FAILED: /usr/bin/mpic++   -I. -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/BrickAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/Containers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/CoupledAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/HybridAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/MatrixTransformation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/PairwiseAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/StructuredAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/StructuredAggregation/coupled -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/StructuredAggregation/uncoupled -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/UncoupledAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Graph/UserAggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Headers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Interface -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Interface/FacadeClasses -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Misc -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/MueCentral -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Rebalancing -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Smoothers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/BaseClass -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/BlackBox -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Smoothers/BlockedSmoothers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/BlockedTransfers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/Energy-Minimization -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/Energy-Minimization/Solvers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/GeneralGeometric -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/Generic -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/Geometric-Interpolation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/Petrov-Galerkin-SA -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/SemiCoarsen -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/Smoothed-Aggregation -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Transfers/User -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Utils -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Utils/ForwardDeclaration -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/../adapters/xpetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/../adapters/epetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/../adapters/tpetra -Ipackages/muelu/src -Ipackages/belos/xpetra/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/belos/xpetra/src -Ipackages/belos/tpetra/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/belos/tpetra/src -Ipackages/belos/epetra/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/belos/epetra/src -Ipackages/belos/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/belos/src -Ipackages/aztecoo/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/aztecoo/src -Ipackages/epetra/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetra/src -Ipackages/teuchos/kokkoscomm/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/kokkoscomm/src -Ipackages/teuchos/kokkoscompat/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/kokkoscompat/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/parameterlist/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/parser/src -Ipackages/teuchos/core/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/core/src -Ipackages/kokkos/core/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos/core/src -Ipackages/kokkos -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/comm/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/remainder/src -Ipackages/teuchos/remainder/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/teuchos/numerics/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/sup/Matrix -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/sup/StridedMap -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/sup/Utils -Ipackages/xpetra/sup -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/CrsGraph -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/CrsMatrix -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/BlockedCrsMatrix -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/DistObject -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Export -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Headers -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Import -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Map -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/BlockedMap -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/MultiVector -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/BlockedMultiVector -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/BlockedVector -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Operator -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Platform -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/RowGraph -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/RowMatrix -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Utils -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Utils/ForwardDeclaration -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/xpetra/src/Vector -Ipackages/xpetra/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/core/ext -Ipackages/tpetra/core/ext -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/core/inout -Ipackages/tpetra/core/inout -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/core/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/core/src/kokkos_refactor -Ipackages/tpetra/core/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/tsqr/src -Ipackages/tpetra/tsqr/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/classic/LinAlg -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/classic/NodeAPI -Ipackages/tpetra/classic/NodeAPI -Ipackages/tpetra/classic/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/tpetra/classic/src -Ipackages/kokkos-kernels/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/impl -Ipackages/kokkos-kernels/src/impl -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/impl/tpls -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/blas -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/blas/impl -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/sparse -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/sparse/impl -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/graph -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/graph/impl -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/batched -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos-kernels/src/common -Ipackages/kokkos/algorithms/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos/algorithms/src -Ipackages/kokkos/containers/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/kokkos/containers/src -Ipackages/epetraext/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src/transform -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src/inout -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src/coloring -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src/model_evaluator -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src/block -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/epetraext/src/restrict -Ipackages/triutils/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/triutils/src -I/imcs/public/compsim/lib/Q4_2019/TPL/include -Ipackages/ml/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Comm -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Coarsen -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/FEGrid -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Main -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Smoother -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Krylov -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Operator -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/Utils -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/RefMaxwell -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/MatrixFree -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/MLAPI -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ml/src/LevelWrap -Ipackages/ifpack/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/ifpack/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/AMD/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/UFconfig -Ipackages/amesos/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/amesos/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/BTF/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CAMD/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/CCOLAMD/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/COLAMD/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/KLU/Include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-xpetra -Ipackages/galeri/src-xpetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-xpetra/../src-epetra -Ipackages/galeri/src-xpetra/../src-epetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-xpetra/../src/Utils -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-xpetra/../src/Headers -Ipackages/galeri/src-epetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-epetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-epetra/Maps -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-epetra/CRSMatrices -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/galeri/src-epetra/FiniteElements -Ipackages/isorropia/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/isorropia/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/isorropia/src/epetra -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/isorropia/src/epetra/zoltanLib -Ipackages/zoltan/src -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/include -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/all -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/coloring -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/graph -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/ha -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/hier -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/hsfc -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/lb -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/matrix -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/order -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/par -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/params -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/tpls -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/phg -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/rcb -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/reftree -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/simple -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/timer -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/Utilities/Communication -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/Utilities/DDirectory -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/Utilities/Timer -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/Utilities/shared -I/ssd/codes/mayrmt_trilinos/src-trilinos/packages/zoltan/src/zz -pedantic -Wall -Wno-long-long -Wwrite-strings -Wshadow -Woverloaded-virtual -fdiagnostics-color=always -w   -Wno-unused-local-typedefs -O3 -DNDEBUG   -std=c++11 -MD -MT packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_NotayAggregationFactory.cpp.o -MF packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_NotayAggregationFactory.cpp.o.d -o packages/muelu/src/CMakeFiles/muelu.dir/Utils/ExplicitInstantiation/MueLu_NotayAggregationFactory.cpp.o -c packages/muelu/src/Utils/ExplicitInstantiation/MueLu_NotayAggregationFactory.cpp
In file included from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_NotayAggregationFactory.cpp:60:0:
/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:25: error: ‘NotayAggregationFactory’ is not a class template
   TPETRA_INSTANTIATE_SLGN_NO_ORDINAL_SCALAR(MUELU_ETI_GROUP)
                         ^
/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:25: error: ‘NotayAggregationFactory’ in namespace ‘MueLu’ does not name a type
```
A similar error occurs for 
```
In file included from packages/muelu/src/Utils/ExplicitInstantiation/MueLu_RegionRFactory.cpp:60:0:
/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:25: error: ‘RegionRFactory’ is not a class template
   TPETRA_INSTANTIATE_SLGN_NO_ORDINAL_SCALAR(MUELU_ETI_GROUP)
                         ^
/ssd/codes/mayrmt_trilinos/src-trilinos/packages/muelu/src/Utils/MueLu_ETI_4arg.hpp:32:25: error: ‘RegionRFactory’ in namespace ‘MueLu’ does not name a type
```

Both (`NotarAggregatioFactor` and `RegionRFactory`) have been recently touched in PR #8106.

### Steps to Reproduce
1. SHA1: d5aa0ca99bd945f0c47a88387f0872f549a441c1
1. Configure script: see above
1. Configure log: [log_configure.txt](https://github.com/trilinos/Trilinos/files/5722580/log_configure.txt)
1. Build log: [log_build.txt](https://github.com/trilinos/Trilinos/files/5722581/log_build.txt)

### PR DESCRIPTION
**Pull request by mayrmt**
@trilinos/muelu 

## Motivation

PR #8106 has guarded the NotayAggregationFactory and the RegionRFactory with `#ifdef HAVE_MUELU_KOKKOS_REFACTOR` and seems to have this tested for a `Tpetra`-only build.

This PR addresses the case of Epetra and Tpetra being enabled simultaneously and `MueLu_ENABLE_Kokkos_Refactor:BOOL=OFF` by propagating these defines completely through MueLu's ETI system to fix the build error reported in #8503.

## Related Issues and PRs

* Closes #8503
* Follows #8106

## Stakeholder Feedback

Some (non-Sandia) legacy application codes require Epetra and Tpetra to be enabled simultaneously.

## Additional Information

I'm not an expert in MueLu's ETI system, so I appreciate every suggestion to this PR. This works for me on my workstation with the configure script given in #8503.

### CODE REVIEW

File: packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp [hunk 1]
```diff
@@ -46,8 +46,8 @@
 #ifndef MUELU_REGIONRFACTORY_FWD_HPP
 #define MUELU_REGIONRFACTORY_FWD_HPP
 
-
-
+#include "MueLu_ConfigDefs.hpp"
+#if defined(HAVE_MUELU_KOKKOS_REFACTOR)
```
Comment (lucbv) [inline packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp:50]: Do we need the Kokkos refactor branch for that or just Tpetra to be enabled?

File: packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake [hunk 2]
```diff
@@ -73,7 +73,7 @@ APPEND_SET(MUELU_SC_LO_GO_NO_ETI_CLASSES MueLu::RebalanceBlockAcFactory )
 APPEND_SET(MUELU_SC_LO_GO_NO_ETI_CLASSES MueLu::RebalanceBlockInterpolationFactory )
 APPEND_SET(MUELU_SC_LO_GO_NO_ETI_CLASSES MueLu::RebalanceBlockRestrictionFactory )
 APPEND_SET(MUELU_SC_LO_GO_NO_ETI_CLASSES MueLu::RebalanceTransferFactory )
-APPEND_SET(MUELU_SC_LO_GO_NO_ETI_CLASSES MueLu::RegionRFactory )
+APPEND_SET(MUELU_SC_LO_GO_NO_ETI_CLASSES MueLu::RegionRFactory-.?if.defined[HAVE_MUELU_KOKKOS_REFACTOR] )
```
Comment (lucbv) [inline packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake:76]: Do we need the Kokkos refactor branch for that or just Tpetra to be enabled?

File: packages/muelu/src/Utils/ClassList/SC-LO-GO-NO.classList [hunk 3]
```diff
@@ -76,7 +76,7 @@ RebalanceBlockAcFactory
 RebalanceBlockInterpolationFactory
 RebalanceBlockRestrictionFactory
 RebalanceTransferFactory
-RegionRFactory
+RegionRFactory - #if defined(HAVE_MUELU_KOKKOS_REFACTOR)
```
Comment (lucbv) [inline packages/muelu/src/Utils/ClassList/SC-LO-GO-NO.classList:79]: Do we need the Kokkos refactor branch for that or just Tpetra to be enabled?

**Review by lucbv — COMMENTED** [review]
Overall this looks fine, I am just wondering if we actually use Kokkos directly in the region multigrid code path? I thought we only use Tpetra but I can easily remember wrong...

File: packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake (hunk 2 above)
Comment (mayrmt) [reply packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake:76]: `HAVE_MUELU_TPETRA` seems to suffice.

File: packages/muelu/src/Utils/ClassList/SC-LO-GO-NO.classList (hunk 3 above)
Comment (mayrmt) [reply packages/muelu/src/Utils/ClassList/SC-LO-GO-NO.classList]: `HAVE_MUELU_TPETRA` seems to suffice.

File: packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp (hunk 1 above)
Comment (mayrmt) [reply packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp:50]: `HAVE_MUELU_TPETRA` seems to suffice.

**Comment by mayrmt** [comment]
@trilinos/muelu This PR is awaiting review. Thanks!

**Comment by mayrmt** [comment]
@lucbv  would you mind having another look? Thanks.

File: packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp [hunk 4]
```diff
@@ -192,9 +192,7 @@ namespace MueLu {
     ordering = O_NATURAL;
     if (orderingStr == "random" ) ordering = O_RANDOM;
     else if(orderingStr == "natural") {}
-#if defined(HAVE_MUELU_KOKKOS_REFACTOR)
```
Comment (lucbv) [inline packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp:195]: The Cuthill-McKee algorithm is only implemented in Kokkos this option should not be exposed to non-kokkos path

File: packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp [hunk 5]
```diff
@@ -208,14 +206,12 @@ namespace MueLu {
       orderingVector[i] = i;
     if (ordering == O_RANDOM)
       MueLu::NotayUtils::RandomReorder(orderingVector);
-#if defined(HAVE_MUELU_KOKKOS_REFACTOR)
```
Comment (lucbv) [inline packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp:211]: As explained above and as is clear from `MueLu::Utilities_kokkos` the Cuthill-McKee reordering needs to be guarded with appropriate `HAVE_MUELU_KOKKOS_REFACTOR`

File: packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp [hunk 6]
```diff
@@ -298,15 +294,13 @@ namespace MueLu {
         localOrderingVector[i] = i;
       if (ordering == O_RANDOM)
         MueLu::NotayUtils::RandomReorder(localOrderingVector);
-#if defined(HAVE_MUELU_KOKKOS_REFACTOR)
```
Comment (lucbv) [inline packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp:301]: Same as above

File: packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_decl.hpp [hunk 7]
```diff
@@ -48,7 +48,7 @@
 #define MUELU_REGIONRFACTORY_DECL_HPP
 
 #include "MueLu_ConfigDefs.hpp"
-#ifdef HAVE_MUELU_KOKKOS_REFACTOR
+#ifdef HAVE_MUELU_TPETRA
```
Comment (lucbv) [inline packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_decl.hpp:51]: Actually `MueLu_RegionRFactory` really needs the Kokkos guard as it is using the `KokkosSparse::CrsMatrix` to construct the restriction operator.

File: packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_decl.hpp [hunk 8]
```diff
@@ -110,5 +110,5 @@ namespace MueLu {
 } // namespace MueLu
 
 #define MUELU_REGIONRFACTORY_SHORT
-#endif //ifdef HAVE_MUELU_KOKKOS_REFACTOR
+#endif //ifdef HAVE_MUELU_TPETRA
```
Comment (lucbv) [inline packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_decl.hpp:113]: Same as above

File: packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp [hunk 9]
```diff
@@ -46,7 +46,7 @@
 #ifndef MUELU_REGIONRFACTORY_DEF_HPP
 #define MUELU_REGIONRFACTORY_DEF_HPP
 
-#ifdef HAVE_MUELU_KOKKOS_REFACTOR
+#ifdef HAVE_MUELU_TPETRA
```
Comment (lucbv) [inline packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp:49]: Same as above

File: packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp [hunk 10]
```diff
@@ -1140,5 +1140,5 @@ namespace MueLu {
 } //namespace MueLu
 
 #define MUELU_REGIONRFACTORY_SHORT
-#endif //ifdef HAVE_MUELU_KOKKOS_REFACTOR
+#endif //ifdef HAVE_MUELU_TPETRA
```
Comment (lucbv) [inline packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp:1143]: Same as above

File: packages/muelu/src/Utils/ClassList/SC-LO-GO-NO.classList [hunk 11]
```diff
@@ -76,7 +76,7 @@ RebalanceBlockAcFactory
 RebalanceBlockInterpolationFactory
 RebalanceBlockRestrictionFactory
 RebalanceTransferFactory
-RegionRFactory
+RegionRFactory - #if defined(HAVE_MUELU_TPETRA)
```
Comment (lucbv) [inline packages/muelu/src/Utils/ClassList/SC-LO-GO-NO.classList:79]: Actually needs Kokkos

File: packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake (hunk 2 above)
Comment (lucbv) [reply packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake:76]: After double checking we need Kokkos for sure here. Sorry for the misleading question above.

File: packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp (hunk 1 above)
Comment (lucbv) [reply packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp:50]: Again definitely need Kokkos for this.

**Review by lucbv — CHANGES_REQUESTED** [review]
Sorry to give you more work but we definitely need the Kokkos guard for `RegionRFactory`, it uses the Kokkos local matrix to build the restriction operator...

File: packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp (hunk 4 above)
Comment (mayrmt) [reply packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp:195]: @lucbv The entire file is encapsulated in `#ifdef HAVE_MUELU_KOKKOS_REFACTOR` (cf. line 49), so this statement can safely be removed, as it just repeats the same `#ifdef`. Same argument holds for all other changes in this file.

File: packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp (hunk 1 above)
Comment (mayrmt) [reply packages/muelu/src/Utils/ForwardDeclaration/MueLu_RegionRFactory_fwd.hpp:50]: Will change this back.

File: packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake (hunk 2 above)
Comment (mayrmt) [reply packages/muelu/src/Utils/ExplicitInstantiation/ETI_SC_LO_GO_NO_classes.cmake:76]: Done.

**Comment by mayrmt** [comment]
@lucbv Thanks for your review. I made the respective changes:
- `RegionRFactory` relies on Kokkos refactor.
- `NotayAggregationFactory` still is guarded by `HAVE_MUELU_KOKKOS_REFACTOR`, just the inner/nested `#ifdef HAVE_MUELU_KOKKOS_REFACTOR` statements are removed, as they are redundant to the outer one that encapsulates the entire file.
Please let me know, if this is ok.

**Review by lucbv — APPROVED** [review]
OK this looks fine to me
