### PR TITLE
Intrepid2: fix C++20 deprecated code and potenttial type mismatch issue

### LINKED ISSUE #12786: Intrepid2: Use of std::is_pod is deprecated in C++ 20
@trilinos/intrepid2 

## Enhancement
I tried a build with C++ 20 and got a bunch of warnings:
```
packages/intrepid2/src/Shared/Intrepid2_Utils.hpp: In function 'constexpr int Intrepid2::getVectorSizeForHierarchicalParallelism()':
packages/intrepid2/src/Shared/Intrepid2_Utils.hpp:827:17: warning: 'template<class _Tp> struct std::is_pod' is deprecated: use is_standard_layout && is_trivial instead [-Wdeprecated-declarations]
```

### PR DESCRIPTION
**Pull request by mperego**
This PR fixes potential issue with Intrepid2 inclusion tests when the points are not of double type. See discussion in PR #13385 (thanks @MalachiTimothyPhillips for pointing this out).

This PR should also fix code that is deprecated in c++20 standard (Issue #12786).

@trilinos/intrepid2 

## Related Issues

* Closes #12786

### CODE REVIEW

**Comment by mperego** [comment]
@etphipp I have modified Sacado because in C++20 standard arithmetic between different enumeration types is deprecated.

**Review by etphipp — COMMENTED** [review]
Sacado changes are fine.

**Comment by MalachiTimothyPhillips** [comment]
@mperego LGTM -- thank you!

File: packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp [hunk 1]
```diff
@@ -826,61 +826,61 @@ refCenterDataStatic_ = {
...
   }
   
-  template<typename PointViewType>
+  template<typename PointViewType, typename ScalarType>
   KOKKOS_INLINE_FUNCTION
   bool
   PointInclusion<shards::Pyramid<>::key>::
-  check(const PointViewType &point, const double threshold) {
+  check(const PointViewType &point, const ScalarType threshold) {
     const double minus_one = -1.0 - threshold, plus_one = 1.0 + threshold, minus_zero = -threshold;
```
Comment (CamelliaDPG) [inline packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp:884]: Should `minus_one`, etc. have type `auto` or `ScalarType` instead?  (If the only other case we're supporting is `float`, it will be fine as it is, maybe modulo some compiler warnings for the comparison below, but if we intend it to be more general, I expect `auto` or `ScalarType` is the right thing, here and throughout.)

Comment (mperego) [reply packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp]: Good point! I pushed a fix using ScalarType instead of double.

**Review by CamelliaDPG — APPROVED** [review]
Looks great!

File: packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp [hunk 2]
```diff
@@ -826,76 +826,76 @@ refCenterDataStatic_ = {
...
 
-  template<typename PointViewType>
+  template<typename PointViewType, typename ScalarType>
   KOKKOS_INLINE_FUNCTION
   bool
   PointInclusion<shards::Triangle<>::key>::
-  check(const PointViewType &point, const double threshold) {
-    const double distance = max( max( -point(0), -point(1) ), point(0) + point(1) - 1.0 );
+  check(const PointViewType &point, const ScalarType threshold) {
+    const ScalarType distance = max( max( -point(0), -point(1) ), point(0) + point(1) - 1.0 );
```
Comment (MalachiTimothyPhillips) [inline packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp:843]: I guess `point(0) + point(1) - 1.0` is interpreted as a `double`?

```
In file included from /sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellData.hpp:415,
                 from /sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellTools.hpp:56,
                 from /projects/sierra/nightly/checkouts/trilinos_develop/default/stk/stk_unit_tests/stk_search_util/UnitTestIsInElement.cpp:42:
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellDataDef.hpp: In instantiation of 'static bool Intrepid2::PointInclusion<537070595>::check(const PointViewType&, ScalarType) [with PointViewType = Kokkos::DynRankView<float, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0> >; ScalarType = float]':
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellToolsDefInclusion.hpp:112:64:   required from 'void Intrepid2::checkPointInclusionFunctor<cellTopologyKey, OutputViewType, InputViewType>::operator()(Intrepid2::ordinal_type) const [with unsigned int cellTopologyKey = 537070595; OutputViewType = Kokkos::DynRankView<int, Kokkos::Serial>; InputViewType = const Kokkos::DynRankView<float, Kokkos::Serial>; Intrepid2::ordinal_type = int]'
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Serial/Kokkos_Serial_Parallel_Range.hpp:37:16:   required from 'std::enable_if_t<std::is_void<_Dummy>::value> Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits ...>, Kokkos::Serial>::exec() const [with TagType = void; FunctorType = Intrepid2::checkPointInclusionFunctor<537070595, Kokkos::DynRankView<int, Kokkos::Serial>, const Kokkos::DynRankView<float, Kokkos::Serial> >; Traits = {Kokkos::Serial}; std::enable_if_t<std::is_void<_Dummy>::value> = void]'
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Serial/Kokkos_Serial_Parallel_Range.hpp:56:51:   required from 'void Kokkos::Impl::ParallelFor<FunctorType, Kokkos::RangePolicy<Traits ...>, Kokkos::Serial>::execute() const [with FunctorType = Intrepid2::checkPointInclusionFunctor<537070595, Kokkos::DynRankView<int, Kokkos::Serial>, const Kokkos::DynRankView<float, Kokkos::Serial> >; Traits = {Kokkos::Serial}]'
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Kokkos_Parallel.hpp:144:18:   required from 'void Kokkos::parallel_for(const string&, const ExecPolicy&, const FunctorType&) [with ExecPolicy = Kokkos::RangePolicy<Kokkos::Serial>; FunctorType = Intrepid2::checkPointInclusionFunctor<537070595, Kokkos::DynRankView<int, Kokkos::Serial>, const Kokkos::DynRankView<float, Kokkos::Serial> >; Enable = void; std::string = std::__cxx11::basic_string<char>]'
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Kokkos_Parallel.hpp:153:23:   required from 'void Kokkos::parallel_for(const ExecPolicy&, const FunctorType&, std::enable_if_t<Kokkos::is_execution_policy<T>::value>*) [with ExecPolicy = Kokkos::RangePolicy<Kokkos::Serial>; FunctorType = Intrepid2::checkPointInclusionFunctor<537070595, Kokkos::DynRankView<int, Kokkos::Serial>, const Kokkos::DynRankView<float, Kokkos::Serial> >; std::enable_if_t<Kokkos::is_execution_policy<T>::value> = void]'
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellToolsDefInclusion.hpp:138:27:   required from 'static void Intrepid2::CellTools<DeviceType>::checkPointwiseInclusion(OutputViewType, InputViewType, typename Intrepid2::ScalarTraits<typename InputViewType::value_type>::scalar_type) [with unsigned int cellTopologyKey = 537070595; OutputViewType = Kokkos::DynRankView<int, Kokkos::Serial>; InputViewType = const Kokkos::DynRankView<float, Kokkos::Serial>; DeviceType = Kokkos::Serial; typename Intrepid2::ScalarTraits<typename InputViewType::value_type>::scalar_type = float]'
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellToolsDefInclusion.hpp:180:89:   required from 'static void Intrepid2::CellTools<DeviceType>::checkPointwiseInclusion(InCellViewType, InputViewType, shards::CellTopology, typename Intrepid2::ScalarTraits<typename PointViewType::value_type>::scalar_type) [with InCellViewType = Kokkos::DynRankView<int, Kokkos::Serial>; PointViewType = Kokkos::DynRankView<float, Kokkos::Serial>; DeviceType = Kokkos::Serial; typename Intrepid2::ScalarTraits<typename PointViewType::value_type>::scalar_type = float]'
/projects/sierra/nightly/checkouts/trilinos_develop/default/stk/stk_unit_tests/stk_search_util/UnitTestIsInElement.cpp:160:63:   required from here
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellDataDef.hpp:843:36: error: no matching function for call to 'max(float, double)'
  843 |     const ScalarType distance = max( max( -point(0), -point(1) ), point(0) + point(1) - 1.0 );
      |                                 ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellTools.hpp:27,
                 from /projects/sierra/nightly/checkouts/trilinos_develop/default/stk/stk_unit_tests/stk_search_util/UnitTestIsInElement.cpp:42:
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_Utils.hpp:264:12: note: candidate: 'template<class T> T Intrepid2::max(const T&, const T&)'
  264 |   static T max(const T &a, const T &b) {
      |            ^~~
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_Utils.hpp:264:12: note:   template argument deduction/substitution failed:
In file included from /sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellData.hpp:415,
                 from /sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellTools.hpp:56,
                 from /projects/sierra/nightly/checkouts/trilinos_develop/default/stk/stk_unit_tests/stk_search_util/UnitTestIsInElement.cpp:42:
/sierra/build/linux_rh7/nightly/gcc_trilinos_devel_master/objs/tpls/spack/spack/__spack_path_placeholder__/__spack_path_placehol/linux-rhel8-x86_64/gcc-10.3.0/trilinos-develop-u36n2g3j26wrryfvry4cm7haqtxu75ki/include/Intrepid2_CellDataDef.hpp:843:36: note:   deduced conflicting types for parameter 'const T' ('float' and 'double')
  843 |     const ScalarType distance = max( max( -point(0), -point(1) ), point(0) + point(1) - 1.0 );
      |                                 ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Comment (MalachiTimothyPhillips) [reply packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp:843]: I guess https://github.com/trilinos/Trilinos/pull/13416 should work :)
