### PR TITLE
Ifpack2: Use assumeMpiIsGPUAware in BTDS

### LINKED ISSUE #12132: Ifpack2:  Block TriDiag test fails with device aware MPI off but HIP enabled
## Bug Report
I've built and run the ifpack2 block tridiag test, but if I disable device aware MPI (at the MPI and Tpetra level), the app will crash.

@vbrunini @kliegeois 

```
# GPU-aware (using 2 procs) - works
MPICH_GPU_SUPPORT_ENABLED=1 \
 TPETRA_ASSUME_GPU_AWARE_MPI=1 \
 flux \
 run \
 -c8 \
 -g1 \
 -n \
 2 \
 ./packages/ifpack2/example/Ifpack2_BlockTriDiagonalSolver.exe \
 --withoutOverlapCommAndComp \
 --matrixType=Laplace3D \
 --blockSize=11 \
 --nx=64 \
 --ny=32 \
 --nz=64 \
 --sublinesPerLine=1 \
 --tol=0 \
 --numIters=10000 \
 --withStackedTimer


#disable GPU-aware MPI - it fails
MPICH_GPU_SUPPORT_ENABLED=0 \
 TPETRA_ASSUME_GPU_AWARE_MPI=0 \
 flux \
 run \
 -c8 \
 -g1 \
 -n \
 2 \
 ./packages/ifpack2/example/Ifpack2_BlockTriDiagonalSolver.exe \
 --withoutOverlapCommAndComp \
 --matrixType=Laplace3D \
 --blockSize=11 \
 --nx=64 \
 --ny=32 \
 --nz=64 \
 --sublinesPerLine=1 \
 --tol=0 \
 --numIters=10000 \
 --withStackedTimer
```

<details>
<summary> configure </summary>

```
cmake \
 "-GNinja" \
 "-DCMAKE_BUILD_TYPE:STRING=Release" \
 "-DTrilinos_ENABLE_TrilinosBuildStats=OFF" \
 "-DTrilinos_ENABLE_BUILD_STATS=OFF" \
 "-DTrilinosBuildStats_ENABLE_TESTS=OFF" \
 "-DBUILD_SHARED_LIBS:BOOL=OFF" \
 "-DTrilinos_ENABLE_Teuchos=ON" \
 "-DPanzerMiniEM_ENABLE_EXAMPLES=ON" \
 "-DPanzerMiniEM_ENABLE_TESTS=ON" \
 "-DTrilinos_ENABLE_Percept=OFF" \
 "-DTrilinos_ENABLE_ALL_PACKAGES=ON" \
 "-DKokkos_ARCH_ZEN3:BOOL=ON" \
 "-DKokkos_ENABLE_SERIAL:BOOL=ON" \
 "-DTpetra_INST_SERIAL:BOOL=ON" \
 "-DKokkos_ENABLE_OPENMP:BOOL=OFF" \
 "-DTpetra_INST_OPENMP:BOOL=OFF" \
 "-DTrilinos_ENABLE_OpenMP:BOOL=OFF" \
 "-DKokkos_ENABLE_HIP:BOOL=ON" \
 "-DTpetra_INST_HIP:BOOL=ON" \
 "-DKOKKOSKERNELS_ENABLE_TPL_BLAS:BOOL=ON" \
 "-DKOKKOSKERNELS_ENABLE_TPL_LAPACK:BOOL=ON" \
 "-DKOKKOSKERNELS_ENABLE_TPL_ROCBLAS:BOOL=ON" \
 "-DKOKKOSKERNELS_ENABLE_TPL_ROCSPARSE:BOOL=ON" \
 "-DKokkos_ARCH_VEGA90A:BOOL=ON" \
 "-DCMAKE_EXE_LINKER_FLAGS=-x none --hip-link  " \
 "-DCMAKE_SHARED_LINKER_FLAGS=-x none --hip-link  " \
 "-DFC_FN_UNDERSCORE=UNDER" \
 "-DCMAKE_CXX_COMPILER=/opt/cray/pe/craype/2.7.21/bin/CC" \
 "-DCMAKE_C_COMPILER=/opt/cray/pe/craype/2.7.21/bin/cc" \
 "-DCMAKE_Fortran_COMPILER=/opt/cray/pe/craype/2.7.21/bin/ftn" \
 "-DCMAKE_CXX_FLAGS=-x hip -mllvm -amdgpu-early-inline-all=false -mllvm -amdgpu-function-calls=false -g " \
 "-DCMAKE_Fortran_FLAGS=" \
 "-DCMAKE_C_FLAGS=" \
 "-DTrilinos_EXTRA_LINK_FLAGS=" \
....
```

The standard TPLs enabled ... the compiler definitions
are benign. Build how you like.  but make sure to use my CXX flags to mimic SPARC
</details>

### Steps to Reproduce
1. Latest develop
1. Configure script:  above (truncated, ping me if you can't reproduce)
1. launch commands above

### PR DESCRIPTION
**Pull request by kliegeois**
@trilinos/ifpack2 
@jjellio 

This PR fixes #12132 by using `assumeMpiIsGPUAware()` to deduce if GPU Aware MPI can be used or if the data needs to be copied to host before/after sending/receiving respectively.

The branch has been tested on V100 using:
```
TPETRA_ASSUME_GPU_AWARE_MPI=0 \
mpirun -np 4 Ifpack2_BlockTriDiagonalSolver.exe  \
--withoutOverlapCommAndComp  --matrixType=Laplace3D  \
--blockSize=11  --nx=64  --ny=32  --nz=64  \
--sublinesPerLine=1  --tol=0  --numIters=2  --withStackedTimer
```
and
```
TPETRA_ASSUME_GPU_AWARE_MPI=1 \
mpirun -np 4 Ifpack2_BlockTriDiagonalSolver.exe  \
--withoutOverlapCommAndComp  --matrixType=Laplace3D  \
--blockSize=11  --nx=64  --ny=32  --nz=64  \
--sublinesPerLine=1  --tol=0  --numIters=2  --withStackedTimer
```

Before this fix, the run with `TPETRA_ASSUME_GPU_AWARE_MPI=0` failed.

### CODE REVIEW

File: packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp [hunk 1]
```diff
@@ -549,12 +549,24 @@ namespace Ifpack2 {
...
+          if(Tpetra::Details::Behavior::assumeMpiIsGPUAware()) {
+            irecv(comm,
+                  reinterpret_cast<char*>(buffer.recv.data() + offset_host.recv[i]*mv_blocksize),
+                  (offset_host.recv[i+1] - offset_host.recv[i])*mv_blocksize*sizeof(impl_scalar_type),
+                  pids.recv[i],
+                  42,
+                  &reqs.recv[i]);
+          }
+          else {
+            const auto buffer_recv_host = Kokkos::create_mirror_view(buffer.recv);
```
Comment (brian-kelley) [inline packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:561]:
```suggestion
            const auto buffer_recv_host = Kokkos::create_mirror_view(
              Kokkos::view_alloc(Kokkos::WithoutInitializing), buffer.recv);
```

File: packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp [hunk 2]
```diff
@@ -576,12 +588,24 @@ namespace Ifpack2 {
...
+          if(Tpetra::Details::Behavior::assumeMpiIsGPUAware()) {
+            isend(comm,
+                  reinterpret_cast<const char*>(buffer.send.data() + offset_host.send[i]*mv_blocksize),
+                  (offset_host.send[i+1] - offset_host.send[i])*mv_blocksize*sizeof(impl_scalar_type),
+                  pids.send[i],
+                  42,
+                  &reqs.send[i]);
+          }
+          else {
+            const auto buffer_send_host = Kokkos::create_mirror_view(buffer.send);
```
Comment (brian-kelley) [inline packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:600]: Same as above

File: packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp [hunk 3]
```diff
@@ -696,25 +720,49 @@ namespace Ifpack2 {
...
+          if(Tpetra::Details::Behavior::assumeMpiIsGPUAware()) {
+            irecv(comm,
+                  reinterpret_cast<char*>(buffer.recv.data() + offset_host.recv[i]*mv_blocksize),
+                  (offset_host.recv[i+1] - offset_host.recv[i])*mv_blocksize*sizeof(impl_scalar_type),
+                  pids.recv[i],
+                  42,
+                  &reqs.recv[i]);
+          }
+          else {
+            const auto buffer_recv_host = Kokkos::create_mirror_view(buffer.recv);
```
Comment (brian-kelley) [inline packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:732]: Same

File: packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp [hunk 4]
```diff
@@ -696,25 +720,49 @@ namespace Ifpack2 {
...
+          if(Tpetra::Details::Behavior::assumeMpiIsGPUAware()) {
+            isend(comm,
+                  reinterpret_cast<const char*>(buffer.send.data() + offset_host.send[i]*mv_blocksize),
+                  (offset_host.send[i+1] - offset_host.send[i])*mv_blocksize*sizeof(impl_scalar_type),
+                  pids.send[i],
+                  42,
+                  &reqs.send[i]);
+          }
+          else {
+            const auto buffer_send_host = Kokkos::create_mirror_view(buffer.send);
```
Comment (brian-kelley) [inline packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:757]: same

**Review by brian-kelley — COMMENTED** [review]
I know this is not the high-performance codepath, but it could be tightened up by avoiding redundant initializations

**Review by brian-kelley — APPROVED** [review]
Thanks!
