### PR TITLE
Tpetra: new constructor for FECrsGraph accepting owned+shared domain map

### LINKED ISSUE #7455: Tpetra: FECrsGraph wrong default domain map?
## Question
@trilinos/Tpetra

I am not sure if this is a bug, so I'm posting it under 'questions', but I have the feeling it is either wrong or counterintuitive.

One can create a FECrsGraph passing only ownedRowMap and ownedPlusSharedRowMap (the domain and column maps being defaulted to null). In this case, FECrsGraph sets the domain map to the ownedRowMap, even if the graph is in FE_ACTIVE_OWNED_PLUS_SHARED state.

This cause the (overlapped) graph to potentially (and, in practice, I do observe it) have a domain map which is not locally fitted to the column map. This is usually not the case in a crs graph, and took me a while to figure out it's not the case for the FECrsGraph (when in owned+shared mode).

So the question is probably two faced:

1) In a CrsGraph, is it usually desired (and safe to assume) that colMap_->isLocallyFitted(domainMap_) returns true? My assumption was "yes", cause it helps in import/export operations. At the very least, isn't it desirable (and even safe to assume) in the case where the column map is internally generated by Tpetra (rather than passed in by the user)?
2) Assuming the answer to 1 is "yes" (or 'no', but 'yes' to the 'at least' clause), is there a reason not to keep this behavior for the overlapped FECrsGraph?

Note: assuming 1=yes, 2=no, we could restore this symmetry by simply setting domaniMap_ to ownedPlusSharedRowMap in case the input domain map is null.

### PR DESCRIPTION
**Pull request by bartgol**
@trilinos/tpetra

## Motivation

This PR adds a set of constructors to FECrsGraph, which accept a domain map for the owned+shared graph. Before this PR, the owned+shared graph and the owned graph were both created with the same _domain_ map, which, by default, was taken to be the owned row map. This caused the owned+shared dof map in the owned+shared graph to not be locally fitted to the graph's column map, which can cause issues in FE codes assembly that partition the mesh by elements. In such codes, during FE assembly kernels, one may only have the owned+shared dofs map available (coming from a discretization or connectivity object), and not the col map of the matrix. When converting the GIDs of the dofs in the element to local ordinals (in order to assembly the local matrix) one _needs_ the local ids in the owned+shared map to be _the same_ as they will be in the col map of the matrix. Having the owned+shared graph storing the owned+shared dofs as its domain map ensures that owned+shared map is locally fitted to the col map, so that the local ids obtained when converting the dofs GIDs to local ordinal are the same (when using the owned+shared map or the col map of the matrix).
 

## Related Issues

* Closes #7455 

## Testing

The new constructors cannot produce the same graph as the existing ones (otherwise there'd be no point in this PR). However, the resulting graphs should be "locally (and globally) equivalent", meaning that they should store the same row/range/domain map and the same set of GID in each row as a graph built with the existing constructors. The only difference is that colum (global) indices may appear in different order, as well as have different local ids. So I added two sets of tests:

- A test that checks that FECrsGraph built with the new constructor is "locally" equivalent to a good old CrsGraph that is globalAssemble-d.
- A test for MatrixMatrix multiplication, that checks that A*B is "locally equivalent" regardless of whether A,B are FECrsMatrix (with graph built with the new constructors) or CrsMatrix (globalAssemble-d).

### CODE REVIEW

**Comment by ikalash** [comment]
@csiefer2 @trilinos/tpetra

**Comment by mperego** [comment]
@bartgol looks good. Just a warning treated as error:
```
/scratch/trilinos/jenkins/tr-test-0/workspace/trilinos-folder/Trilinos_pullrequest_gcc_7.2.0/Trilinos/packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp:175:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     for (size_t j=0; j<numEntries; ++j) {
                      ~^~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by bartgol** [comment]
Thanks for the explanation @mperego ! I didn't know (remember?) that the AT treated warnings as errors. Should be fixed now.

Quick question: the AT triggers also tests in downstream packages that use Tpetra, right? I just want to make sure that my mods didn't mess up things for customers that already used FECrs stuff (it shouldn't have changed anything regarding the behavior of existing ctors, but you know how it goes...).

**Comment by mperego** [comment]
> Quick question: the AT triggers also tests in downstream packages that use Tpetra, right?

Yes.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp [hunk 1]
```diff
@@ -141,10 +141,45 @@ namespace Tpetra {
                const Teuchos::RCP<const map_type> & ownedPlusSharedRowMap,
                const size_t maxNumEntriesPerRow,
                const Teuchos::RCP<const import_type> & ownedPlusSharedToOwnedimporter = Teuchos::null,
-               const Teuchos::RCP<const map_type> & domainMap = Teuchos::null,
-               const Teuchos::RCP<const map_type> & rangeMap = Teuchos::null,
+               const Teuchos::RCP<const map_type> & ownedDomainMap = Teuchos::null,
+               const Teuchos::RCP<const map_type> & ownedRangeMap = Teuchos::null,
                const Teuchos::RCP<Teuchos::ParameterList>& params = Teuchos::null);
 
+    /// \brief Constructorfor globally-indexed assembly specifying a single upper bound for the
```
Comment (kddevin) [inline packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp:148]: Please add documentation saying why one would use this constructor over the existing constructors.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp [hunk 2]
```diff
@@ -172,8 +207,43 @@ namespace Tpetra {
                 const Teuchos::RCP<const map_type> & ownedPlusSharedRowMap,
                 const Kokkos::DualView<const size_t*, execution_space>& numEntPerRow,
                 const Teuchos::RCP<const import_type> & ownedPlusSharedToOwnedimporter = Teuchos::null,
-                const Teuchos::RCP<const map_type> & domainMap = Teuchos::null,
-                const Teuchos::RCP<const map_type> & rangeMap = Teuchos::null,
+                const Teuchos::RCP<const map_type> & ownedDomainMap = Teuchos::null,
+                const Teuchos::RCP<const map_type> & ownedRangeMap = Teuchos::null,
+                const Teuchos::RCP<Teuchos::ParameterList>& params = Teuchos::null);
+
+    /// \brief Constructor for globally-indexed assembly specifying a (possibly different) upper
```
Comment (kddevin) [inline packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp:214]: Please add documentation saying why one would use this constructor over the existing constructors.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp [hunk 3]
```diff
@@ -207,10 +277,79 @@ namespace Tpetra {
                const Teuchos::RCP<const map_type> & ownedPlusSharedColMap,
                const size_t maxNumEntriesPerRow,
                const Teuchos::RCP<const import_type> & ownedPlusSharedToOwnedimporter = Teuchos::null,
-               const Teuchos::RCP<const map_type> & domainMap = Teuchos::null,
-               const Teuchos::RCP<const map_type> & rangeMap = Teuchos::null,
+               const Teuchos::RCP<const map_type> & ownedDomainMap = Teuchos::null,
+               const Teuchos::RCP<const map_type> & ownedRangeMap = Teuchos::null,
                const Teuchos::RCP<Teuchos::ParameterList>& params = Teuchos::null);
 
+    /// \brief Constructor for locally-indexed assembly specifying a single upper bound for the
```
Comment (kddevin) [inline packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp:284]: Please add documentation saying why one would use this constructor over the existing constructors.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp [hunk 4]
```diff
@@ -42,11 +42,13 @@
 #ifndef TPETRA_FECRSGRAPH_DEF_HPP
 #define TPETRA_FECRSGRAPH_DEF_HPP
 
-#include <type_traits>
-#include "Tpetra_CrsGraph.hpp"
+#include "Tpetra_FECrsGraph.hpp"
 #include "Tpetra_Details_Behavior.hpp"
 #include "Tpetra_Details_getEntryOnHost.hpp"
+#include "Tpetra_Details_makeColMap.hpp"
```
Comment (kddevin) [inline packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp:48]: Is this include needed?  It appears the code that calls it is commented out below.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp [hunk 5]
```diff
@@ -308,6 +379,42 @@ void FECrsGraph<LocalOrdinal, GlobalOrdinal, Node>::beginFill() {
 
 }
 
+// template<class LocalOrdinal, class GlobalOrdinal, class Node>
```
Comment (kddevin) [inline packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp:382]: This function is added to the file, but completely commented out.  Is it needed?

File: packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp [hunk 6]
```diff
@@ -128,11 +128,11 @@ namespace Tpetra {
     /// \param ownedPlusSharedToOwnedimporter [in] Optional importer between the ownedMap and ownedPlusSharedMap
     ///   This will be calculated by FECrsGraph if it is not provided
     ///
-    /// \param domainMap [in] Optional domainMap for the owned graph.  If this is not provided, then ownedMap
-    ///   will be used for the domainMap in the call to endFill()
+    /// \param ownedDomainMap [in] Optional domain map for both owned and owned+shared graphs. If this is not provided,
```
[the remark this answers is not in the document]
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp:131]: Ah, good catch. I was updating the comments to stress the fact that that map was for the owned graph only, but I must have messed up with copy/paste from another ctor. I will go over the comments again, fix this, and make sure there are no other mistakes.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp [hunk 7]
```diff
@@ -42,11 +42,13 @@
 #ifndef TPETRA_FECRSGRAPH_DEF_HPP
 #define TPETRA_FECRSGRAPH_DEF_HPP
 
-#include <type_traits>
-#include "Tpetra_CrsGraph.hpp"
+#include "Tpetra_FECrsGraph.hpp"
```
[the remark this answers is not in the document]
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp:45]: It is not. I just thought the above one was not the one intended. I'm ok removing the include of FECrsGraph, but then, what's the point of including CrsGraph either? Should I remove that too?

File: packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp [hunk 8]
```diff
@@ -166,24 +243,21 @@ void FECrsGraph<LocalOrdinal, GlobalOrdinal, Node>::setup(const Teuchos::RCP<con
...
      
    }
-
-   // For FECrsGraph, we do all the aliasing AFTER import.  All we need here is a constructor
-   if(ownedPlusSharedColMap.is_null())
-     inactiveCrsGraph_ = Teuchos::rcp(new crs_graph_type(ownedRowMap,0,StaticProfile,params));
-   else
-     inactiveCrsGraph_ = Teuchos::rcp(new crs_graph_type(ownedRowMap,ownedPlusSharedColMap,0,StaticProfile,params));
+ } else {
+   // We don't need the importer. Setting it to null helps detecting we are in a non-FE case later
```
[the remark this answers is not in the document]
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp:247]: I'll improve the comment. Non-FE is indeed a poor word choice. I was trying to refer to the case where there's no need for an inactive graph, since owned and owned+shared row maps coincide.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp (hunk 1 above)
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp:148]: Will do.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp (hunk 4 above)
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp:48]: Ah, good catch. I went through a few impl cycles, where at some point I tried to build a col map, but then backed off. This was supposed to be removed.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp (hunk 5 above)
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp:382]: Ouch, same as above. I'll fix all this sloppy nonsense.

File: packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (bartgol) [reply packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp:131]: Ah, sorry, this is the already existing ctor. Indeed, the old ctor was using this map for both owned and owned+shared. I will change the input var name so that it does not imply owned or owned+shared.

**Comment by bartgol** [comment]
@kddevin I think I addressed your concerns, but please, let me know if something is still off/unclear/misleading.

I ended up adding a relatively long paragraph in the class documentation at the top, explainind the difference (and reason of being) between the consturctor that accept a owned+shared domain map and those that don't. It might have come out a bit long, but I didn't know how to clearly explain the issue in two lines, and also I figured "better a bit verbose than a bit cryptic".

**Comment by bartgol** [comment]
> Can you also add a comment with the github issue number motivating the additions?

Do you mean inside the code?

**Comment by bartgol** [comment]
> > Can you also add a comment with the github issue number motivating the additions?
> 
> Do you mean inside the code?

I think that's what you meant, so I went ahead and put a reference in the comment in the FECrsGraph header.

**Comment by mperego** [comment]
@bartgol I guess the autotester won't run until @kddevin will approve your changes. 
@jwillenbring can you please add @bartgol to the trilinos team? He is  a Sandian. He is  not actively working on trilinos but he is a developer of Albany and he occasionally has patches for bugs or new features (like this one) for trilinos.

**Comment by jwillenbring** [comment]
> @jwillenbring can you please add @bartgol to the trilinos team? 

I sent an invite.

**Comment by bartgol** [comment]
> > @jwillenbring can you please add @bartgol to the trilinos team?
> 
> I sent an invite.

Thanks!

**Comment by mperego** [comment]
@kddevin , I think @bartgol addressed all of your comments. We'll merge the branch by COB today if there are no objections.
