### PR TITLE
Stokhos(fixes #11398): Set alg defaults depending on cusparse version

### LINKED ISSUE #11398: Stokhos: CUSPARSE_MM_ALG_DEFAULT is not defined in CUDA 12
## Bug Report

@etphipp

### Description

The fixes introduced in
* https://github.com/trilinos/Trilinos/pull/11165

in `packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp` will not compile on `CUDA 12` because of
* https://github.com/kokkos/kokkos-kernels/issues/1630

We also wonder why `KokkosSparse::Impl::spmv_mv_cusparse` was not used in `packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp`. Do you have some more information about that?

Thanks!

### PR DESCRIPTION
**Pull request by maartenarnst**
@etphipp 

## Motivation

A while ago, we had seen in issue #11398 that the cuSparse's alg defaults for SPMV/SPMM depend on the cuSparse version. 

This PR is a fix that follows what was done in e.g. `KokkosSparse_spmv_tpl_spec_decl.hpp` to address the same issue. 

Fixes #11398.

### CODE REVIEW

File: packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp [hunk 1]
```diff
@@ -61,7 +61,21 @@
...
+    cusparseSpMMAlg_t alg_spmm = CUSPARSE_SPMM_ALG_DEFAULT;
+#elif CUSPARSE_VERSION >= 11000
+  #define USE_NEW_SPMV 1
+  #define NEW_SPMV_ALG_DEFAULTS \
+    cusparseSpMVAlg_t alg_spmv = CUSPARSE_MV_ALG_DEFAULT;
+  #define NEW_SPMM_ALG_DEFAULTS \
+    cusparseSpMMAlg_t alg_spmm = CUSPARSE_MM_ALG_DEFAULT;
+#else
+  #define USE_NEW_SPMV 0
+#endif
```
Comment (etphipp) [inline packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp:78]: Generally I am fine with this.  However, the logic here appears to be copied from KokkosKernels and my experience has been this logic isn't completely correct.  There is an important customer who builds with version 11.2.0 of the CUDA toolkit where the cuSPARSE version reports to be 11.3.1:
```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 3
#define CUSPARSE_VER_PATCH 1
#define CUSPARSE_VER_BUILD 68
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```
which would choose the first branch, but uses `CUSPARSE_MV_ALG_DEFAULT` as in the second branch:
```
typedef enum {
    CUSPARSE_MV_ALG_DEFAULT = 0,
    CUSPARSE_COOMV_ALG      = 1,
    CUSPARSE_CSRMV_ALG1     = 2,
    CUSPARSE_CSRMV_ALG2     = 3
} cusparseSpMVAlg_t;
```
I've run into this issue several times with KokkosKernels, but have been too lazy to file a bug with them.  It would be annoying to have to fix this in two places though.

Comment (maartenarnst) [reply packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp:78]: Hi @etphipp. OK. I've done a search in Trilinos:

- In `Kokkos-kernels/perf_test/sparse/KokkosSparse_spmv_struct_tuning.cpp`, the conditional is `#if CUSPARSE_VERSION >= 11201`.
- In `Kokkos-kernels/sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp`, the conditional is `#if CUSPARSE_VERSION >= 11301`.
- In `Kokkos-kernels/sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp`, the conditional is `#if CUSPARSE_VERSION < 11010`.
- In `mule/test/scaling/MatvecKernelDriver.cpp`, the conditional is `#if CUSPARSE_VERSION >= 11201`.

So you think we should find out exactly which version changed it in which case MM/MV and then do two simultaneous PRs, one in Trilinos (for Stokhos and Muelu) and one in Kokkos-kernels?

Comment (etphipp) [reply packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp:78]: Ideally, yes, I guess.

**Comment by maartenarnst** [comment]
Hi @etphipp,

OK, let's see what the different cuda/cusparse versions say :)

- docker image nvidia/cuda:11.0.3-devel-ubuntu20.04:

```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 1
#define CUSPARSE_VER_PATCH 1
#define CUSPARSE_VER_BUILD 245
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```

```
typedef enum {
    CUSPARSE_MV_ALG_DEFAULT = 0,
    CUSPARSE_COOMV_ALG      = 1,
    CUSPARSE_CSRMV_ALG1     = 2,
    CUSPARSE_CSRMV_ALG2     = 3
} cusparseSpMVAlg_t;
```

```
typedef enum {
    CUSPARSE_MM_ALG_DEFAULT
                        CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_ALG_DEFAULT) = 0,
    CUSPARSE_COOMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG1) = 1,
    CUSPARSE_COOMM_ALG2 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG2) = 2,
    CUSPARSE_COOMM_ALG3 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG3) = 3,
    CUSPARSE_CSRMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_CSR_ALG1) = 4,
    CUSPARSE_SPMM_ALG_DEFAULT = 0,
    CUSPARSE_SPMM_COO_ALG1    = 1,
    CUSPARSE_SPMM_COO_ALG2    = 2,
    CUSPARSE_SPMM_COO_ALG3    = 3,
    CUSPARSE_SPMM_COO_ALG4    = 5,
    CUSPARSE_SPMM_CSR_ALG1    = 4,
    CUSPARSE_SPMM_CSR_ALG2    = 6,
} cusparseSpMMAlg_t;
```

- docker image nvidia/cuda:11.1.1-devel-ubuntu20.04:

```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 3
#define CUSPARSE_VER_PATCH 0
#define CUSPARSE_VER_BUILD 10
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```

```
typedef enum {
    CUSPARSE_MV_ALG_DEFAULT = 0,
    CUSPARSE_COOMV_ALG      = 1,
    CUSPARSE_CSRMV_ALG1     = 2,
    CUSPARSE_CSRMV_ALG2     = 3
} cusparseSpMVAlg_t;
```

```
typedef enum {
    CUSPARSE_MM_ALG_DEFAULT
                        CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_ALG_DEFAULT) = 0,
    CUSPARSE_COOMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG1) = 1,
    CUSPARSE_COOMM_ALG2 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG2) = 2,
    CUSPARSE_COOMM_ALG3 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG3) = 3,
    CUSPARSE_CSRMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_CSR_ALG1) = 4,
    CUSPARSE_SPMM_ALG_DEFAULT = 0,
    CUSPARSE_SPMM_COO_ALG1    = 1,
    CUSPARSE_SPMM_COO_ALG2    = 2,
    CUSPARSE_SPMM_COO_ALG3    = 3,
    CUSPARSE_SPMM_COO_ALG4    = 5,
    CUSPARSE_SPMM_CSR_ALG1    = 4,
    CUSPARSE_SPMM_CSR_ALG2    = 6,
    CUSPARSE_SPMMA_PREPROCESS = 7,
    CUSPARSE_SPMMA_ALG1       = 8,
    CUSPARSE_SPMMA_ALG2       = 9,
    CUSPARSE_SPMMA_ALG3       = 10,
    CUSPARSE_SPMMA_ALG4       = 11
} cusparseSpMMAlg_t;
```

- docker image nvidia/cuda:11.2.2-devel-ubuntu20.04:

```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 4
#define CUSPARSE_VER_PATCH 1
#define CUSPARSE_VER_BUILD 1152
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```

```
typedef enum {
    CUSPARSE_MV_ALG_DEFAULT
                        CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_ALG_DEFAULT) = 0,
    CUSPARSE_COOMV_ALG  CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_COO_ALG1)    = 1,
    CUSPARSE_CSRMV_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_CSR_ALG1)    = 2,
    CUSPARSE_CSRMV_ALG2 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_CSR_ALG2)    = 3,
    CUSPARSE_SPMV_ALG_DEFAULT = 0,
    CUSPARSE_SPMV_CSR_ALG1    = 2,
    CUSPARSE_SPMV_CSR_ALG2    = 3,
    CUSPARSE_SPMV_COO_ALG1    = 1,
    CUSPARSE_SPMV_COO_ALG2    = 4
} cusparseSpMVAlg_t;
```

```
typedef enum {
    CUSPARSE_MM_ALG_DEFAULT
                        CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_ALG_DEFAULT) = 0,
    CUSPARSE_COOMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG1) = 1,
    CUSPARSE_COOMM_ALG2 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG2) = 2,
    CUSPARSE_COOMM_ALG3 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG3) = 3,
    CUSPARSE_CSRMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_CSR_ALG1) = 4,
    CUSPARSE_SPMM_ALG_DEFAULT      = 0,
    CUSPARSE_SPMM_COO_ALG1         = 1,
    CUSPARSE_SPMM_COO_ALG2         = 2,
    CUSPARSE_SPMM_COO_ALG3         = 3,
    CUSPARSE_SPMM_COO_ALG4         = 5,
    CUSPARSE_SPMM_CSR_ALG1         = 4,
    CUSPARSE_SPMM_CSR_ALG2         = 6,
    CUSPARSE_SPMM_CSR_ALG3         = 12,
    CUSPARSE_SPMM_BLOCKED_ELL_ALG1 = 13
} cusparseSpMMAlg_t;
```

- docker image nvidia/cuda:11.3.1-devel-ubuntu20.04:

```
#define CUSPARSE_VER_MAJOR 11
#define CUSPARSE_VER_MINOR 6
#define CUSPARSE_VER_PATCH 0
#define CUSPARSE_VER_BUILD 109
#define CUSPARSE_VERSION (CUSPARSE_VER_MAJOR * 1000 + \
                          CUSPARSE_VER_MINOR *  100 + \
                          CUSPARSE_VER_PATCH)
```

```
typedef enum {
    CUSPARSE_MV_ALG_DEFAULT
                        /*CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_ALG_DEFAULT)*/ = 0,
    CUSPARSE_COOMV_ALG  CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_COO_ALG1)    = 1,
    CUSPARSE_CSRMV_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_CSR_ALG1)    = 2,
    CUSPARSE_CSRMV_ALG2 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMV_CSR_ALG2)    = 3,
    CUSPARSE_SPMV_ALG_DEFAULT = 0,
    CUSPARSE_SPMV_CSR_ALG1    = 2,
    CUSPARSE_SPMV_CSR_ALG2    = 3,
    CUSPARSE_SPMV_COO_ALG1    = 1,
    CUSPARSE_SPMV_COO_ALG2    = 4
} cusparseSpMVAlg_t;
```

```
typedef enum {
    CUSPARSE_MM_ALG_DEFAULT
                        CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_ALG_DEFAULT) = 0,
    CUSPARSE_COOMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG1) = 1,
    CUSPARSE_COOMM_ALG2 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG2) = 2,
    CUSPARSE_COOMM_ALG3 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_COO_ALG3) = 3,
    CUSPARSE_CSRMM_ALG1 CUSPARSE_DEPRECATED_ENUM(CUSPARSE_SPMM_CSR_ALG1) = 4,
    CUSPARSE_SPMM_ALG_DEFAULT      = 0,
    CUSPARSE_SPMM_COO_ALG1         = 1,
    CUSPARSE_SPMM_COO_ALG2         = 2,
    CUSPARSE_SPMM_COO_ALG3         = 3,
    CUSPARSE_SPMM_COO_ALG4         = 5,
    CUSPARSE_SPMM_CSR_ALG1         = 4,
    CUSPARSE_SPMM_CSR_ALG2         = 6,
    CUSPARSE_SPMM_CSR_ALG3         = 12,
    CUSPARSE_SPMM_BLOCKED_ELL_ALG1 = 13
} cusparseSpMMAlg_t;
```

So these results seem to confirm that you're right that setting the threshold at 11201 is not good. 

Based on these results, I'd propose to set the threshold at 11401. In this case, we'd be in a version for which both enum values are defined, and the older one is deprecated.

What do you think?

**Comment by etphipp** [comment]
Sounds good to me.  Can you create an issue with @trilinos/kokkos-kernels?  Note, they snapshot KokkosKernels into Trilinos, so I'm not sure how they would want to handle this.

**Comment by maartenarnst** [comment]
Hi @etphipp. Thanks, and done. It's issue kokkos/kokkos-kernels#1967.

**Comment by sebrowne** [comment]
I recommend rebasing this branch given the 'develop' history change.

**Review by etphipp — APPROVED** [review]

**Comment by etphipp** [comment]
Looks like this was waiting for pre-test inspection, which I have no done.  Sorry about that!

**Comment by cwpearson** [comment]
I think I figured out exactly which CUDA releases and corresponding cuSPARSE versions changed this behavior:

https://github.com/kokkos/kokkos-kernels/issues/1967

For SpMV it looks like the threshold should be `11400` and for SpMM, at `11000`

**Comment by etphipp** [comment]
@cwpearson Should we merge this, or are you making other changes to KokkosKernels that should be propagated here as well?

**Comment by etphipp** [comment]
Even after this merge I am still seeing errors like
```
/ascldap/users/etphipp/project/Trilinos/Trilinos/packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp(98): error: identifier "CUSPARSE_SPMV_ALG_DEFAULT" is undefined

/ascldap/users/etphipp/project/Trilinos/Trilinos/packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp(112): error: identifier "CUSPARSE_SPMV_CSR_ALG2" is undefined
```

**Comment by etphipp** [comment]
You're right, sorry!
