### PR TITLE
Belos smoother: Fix #6932

### LINKED ISSUE #6932: MueLu:  Build error in MueLu_BelosSmoother
## Bug Report
@trilinos/muelu

### Description
We're seeing a build error in all of our integration builds (gcc, intel, and nvidia).

`Trilinos/packages/muelu/src/Smoothers/MueLu_BelosSmoother_decl.hpp:72:10: fatal error: BelosXpetraAdapter.hpp: No such file or directory`

### Steps to Reproduce
Configure script:
```
cmake \
  -G "Ninja" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -D Trilinos_EXTRA_LINK_FLAGS:STRING="" \
  -D CMAKE_BUILD_TYPE:STRING=release \
 -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
 -D TPL_ENABLE_CUDA:BOOL=OFF \
 -DCMAKE_C_FLAGS_RELEASE_OVERRIDE:STRING="-DNDEBUG" \
 -DCMAKE_CXX_FLAGS_RELEASE_OVERRIDE:STRING="-DNDEBUG" \
 -DCMAKE_Fortran_FLAGS_RELEASE_OVERRIDE:STRING="-DNDEBUG" \
 -DCMAKE_C_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -w " \
 -DCMAKE_CXX_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -w " \
 -DCMAKE_Fortran_FLAGS:STRING="-O2 -finline-functions -ftemplate-depth-128 -w  " \
 -DHAVE_GCC_ABI_DEMANGLE:BOOL=ON \
 -DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
 -DTrilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
 -DTrilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
 -DTrilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON \
 -DTrilinos_ENABLE_FLOAT:BOOL=ON \
 -DTrilinos_ENABLE_LINEAR_SOLVER_FACTORY_REGISTRATION:BOOL=ON \
 -DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
 -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
 -DTrilinos_CXX11_FLAGS=-std=c++11 \
 -DTPL_ENABLE_Pthread:BOOL=OFF \
 -DTPL_ENABLE_yaml-cpp:BOOL=OFF \
 -DTPL_ENABLE_MPI:BOOL=ON \
 -DTPL_ENABLE_ParMETIS:BOOL=ON \
 -DTPL_ENABLE_UMFPACK:BOOL=ON \
 -DTPL_ENABLE_y12m:BOOL=ON \
 -DTPL_ENABLE_Boost:BOOL=ON \
 -DTrilinos_ENABLE_Amesos:BOOL=ON \
 -DTrilinos_ENABLE_Amesos2:BOOL=ON \
 -DTrilinos_ENABLE_Anasazi:BOOL=ON \
 -DTrilinos_ENABLE_AztecOO:BOOL=ON \
 -DTrilinos_ENABLE_Belos:BOOL=ON \
 -DTrilinos_ENABLE_Epetra:BOOL=ON \
 -DTrilinos_ENABLE_EpetraExt:BOOL=ON \
 -DTrilinos_ENABLE_FEI:BOOL=ON \
 -DTrilinos_ENABLE_Ifpack:BOOL=ON \
 -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
 -DTrilinos_ENABLE_Intrepid:BOOL=ON \
 -DTrilinos_ENABLE_Kokkos:BOOL=ON \
 -DTrilinos_ENABLE_KokkosCore:BOOL=ON \
 -DTrilinos_ENABLE_KokkosContainers:BOOL=ON \
 -DTrilinos_ENABLE_MiniTensor:BOOL=ON \
 -DTrilinos_ENABLE_ML:BOOL=ON \
 -DTrilinos_ENABLE_MueLu:BOOL=ON \
 -DTrilinos_ENABLE_Pamgen:BOOL=ON \
 -DTrilinos_ENABLE_ROL:BOOL=ON \
 -DTrilinos_ENABLE_RTOp:BOOL=ON \
 -DTrilinos_ENABLE_Sacado:BOOL=ON \
 -DTrilinos_ENABLE_Shards:BOOL=ON \
 -DTrilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON \
 -DTrilinos_ENABLE_ShyLU_NodeHTS:BOOL=ON \
 -DTrilinos_ENABLE_Stokhos:BOOL=OFF \
 -DTrilinos_ENABLE_Teuchos:BOOL=ON \
 -DTrilinos_ENABLE_ThreadPool:BOOL=ON \
 -DTrilinos_ENABLE_Thyra:BOOL=ON \
 -DTrilinos_ENABLE_ThyraEpetraExtAdapters:BOOL=ON \
 -DTrilinos_ENABLE_Tpetra:BOOL=ON \
 -DTrilinos_ENABLE_Triutils:BOOL=ON \
 -DTrilinos_ENABLE_Xpetra:BOOL=ON \
 -DTrilinos_ENABLE_Zoltan:BOOL=ON \
 -DTrilinos_ENABLE_Zoltan2:BOOL=ON \
 -DTrilinos_ENABLE_Galeri:BOOL=OFF \
 -DTrilinos_ENABLE_Gtest:BOOL=OFF \
 -DTrilinos_ENABLE_Isorropia:BOOL=OFF \
 -DTrilinos_ENABLE_MOOCHO:BOOL=OFF \
 -DTrilinos_ENABLE_Rythmos:BOOL=OFF \
 -DTrilinos_ENABLE_SEACAS:BOOL=OFF \
 -DTrilinos_ENABLE_STK:BOOL=OFF \
 -DTrilinos_ENABLE_Stratimikos:BOOL=OFF \
 -DTrilinos_ENABLE_TrilinosCouplings:BOOL=OFF \
 -DAmesos_ENABLE_SuperLU:BOOL=ON \
 -DAmesos2_ENABLE_ShyLU_NodeTacho:BOOL=OFF \
 -DAmesos2_ENABLE_SuperLU:BOOL=ON \
 -DAztecOO_ENABLE_AZLU:BOOL=ON \
 -DBelos_ENABLE_Xpetra:BOOL=OFF \
 -DIfpack2_ENABLE_ThyraTpetraAdapters=OFF \
 -DKOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF \
 -DKOKKOS_ENABLE_PROFILING:BOOL=ON \
 -DML_ENABLE_METIS:BOOL=OFF \
 -DML_ENABLE_ParMETIS:BOOL=OFF \
 -DPamgen_ENABLE_Boost:BOOL=OFF \
 -DPamgen_ENABLE_Extras:BOOL=OFF \
 -DROL_ENABLE_EXAMPLES:BOOL=OFF \
 -DROL_ENABLE_TESTS:BOOL=OFF \
 -DSacado_ENABLE_KokkosCore:BOOL=ON \
 -DTacho_ENABLE_INT_INT:BOOL=ON \
 -DTpetra_INST_INT_LONG:BOOL=ON \
 -DTpetra_INST_INT_LONG_LONG:BOOL=OFF \
 -DTpetra_INST_SERIAL:BOOL=ON \
 -DZoltan_ENABLE_METIS:BOOL=OFF \
 -DZoltan_ENABLE_Scotch:BOOL=OFF \
 -DZoltan2_ENABLE_Experimental:BOOL=ON \
 -DZoltan2_ENABLE_Scotch:BOOL=OFF
```

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/muelu 

## Motivation
Second attempt at fixing #6932.

### CODE REVIEW

File: packages/muelu/src/Smoothers/MueLu_BelosSmoother_decl.hpp [hunk 1]
```diff
@@ -48,28 +48,28 @@
...
 #include "MueLu_ConfigDefs.hpp"
-#include "MueLu_BelosSmoother_fwd.hpp"
 
 #if defined(HAVE_MUELU_BELOS)
 
+#include "MueLu_BelosSmoother_fwd.hpp"
+
+#ifdef HAVE_XPETRA_TPETRA
+#include "BelosTpetraAdapter.hpp"
+#include <Tpetra_Operator.hpp>
```
Comment (mhoemmen) [inline packages/muelu/src/Smoothers/MueLu_BelosSmoother_decl.hpp]: Use double quotes here too.  In general, only system headers get angle brackets.
