### PR TITLE
KokkosKernels: Fix #6418 

### LINKED ISSUE #6418: TpetraCore_MultiVector_UnitTests_MPI_4 and TpetraCore_gemm_m_eq_<X>_MPI_1 tests in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug failing starting 2019-12-07
CC: @trilinos/tpetra, @kddevin (Trilinos Data Services Product Lead), @bartlettroscoe, @fryeguy52, @seheracer

<Checklist>
<???: Add label "client: ATDM">
<???: Add label "ATDM Sev: Blocker" (by default but could be other "ATDM Sev: XXX")>
<???: Add label "type: bug"?>
<???: Add label for affected packages (e.g. "pkg: MueLu", "pkg: Tpetra", "pkg: Kokkos", etc.)>
<???: Add label "PA: ???Project Area???" (e.g. "PA: Linear Solvers", "PA: Data Services")>
<???: Add milestone "Initial cleanup of new ATDM ..." or "Keep promoted ATDM ...">
<???: Once GitHub Issue is created, add entries for tests to TrilinosATDMStatus/*.csv files>

## Next Action Status

<status-and-or-first-action>

## Description

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-10&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=TpetraCore_MultiVector_UnitTests_MPI_4&field3field2=testname&field3compare2=65&field3value2=TpetraCore_gemm_m_eq_) the tests:

* `TpetraCore_gemm_m_eq_1_MPI_1`
* `TpetraCore_gemm_m_eq_2_MPI_1`
* `TpetraCore_gemm_m_eq_5_MPI_1`
* `TpetraCore_gemm_m_eq_13_MPI_1`
* `TpetraCore_MultiVector_UnitTests_MPI_4`

are failing in build:

* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug`

starting 2019-12-07.

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=testname&compare3=65&value3=TpetraCore_gemm_m_eq_&field4=testoutput&compare4=97&value4=FAILED.*%20Blas_std_complex0double0_Gemm_UnitTest), the tests `TpetraCore_gemm_m_eq_<X>_MPI_1` are all failing the unit test `Blas_std_complex0double0_Gemm_UnitTest` showing error output like:

```
     ...
     trans_A: C
     trans_B: N
     A_norm: 1.15513
     B_norm: 0.355242
     C_norm: 1.13028
     bound: 1.77636e-15
     false = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/Blas/gemm.cpp:306
     Comparing KokkosBlas::gemm against Teuchos::BLAS::GEMM: Max error 0.699682 > error bound 1.77636e-15
     false = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/Blas/gemm.cpp:333
     Comparing KokkosBlas::Default::gemm against Teuchos::BLAS::GEMM: Max error 0.699682 > error bound 1.77636e-15
     At least one test FAILED; abandoning the others.
   At least one test FAILED; abandoning the others.
   At least one test FAILED; abandoning the others.
 [FAILED]  (2.47 sec) Blas_std_complex0double0_Gemm_UnitTest
```

As shown in [this query](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&begin=2019-11-11&end=2019-12-10&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=testname&compare3=61&value3=TpetraCore_MultiVector_UnitTests_MPI_4&field4=testoutput&compare4=97&value4=FAILED.*MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest), the test `TpetraCore_MultiVector_UnitTests_MPI_4` is failing the unit test `MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest` showing oputput like:

```
88. MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest ... 
 Test: MultiVector, Multiply
  Comparing tmpView(0,9) == check3 ... passed
  Comparing tmpView(0,4) == check2 ... passed
  Comparing tmpView(0,4) == check2 ... passed
  Comparing tmpView(0,9) == check3 ... passed
  gblSuccess == 1 = 1 == true : passed
  Comparing tmpView == sdmView ... passed
  gblSuccess == 1 = 1 == true : passed
  Comparing tmpView == sdmView ... passed
  gblSuccess == 1 = 1 == true : passed
  Comparing tmpView == sdmView ... 
  Error, relErr(tmpView[0],sdmView[0]) = relErr((1.3406,0.995454),(2.15303,0)) = 0.596788 <= tol = 2.22045e-14: failed!
  
  Error, relErr(tmpView[1],sdmView[1]) = relErr((-0.767759,0.205214),(-0.0764208,-0.51095)) = 1.25254 <= tol = 2.22045e-14: failed!
  
  Error, relErr(tmpView[2],sdmView[2]) = relErr((-0.767759,0.205214),(-0.0764208,0.51095)) = 0.951195 <= tol = 2.22045e-14: failed!
  
  Error, relErr(tmpView[3],sdmView[3]) = relErr((-0.18601,0.101217),(0.738326,0)) = 1.25942 <= tol = 2.22045e-14: failed!
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:815
  Comparing tmpView == sdmView ... passed
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:828
  Comparing tmpView == check(0,tmpView.size()) ... passed
  Comparing tmpView == check(0,tmpView.size()) ... passed
  Comparing tmpView == check(0,tmpView.size()) ... passed
  Comparing tmpView == check(0,tmpView.size()) ... passed
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:861
  Comparing tmpView == check2 ... passed
  Comparing tmpView == check3 ... passed
  gblSuccess == 1 = 0 == true : FAILED ==> /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:888
 [FAILED]  (0.0303 sec) MultiVector_int_longlong_std_complex0double0_Kokkos_Compat_KokkosCudaWrapperNode_Multiply_UnitTest
 Location: /scratch/jenkins/ascicgpu14/workspace/Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug/SRC_AND_BUILD/Trilinos/packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp:707
```

The new commits that were pulled on the testing day 2019-12-07 as shown [here](https://testing-dev.sandia.gov/cdash/viewNotes.php?buildid=5069857#!#note6).  Looking over that set of commits, the commits most likely to have triggered this failuire are:

```
d3a22b1:  Add beta=0 case and allow number of teams smaller than 32 to resolve NaN and diff issues in some Teko and ShyLu tests.
Author: Seher Acer <sacer@sandia.gov>
Date:   Wed Dec 4 21:10:29 2019 -0700

M	packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp

e5f7c38:  KokkosKernels: Optimized GEMM (over CUBLAS GEMM) for A^TB with tall and skinny matrices on CUDA.
Author: Seher Acer <sacer@sandia.gov>
Date:   Tue Nov 5 19:47:58 2019 -0700

M	packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
```

pulled in from PR #6226 by @seheracer.

## Current Status on CDash

* [`TpetraCore_MultiVector_UnitTests_MPI_4` and `TpetraCore_gemm_m_eq_<X>_MPI_1` tests in build Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug for current testing day](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug&field2=site&compare2=61&value2=sems-rhel7&field3=block&field3count=2&field3field1=testname&field3compare1=61&field3value1=TpetraCore_MultiVector_UnitTests_MPI_4&field3field2=testname&field3compare2=65&field3value2=TpetraCore_gemm_m_eq_)

## Steps to Reproduce

One should be able to reproduce this failure on a CEE LAN `ascicgpu<NUM>` 'sems-rhel7' as described in:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md

More specifically, the commands given for the system CEE LAN `ascicgpu<NUM>` 'sems-rhel7' are provided at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#sems-rhel7-environment

The exact commands to reproduce this issue should be:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/atdm/load-env.sh \
  Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug

$ cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_TpetraCore=ON \
 $TRILINOS_DIR

$ make NP=16

$ ctest -j4
```

### PR DESCRIPTION
**Pull request by seheracer**
@trilinos/kokkos-kernels 

## Motivation

This PR 
1) fixes the issue https://github.com/trilinos/Trilinos/issues/6418, which was caused by DotBasedGEMM in KokkosKernels, by excluding the conjugate transpose case for A from the optimized case and    
2) upgrades the initialization kernels in DotBasedGEMM to use MDRangePolicy.
 

## Related Issues
https://github.com/trilinos/Trilinos/issues/6418
https://github.com/kokkos/kokkos-kernels/pull/510#discussion_r354566671

## Testing

These tests (which were failing in https://github.com/trilinos/Trilinos/issues/6418) are passing now:

    TpetraCore_gemm_m_eq_1_MPI_1
    TpetraCore_gemm_m_eq_2_MPI_1
    TpetraCore_gemm_m_eq_5_MPI_1
    TpetraCore_gemm_m_eq_13_MPI_1
    TpetraCore_MultiVector_UnitTests_MPI_4

### CODE REVIEW

**Comment by mhoemmen** [comment]
I don't think it's too hard to add a test -- we would just need to compare results against the system BLAS' GEMM.  That's what the failing test did (`Teuchos::BLAS` defers to the system BLAS for the four element types that the BLAS supports).

**Comment by seheracer** [comment]
@bartlettroscoe @mhoemmen, I will add the KokkosKernels test. Thanks for the suggestion.

**Comment by bartlettroscoe** [comment]
CC: @trilinos/framework 

@seheracer, looks like your PR build got bit by the known randomly failing test `Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4` as per #3585.  Add the label `AT: RETEST` and cross your fingers :-)

**Comment by bartlettroscoe** [comment]
@seheracer,

Actually, wait until you add the new tests for KokkosKernels that expose this defect and then show our changes fix this and then set the label `AT: RETEST`.

**Comment by seheracer** [comment]
@bartlettroscoe @mhoemmen @ndellingwood,

It turned out I don't need to add a new KK test to expose the failure in https://github.com/trilinos/Trilinos/issues/6418. I just needed to update the existing GEMM test. Previously, the maximum value allowed in randomly-created A, B, C matrices was 10, which didn't have enough room to accumulate the difference to expose the conjugate transpose error. In my last commit (https://github.com/trilinos/Trilinos/pull/6427/commits/885e3a634e56d756997274aeb32d0e1338d6adf9), I changed this to be the max value of the corresponding scalar type, as in failing Tpetra gemm tests in https://github.com/trilinos/Trilinos/issues/6418. This change causes the complex_double gemm tests in KK to fail when the previous version of DotBasedGEMM is used.

File: packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp [hunk 1]
```diff
@@ -105,9 +105,10 @@ namespace Test {
     uint64_t seed = Kokkos::Impl::clock_tic();
     Kokkos::Random_XorShift64_Pool<execution_space> rand_pool(seed);
 
-    Kokkos::fill_random(A,rand_pool,ScalarA(10));
-    Kokkos::fill_random(B,rand_pool,ScalarB(10));
-    Kokkos::fill_random(C,rand_pool,ScalarC(10));
+    // (SA 11 Dec 2019) Max (previously: 10) increased to detect the bug in Trilinos issue #6418 
+    Kokkos::fill_random(A,rand_pool, Kokkos::rand<typename Kokkos::Random_XorShift64_Pool<execution_space>::generator_type,ScalarA>::max());
```
Comment (bartlettroscoe) [inline packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp]: How big is this `rand<>:::max()`?  Is this going to cause problems with overflow?

**Comment by bartlettroscoe** [comment]
@seheracer, do you want to add the label `AT: AUTOMERGE`?

Also, please pull these commits off with `git format-patch` and use `git am` to apply them back to the native kokkos-kernels git repo.  If you are not sure about how two do that, I can supply the commands to do that (to avoid possible conflicts when running `git am`).

File: packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp (hunk 1 above)
Comment (seheracer) [reply packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp]: Yes, the updated test fails if I revert the commit that updates the file:
    kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp

I'm not sure about the value of rand<>::max(), but I want to say it should have caused problems in the Tpetra gemm test if it would (?). On the other hand, the inner dimension of the multiplication in the KokkosKernels test goes up to 517 whereas this value is only 13 in the Tpetra test, so KK test would be more likely to hit such an issue (?).  I'm not sure.
