### PR TITLE
Ifpack2 - remove return type from Ifpack2_BlockTriDiContainer_impl.hpp

### LINKED ISSUE #3304: Ifpack2: Build error in BlockTriDi due to wrong return type for volatile operator+=
Ifpack2's overloaded `operator+=` for volatile ArrayViewType in BlockTriDi needs to return void, not a volatile reference.  This is causing a build error in Sierra.

@trilinos/ifpack2

### PR DESCRIPTION
**Pull request by kyungjoo-kim**
Fix  #3304

## Description

Unnecessary return type (probably typo from when I change the operator as a static function) produces an warning which turns into an error in sierra build.

## How Has This Been Tested?

I confirmed the error is gone in my workstation using gcc pull request script.

### CODE REVIEW

File: packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp [hunk 1]
```diff
@@ -147,22 +147,20 @@ namespace Ifpack2 {
...
                volatile const ArrayValueType<T,N> &b) {
       for (int i=0;i<N;++i) 
         a.v[i] += b.v[i];
-      return a;
     }
     template<typename T, int N>
     static 
     KOKKOS_INLINE_FUNCTION
-    ArrayValueType<T,N>& 
+    void
```
Comment (mhoemmen) [inline packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: You don't need to change this one.  (I suppose it's harmless, unless you want to be able to chain operators.)

Comment (kyungjoo-kim) [reply packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: Ummm..... I just want to keep the code at the same manner. You are right that the operator would not be used for chaining but the warning should be removed in building the code anyway.

Comment (mhoemmen) [reply packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: I'm not too worried about this -- if people ever need to chain `ArrayValueType` `operator+=`, we could always add the return type back in.

Comment (mhoemmen) [reply packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: This is not a Scalar type that we intend to expose for general use, right?

Comment (kyungjoo-kim) [reply packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp]: No, it is not. I just want to do multiple reductions in a single parallel for using a fixed array type to reduce the number of parallel for launching and multiple memory access. If Kokkos supports this kind of types and its reduction operator, it would be nice though.

**Comment by mhoemmen** [comment]
@micahahoward @tcfisher
