### PR TITLE
Zoltan2:  Enable MJ to work with int coordinates

### LINKED ISSUE #1312: Zoltan2 partitioning metrics return scalar_t; should return double
Zoltan2's partitioning metrics class EvaluatePartition returns, among other things, imbalance values.  Imbalance is inherently a float or double.  While scalar_t is often float or double, it could be int.  When scalar_t is int, returning imbalance as an int is inaccurate. 

It appears that currently, all metrics are stored as scalar_t.  We could store them as double instead.
@trilinos/zoltan2

### LINKED ISSUE #4212: Zoltan2:  MJ does not work with integer coordinates
@trilinos/zoltan2   @MicheldeMessieres 

## Expectations
MJ should function when users provide scalar_t = int coordinates (e.g., (i.,j) indices of matrix entries) to be partitioned.

## Current Behavior

MJ requires scalar_t = float or double.  MJ uses the users' scalar_t as the data type for cuts and ratios.  When scalar_t = int, MJ segfaults with division by zero or hangs, due to truncation of differences of coordinates, etc.  

## Possible Solution

Possible solutions:
-  throw an error if users provide scalar_t = int; require users to copy their int data to float or double before calling MJ
-  allow users to provide scalar_t = int, but define an internal coordinate type as double and use that throughout the code; copy the user's int coordinates into the internal coordinate type and proceed
-  do a massive overhall of MJ to use scalar_t in some places and internal coordinate type where needed.  

I prefer the second solution over the first, but it will require more work; it will likely require changes related to #4211 as well.  The third solution would cause many code diffs, which would complicated the eventual merge of @MicheldeMessieres' work on GPU-enabled MJ.

## Steps to Reproduce

A test is already written:   zoltan2/test/partition/mj_int_coordinates.cpp.

## Related Issues

#4211 #4207

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/zoltan2 

## Description
Enables MJ partitioner to work with integer coordinates:  #4212 
- MJ requires floating point calculations for determining cuts
- MJ previously used the User's scalar_t for cuts, which was problematic when scalar_t was int
- Fix defines mj_scalar_t to be the user's scalar_t if it is a floating point type; otherwise, mj_scalar_t is float
- If mj_scalar_t differs from the user's scalar_t, coordinates are copied to mj_scalar_t arrays.

Also, removed templated types from coordinateModelPartBoxes.  #4211 
- coordinateModelPartBoxes store cut information computed by Zoltan2; their storage should not depend on the user's data types
-  changed storage in coordinateModelPartBoxes to be double
-  these changes were needed to enable fixing #4212 
-  removing the template parameters breaks backward compatibility

## Motivation and Context

I want to partition integer coordinates.

## Related Issues

* Closes #4212, #4211
* Still need to fix #1312 (as for scalar_t = int, it always returns imbalance = 1), but waiting until #1533 is merged to avoid conflicts 

## How Has This Been Tested?

new test zoltan2/test/partition/mj_int_coordinates.cpp
mac and linux

## Checklist

- [ x] My commit messages mention the appropriate GitHub issue numbers.
- [ x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] No new compiler warnings were introduced.
- [ x] These changes break backwards compatibility.:  removing template parameters breaks backward compatibility of functions returning coordinateModelPartBox

### CODE REVIEW

File: packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp [hunk 1]
```diff
@@ -99,9 +99,9 @@
...
 //imbalance calculation. Wreal / Wexpected - 1
 #define imbalanceOf(Wachieved, totalW, expectedRatio) \
-        double(Wachieved) / double((totalW) * (expectedRatio)) - 1
+        (Wachieved) / ((totalW) * (expectedRatio)) - 1
 #define imbalanceOf2(Wachieved, wExpected) \
-        double(Wachieved) / double(wExpected) - 1
+        (Wachieved) / (wExpected) - 1
 
 
 #define ZOLTAN2_ALGMULTIJAGGED_SWAP(a,b,temp) temp=(a);(a)=(b);(b)=temp;
```
Comment (mhoemmen) [inline packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp]: Please just use `std::swap` here.  If `a` or `b` are expressions with side effects, this macro will invoke the side effects multiple times.

File: packages/zoltan2/src/util/Zoltan2_StridedData.hpp [hunk 2]
```diff
@@ -158,6 +158,44 @@ class StridedData {
...
+// because cannot specialize member function of templated class.
+template<typename scalar_t, typename T>
+static void getInputArrayHelper(
+  ArrayRCP<const T> &target,
+  const ArrayRCP<const scalar_t> &src)
+{
+  // Create a copy of desired type T
+  // From logic in getInputArray, we know stride == 1.
+  size_t n = src.size();
+  T *tmp = new T [n];
```
Comment (mhoemmen) [inline packages/zoltan2/src/util/Zoltan2_StridedData.hpp]: You could just wrap `tmp` in an `ArrayRCP` from the beginning, using the `ArrayRCP` constructor that takes a raw pointer and `true` (for "owning")

File: packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp (hunk 1 above)
Comment (MicheldeMessieres) [reply packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp]: I'll take care of this when I merge some ongoing MJ work.
