### PR TITLE
Tpetra/MueLu/Ifpack2/Xpetra: remove all deprecated code (including DynamicProfile)

### LINKED ISSUE #5602: Tpetra: Removal of deprecated code meta issue
## Bug Report
@trilinos/tpetra 

### Description
Meta issue to track work to remove deprecated code from @trilinos/tpetra

The work (so far) concentrates on two configurations, each with deprecated code **disabled**:

1. Tpetra's global ordinal = `int` (`TPETRA_INST_INT_INT:BOOL=ON`)
2. Tpetra's global ordinal = the default value (`long long int`)

Each configuration has build and/or test problems outlined in the following comments.

*Related PRs*
- #5590 
- #5573 

*Related Issues*
- #5537 
- #5538 
- #5540 
- #5541 
- #5592 
- #5593 
- #5594 
- #5595 

*Supersedes*
- #5536

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/tpetra 
@trilinos/muelu 
@trilinos/ifpack2 
@trilinos/xpetra 

## Motivation

Removing all deprecated code from the core of the Tpetra stack. Much of this is related to the removal of DynamicProfile from Tpetra.

The motivation for that is to reduce the number of code paths in CrsGraph and CrsMatrix, and to provide opportunities for performance improvements that can't be done with the Teuchos array-of-arrays storage format. In StaticProfile, entries are stored in a 1D Kokkos::View with fixed storage allocated per row, much like a fill-complete matrix.

## Related Issues

* Closes #5602
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to  
* Part of 
* Composed of 

## Stakeholder Feedback

EMPIRE has already been building Trilinos successfully with deprecated code disabled.

## Testing

This change touches tests in just about every package downstream of Tpetra, but since this PR is about removing code, there are no new features that need to be tested.

### CODE REVIEW

File: packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp [hunk 1]
```diff
@@ -241,7 +241,6 @@ int ML_Epetra::RefMaxwell_SetupCoordinates(ML_Operator* A,
   return(0);
 }
 
-
```
Comment (mhoemmen) [inline packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp]: How did this get here?  I'm guessing it came in from a rebase.

File: packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp [hunk 2]
```diff
@@ -2152,6 +2152,15 @@ ComputePreconditioner(const bool CheckPreconditioner)
       ml_->Amat[LevelID_[0]].num_PDEs = NumPDEEqns_;
     }
 
+    if (List_.get("aggregation: material: enable", false)) {
```
Comment (mhoemmen) [inline packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp]: Woah, what's this?  Should we still have this here?  Do we need to rebase again or otherwise account for the latest changes in develop?

Comment (brian-kelley) [reply packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp]: Argh, I messed up the merge. But now, a recursive diff of the ml directories in this branch and develop shows no changes, which is how it should be.

File: packages/ifpack2/src/Ifpack2_Krylov_decl.hpp [hunk 3]
```diff
@@ -51,314 +51,4 @@
 #define IFPACK2_KRYLOV_DECL_HPP
 
 #include "Ifpack2_ConfigDefs.hpp"
-#ifdef HAVE_IFPACK2_DEPRECATED_CODE
```
[the remark this answers is not in the document]
Comment (brian-kelley) [reply packages/ifpack2/src/Ifpack2_Krylov_decl.hpp]: I just removed it, and the ETI line for it.

**Comment by brian-kelley** [comment]
@mhoemmen I fixed the things you noticed (thanks!) and scrolled through all the changes to make sure there were no other merge problems.

File: packages/tpetra/core/example/Finite-Element-Assembly/README.md [hunk 4]
```diff
@@ -15,8 +16,17 @@ Files
   - Provides helpers for processing command line options.
 - `fem_assembly_main`
   - Contains the main() function for the application.
+
+### Finite Element Mesh Assembly Example Sources
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/README.md]: Wait, where did these changes come from?

File: packages/tpetra/core/src/Tpetra_Vector_decl.hpp [hunk 5]
```diff
@@ -255,16 +255,6 @@ class Vector : public MultiVector<Scalar, LocalOrdinal, GlobalOrdinal, Node>
...
-  //! \name Clone method
-  //@{
-
-  /// \brief Return a deep copy of <tt>*this</tt> with a different
-  ///   Node type (and therefore a different Device type).
-  /// \tparam Node2 The returned Vector's Node type.
-  ///
-  /// \param node2 [in] The returned Vector's Kokkos Node instance.
-//@}
   //! @name Post-construction modification routines
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_Vector_decl.hpp]: There's probably a missing `//@}` above this.  I saw another one of these above.

**Comment by mhoemmen** [comment]
@brian-kelley Thanks!  I saw one interesting change to documentation in the latest changes -- not quite sure where that came from.

File: packages/tpetra/core/example/Finite-Element-Assembly/README.md (hunk 4 above)
Comment (brian-kelley) [reply packages/tpetra/core/example/Finite-Element-Assembly/README.md]: @mhoemmen When I removed the DynamicProfile versions, I removed too much of the actual explanations of the options from the README, so today I put them back.

Comment (mhoemmen) [reply packages/tpetra/core/example/Finite-Element-Assembly/README.md]: Thanks @brian-kelley ! :-)

File: packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp [hunk 6]
```diff
@@ -44,7 +44,7 @@
 #ifndef TPETRA_DETAILS_COPYCONVERT_HPP
 #define TPETRA_DETAILS_COPYCONVERT_HPP
 
-/// \file Tpetra_Details_convert.hpp
+/// \file Tpetra_Details_copyConvert.hpp
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp]: Nice catch! :-D

File: packages/tpetra/core/src/Tpetra_Details_gathervPrint.hpp [hunk 7]
```diff
@@ -41,7 +41,7 @@
 // @HEADER
 */
 
-/// \file Tpetra_Details_gatherPrint.hpp
+/// \file Tpetra_Details_gathervPrint.hpp
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_Details_gathervPrint.hpp]: Nice catch! :-D

**Comment by kddevin** [comment]
@csiefer2 @william76 Seems to be an Xpetra issue here.  Please can you help/advise?  Thanks

**Comment by brian-kelley** [comment]
@kddevin There were two build errors, both in my changes to Xpetra. I just pushed a fix.

**Comment by william76** [comment]
```
/home/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp(527): error: identifier "plist" is undefined

/home/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp(531): error: more than one instance of constructor "Xpetra::EpetraCrsMatrixT<long long, Xpetra::EpetraNode>::EpetraCrsMatrixT" matches the argument list:
            function "Xpetra::EpetraCrsMatrixT<long long, Xpetra::EpetraNode>::EpetraCrsMatrixT(const Teuchos::RCP<const Xpetra::CrsGraph<int, long long, Xpetra::EpetraNode>> &, const Teuchos::RCP<Teuchos::ParameterList> &)"
            function "Xpetra::EpetraCrsMatrixT<long long, Xpetra::EpetraNode>::EpetraCrsMatrixT(const Teuchos::RCP<Epetra_CrsMatrix> &)"
            argument types are: (const Teuchos::RCP<const Xpetra::Map<int, long long, Xpetra::EpetraNode>>)

/home/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_cuda_9.2/Trilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp(2011): error: name followed by "::" must be a class or namespace name
```
These don't look like they're related to any of the ETI work I've done. I won't have any time to look at anything Xpetra in any depth until sometime next week at the earliest. 
@csiefer2 @jhux2

**Comment by brian-kelley** [comment]
The dashboard servers seem to be giving HTTP 500 errors, which is killing both the autotester and the ability to see the results from the test that completed ~11 hours ago. It seems like there is an actual problem with the code though, since it says that some tests in Anasazi, FEI and Moertel didn't build. I will try to replicate and fix those on my local builds.

**Comment by brian-kelley** [comment]
Oops, I forgot to actually turn off Tpetra_ENABLE_DEPRECATED_CODE by default. That'll do it...

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 8]
```diff
@@ -2030,19 +2024,13 @@ namespace Tpetra {
     this->setLocallyModified ();
 
 #ifdef HAVE_TPETRA_DEBUG
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: This looks interesting.  What happened here?

Comment (brian-kelley) [reply packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: @mhoemmen Some variables that were only used inside HAVE_TPETRA_DEBUG blocks were declared outside of them.

**Comment by brian-kelley** [comment]
Hmm, the PR testing builds with Tpetra and Epetra both explicitly enabled, but Tpetra is using the default GO=long long. Then Xpetra complains that the GO types don't match. Could we make Tpetra use GO=int by default if Xpetra_ENABLE_Epetra and Epetra has 32-bit indices? I think that logic could just go in RepositoryDependenciesSetup.cmake, rather than doing another DUAL_SCOPE_SET() hack like before.

**Comment by mhoemmen** [comment]
@brian-kelley I worry that this would just make Tpetra use `GO=int` by default.  Users might not realize that they need to turn off Epetra in order to get the desired default Tpetra behavior.  I would prefer that Xpetra disable Epetra support if Tpetra's GO type isn't `int`.

**Comment by kddevin** [comment]
I agree with @mhoemmen. Tpetra should be the primary indicator of GO; it should not change to match legacy code.

**Comment by brian-kelley** [comment]
@kddevin @mhoemmen Sounds good.

**Comment by kddevin** [comment]
I tried to build the branch with the ATDM scripts used in ATDM testing, and got errors in Xpetra.  #6409

**Comment by mhoemmen** [comment]
@trilinos/tpetra Is the idea that we merge this PR on the deadline? or will we do a rebase first?

**Comment by csiefer2** [comment]
Stria (arm, SerialNode) build of Tpetra/MueLu w/ tests is good!

**Comment by kddevin** [comment]
On cee-lan with the following configuration, all tests from enabled packages (635 tests total) passed.
```
source /home//code/Trilinos/cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
cmake \
  -GNinja \
 -DMPI_EXEC=${MPI_EXEC} \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DTrilinos_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_COMPLEX:BOOL=OFF \
 -DTrilinos_ENABLE_Panzer:BOOL=ON \
 -DTrilinos_ENABLE_MueLu:BOOL=ON \
 -DTrilinos_ENABLE_Ifpack2:BOOL=ON \
 -DTrilinos_ENABLE_Teko:BOOL=ON \
 -DTrilinos_ENABLE_Tpetra:BOOL=ON \
 -DTrilinos_ENABLE_Zoltan2:BOOL=ON \
 -DTrilinos_ENABLE_Piro:BOOL=ON \
 -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
 -DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
 -DTPL_ENABLE_Matio=OFF \
 -DTPL_ENABLE_X11=OFF \
/home//code/Trilinos |& tee OUTPUT.CMAKE
```

**Comment by brian-kelley** [comment]
@mhoemmen Right after creating this PR (on Dec. 3) I merged develop into this branch, so I don't think we'll have any problems with conflicts.

**Comment by brian-kelley** [comment]
I just fixed a build error in a MueLu test which only showed up in a CUDA build. There were still some test failures:
```
	482 - Zoltan2_mjTest_uvmOff_MPI_4 (Failed)
	483 - Zoltan2_mjTest_geomgen_uvmOff_MPI_3 (Failed)
	484 - Zoltan2_mjTest_geomgen_noholes_uvmOff_MPI_3 (Failed)
	485 - Zoltan2_mjTest_geomgen_nomjparts_uvmOff_MPI_3 (Failed)
	682 - STKUnit_tests_stk_ngp_unit_tests_MPI_4 (Failed)
	683 - STKUnit_tests_stk_ngp_test_utest_MPI_4 (Failed)
	813 - MueLu_ParameterListInterpreterTpetra_MPI_1 (Failed)
	814 - MueLu_ParameterListInterpreterTpetra_MPI_4 (Failed)
	1006 - ROL_test_elementwise_TpetraMultiVector_MPI_4 (Failed)
	1107 - ROL_example_PDE-OPT_stefan-boltzmann_example_01_MPI_4 (Failed)
	1109 - ROL_example_PDE-OPT_stefan-boltzmann_example_03_MPI_4 (Failed)
	1112 - ROL_example_PDE-OPT_navier-stokes_example_02_MPI_4 (Failed)
	1113 - ROL_example_PDE-OPT_obstacle_example_01_MPI_4 (Failed)
	1118 - ROL_example_PDE-OPT_nonlinear-elliptic_example_01_MPI_4 (Failed)
	1119 - ROL_example_PDE-OPT_nonlinear-elliptic_example_02_MPI_4 (Failed)
	1120 - ROL_example_PDE-OPT_topo-opt_poisson_example_01_MPI_4 (Failed)
	1126 - ROL_example_tempus_example_parabolic_modeleval_forward-adjoint_MPI_1 (Failed)
```
I think some or all of the ROL failures have existed in develop for a while, but don't get caught by PR testing. There's a good chance the Zoltan2 failures are related to #6424. I don't know about the MueLu and STK ones.

**Comment by kddevin** [comment]
The Zoltan2 errors are #6412 .  @MicheldeMessieres  is looking at them.

**Comment by brian-kelley** [comment]
@kddevin OK, so that means this PR is clean. The other failures are happening in develop too: [Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt](https://testing-dev.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=5079570)

**Comment by brian-kelley** [comment]
Here are all the builds I've done locally (Skylake, Pascal P100, GCC 9.1.0, CUDA 10.1). There are a handful of test failures but they all exist in develop too and are being fixed.

- GO=long long, tests+examples: [configure](https://gist.github.com/brian-kelley/4bf7b79d0b1fe7734d2e0ec032e01a21)
- GO=int (Xpetra has Tpetra+Epetra support), tests+examples: [configure](https://gist.github.com/brian-kelley/a6847114109942ef7e4d567f309c5287). One failure (#6424) which is being fixed. 
- GO=long long, debug build, tests+examples: [configure](https://gist.github.com/brian-kelley/8d591c14398f61b1223cbc11a7b72ba9)
- CUDA, GO=long long: [configure](https://gist.github.com/brian-kelley/0baebd3bf121a53e53ce8eb1770d4016). Several test failures (3 comments up) but they are all happening in develop too.

**Comment by mhoemmen** [comment]
@trilinos/tpetra Are we gonna do this? :D

**Comment by brian-kelley** [comment]
@mhoemmen @kddevin I'm ready if you are.

**Comment by csiefer2** [comment]
:santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa:

**Comment by mhoemmen** [comment]
@trilinos/tpetra I did it :-)

**Comment by csiefer2** [comment]
:hear_no_evil: :see_no_evil: :speak_no_evil:
