### PR TITLE
Xpetra: fix MultiVector unit-test for Epetra=OFF configuration, see issue #5300

### LINKED ISSUE #5300: Xpetra: issue with un-guarded EpetraNode in MultiVector unit-test
## Bug Report
@trilinos/xpetra 

### Description
The Xpetra unit-test for MultiVector is not building correctly when Epetra is off due to an un-guarded `Xpetra::EpetraNode` as can be seen on the dashboard [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5130376), [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5129944) and [here](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5129516).

### Steps to Reproduce
Refer to the dashboard builds above.

### PR DESCRIPTION
**Pull request by lucbv**
Also fixing small warning in MueLu unit-tests for Epetra=OFF build:
Moved a variable declaration around to make sure it is not un-used.

@trilinos/xpetra 

## Description
The MultiVector unit-test in Xpetra does not build properly if Epetra is turned OFF

## Motivation and Context
This is a simple fix that adds a preprocessor guard around the Xpetra::EpetraNode check in the unit-test to avoid build error when Epetra is OFF.

## Related Issues

* Closes #5300 
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## How Has This Been Tested?
I performed a local build with Epetra=OFF and the unit-test was built correctly.

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

File: packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp [hunk 1]
```diff
@@ -538,18 +538,22 @@ namespace {
...
-      mvec.norm1(norms);
-      TEST_COMPARE_FLOATING_ARRAYS(norms,zeros,ScalarTraits<Magnitude>::zero());
-      mvec.normInf(norms);
-      TEST_COMPARE_FLOATING_ARRAYS(norms,zeros,ScalarTraits<Magnitude>::zero());
+    #ifdef HAVE_XPETRA_EPETRA
+    if(!is_same<typename MV::node_type, Xpetra::EpetraNode>::value)
+    #endif
+    {
+      if(!(is_same<typename MV::scalar_type, int>::value || is_same<typename MV::scalar_type, long long int>::value)) {
+        std::cout << "Running the norm tests!" << std::endl;
```
Comment (jhux2) [inline packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp]: This should be `*out` so that this doesn't print unconditionally.
