### PR TITLE
Amesos2: Fix #4992

### LINKED ISSUE #4992: Amesos2 does not support Epetra with Tpetra_INST_INT_INT=OFF
## Bug Report
@trilinos/amesos2 @rppawlo @kddevin 

### Description

Amesos2 does not support Epetra with `Tpetra_INST_INT_INT=OFF`.

### Steps to Reproduce

1. Set `Tpetra_INST_INT_INT=OFF` and `Amesos2_ENABLE_Epetra=ON`
2. Watch Amesos2 complain and fail to implement the feature

This is related to #3234.  That issue was about Amesos2 failing to catch its failure to implement this feature.

### PR DESCRIPTION
**Pull request by mhoemmen**
@trilinos/amesos2

## Description

- Permit Amesos2_ENABLE_Epetra=ON with Tpetra_INST_INT_INT=OFF.
- Fix Amesos2's build for that case.

This took me about an hour to do and required only trivial index conversions.

## Motivation and Context

@rppawlo needs this for Empire.  Tpetra developers want to deprecate and remove template parameters like GlobalOrdinal.  It's trivial to do index conversions, especially for a package like Amesos2, where the solves will take much longer than any index conversions that need to happen.

## Related Issues

* Closes #4992 
* Related to #3234

### CODE REVIEW

File: packages/amesos2/src/Amesos2_PardisoMKL.cpp [hunk 1]
```diff
@@ -307,7 +305,7 @@ TPETRA_ETI_MANGLING_TYPEDEFS()
   #endif
 #endif
 #ifdef HAVE_TPETRA_INST_COMPLEX_DOUBLE
-    #ifdef HAVE_TPETRA_INST_INT_INT
```
Comment (ndellingwood) [inline packages/amesos2/src/Amesos2_PardisoMKL.cpp]: @mhoemmen looks like you missed removing the corresponding `#endif` here

File: packages/amesos2/src/Amesos2_Util.cpp [hunk 2]
```diff
@@ -112,12 +109,11 @@ Amesos2::Util::to_epetra_comm(Teuchos::RCP<const Teuchos::Comm<int> > c)
     Teuchos::RCP<const Epetra_SerialComm> serialComm = rcp(new Epetra_SerialComm());
     return serialComm;
   }
-#endif	// HAVE_MPI
+#endif  // HAVE_MPI
```
Comment (ndellingwood) [inline packages/amesos2/src/Amesos2_Util.cpp]: @mhoemmen were there missing `#endif`s in this file? Asking since the number of `#ifdef` removed does not match removed `#endif`s

File: packages/amesos2/src/Amesos2_PardisoMKL.cpp (hunk 1 above)
Comment (mhoemmen) [reply packages/amesos2/src/Amesos2_PardisoMKL.cpp]: Thanks @ndellingwood !  I'll work on this.

Comment (mhoemmen) [reply packages/amesos2/src/Amesos2_PardisoMKL.cpp]: @ndellingwood I think this one looks fine -- thanks for checking, though!

File: packages/amesos2/src/Amesos2_Util.cpp (hunk 2 above)
Comment (mhoemmen) [reply packages/amesos2/src/Amesos2_Util.cpp]: @ndellingwood In my changed version, the counts of `#ifdef`s and `#endif`s match.  It's possible that the code was not correct before.

**Comment by mhoemmen** [comment]
@ndellingwood I think my changes are OK -- I pushed a new commit that adds some comments to make ifdef / endif pairs more clear in that one file.  Could you please rereview?  Thanks!

**Comment by mhoemmen** [comment]
Failure is because I marked this as WIP, which killed the builds.

File: packages/amesos2/src/Amesos2_Util.cpp (hunk 2 above)
Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_Util.cpp]: Oh goodness, thanks for clarifying!

**Comment by mhoemmen** [comment]
Thanks @ndellingwood ! :D
