### PR TITLE
Tpetra: Remove informational output from passing tests

### LINKED ISSUE #10885: Random failures due to jumbled output in TpetraCore_Bug7745_MPI_4 and TpetraCore_MultiVector_LocalViewTests_MPI_4 starting 2022-08-05?
CC: @trilinos/tpetra

## Description

As shown in [this query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-08-05&end=2022-08-15&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=status&compare2=61&value2=Failed&field3=testoutput&compare3=96&value3=Error%20initializing%20RM%20connection&field4=block&field4count=2&field4field1=testname&field4compare1=61&field4value1=TpetraCore_Bug7745_MPI_4&field4field2=testname&field4compare2=61&field4value2=TpetraCore_MultiVector_LocalViewTests_MPI_4) (click "Shown Matching Output" in upper right) the tests:

* `TpetraCore_Bug7745_MPI_4`
* `TpetraCore_MultiVector_LocalViewTests_MPI_4`

appear to be randomly failing in the builds:

* `PR-10801-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-331`
* `PR-10802-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-423`
* `PR-10808-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-325`
* `PR-10808-test-rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables-794`
* `PR-10834-test-rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables-409`

starting testing day 2022-08-05.

The `TpetraCore_Bug7745_MPI_4` test failues appear to be output jumbling the line `End Result: TEST PASSED` such as [here](https://trilinos-cdash.sandia.gov/test/9339461) showing:

```
Total Time: 0.0481 sec

Summary: total = 24, run = 24, passed = 24, failed = 0

End Result: 3 SUPERSET MAP
3 SUPERSET TO DEFAULT 
3 DEFAULT MAP
3 NOSAMES MAP
3 NOSAMES TO DEFAULT 
1 SUPERSET MAP
1 SUPERSET TO DEFAULT 
1 DEFAULT MAP
1 NOSAMES MAP
1 NOSAMES TO DEFAULT 
2 SUPERSET MAP
2 SUPERSET TO DEFAULT 
2 DEFAULT MAP
2 NOSAMES MAP
2 NOSAMES TO DEFAULT 
TEST PASSED
```

The test `TpetraCore_MultiVector_LocalViewTests_MPI_4` fails are also technically due to jumbling the line `End Result: TEST PASSED` line such as [here](https://trilinos-cdash.sandia.gov/test/10298214) showing:

```

Total Time: 0.401 sec

Summary: total = 24, run = 24, passed = 24, failed = 0

End 1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view
1 caught exception trying to get a local view while holding a device view
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view 
1 caught exception trying to get a device view while holding a local view
1 caught exception trying to get a local view while holding a device view
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view
2 caught exception trying to get a local view while holding a device view
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view 
2 caught exception trying to get a device view while holding a local view
2 caught exception trying to get a local view while holding a device view
3 caught exception trying to get a device view while holding a local view
3 caught exception trying to get a local view while holding a device view
3 caught exception trying to get a device view while holding a local view 
3 caught exception trying to get a device view while holding a local view 
3 caught exception trying to get a device view while holding a local view 
3 caught exception trying to get a device view while holding a local view 
3 caught exception trying to get a device view while holding a local view
3 caught exception trying to get a local view while holding a device view
Result: TEST PASSED
```

In the above case, it seems that even though all of the unit tests claimed to pass, the fact that so many exceptions are being thrown, that might indicate that this test is actually defective and it is just dumb chance that these exception messages are jumbling the line `End Result: TEST PASSED`

## Current Status on CDash

Run the [above query](https://trilinos-cdash.sandia.gov/queryTests.php?project=Trilinos&begin=2022-08-05&end=2022-08-15&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Pull%20Request&field2=status&compare2=61&value2=Failed&field3=testoutput&compare3=96&value3=Error%20initializing%20RM%20connection&field4=block&field4count=2&field4field1=testname&field4compare1=61&field4value1=TpetraCore_Bug7745_MPI_4&field4field2=testname&field4compare2=61&field4value2=TpetraCore_MultiVector_LocalViewTests_MPI_4) adjusting the "Begin" and "End" dates to match today any other date range or just click "CURRENT" in the top bar to see results for the current testing day.

## Steps to Reproduce

Follow instructions at:

* https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors

However, because these are random failures, triggering the failing test may be hard to do.

### PR DESCRIPTION
**Pull request by tasmith4**
@trilinos/tpetra @bartlettroscoe 

## Motivation
Informational output is of limited utility when tests are passing, and can randomly break automated PR testing when it overlaps with and breaks up the "test passed" output.

## Related Issues

* Closes #10885 

## Testing
Update to tests to improve robustness.

### CODE REVIEW

File: packages/tpetra/core/test/MultiVector/Bug7745.cpp [hunk 1]
```diff
@@ -81,7 +81,6 @@ TEUCHOS_UNIT_TEST_TEMPLATE_4_DECL(Bug7745, DefaultToDefault, Scalar,LO,GO,Node)
   Teuchos::RCP<const map_t> defaultMap = 
            rcp(new map_t(nGlobalEntries, 0, comm));
 
-  std::cout << me << " DEFAULT MAP" << std::endl;
   defaultMap->describe(foo, Teuchos::VERB_EXTREME);
```
Comment (brian-kelley) [inline packages/tpetra/core/test/MultiVector/Bug7745.cpp:84]: Should the map describe be gone too?

**Review by csiefer2 — DISMISSED** [review]

File: packages/tpetra/core/test/MultiVector/Bug7745.cpp (hunk 1 above)
Comment (csiefer2) [reply packages/tpetra/core/test/MultiVector/Bug7745.cpp:84]: I suspect they should go as well, yes.

Comment (tasmith4) [reply packages/tpetra/core/test/MultiVector/Bug7745.cpp]: done

**Review by brian-kelley — DISMISSED** [review]
