### PR TITLE
NOX: Make `Solver::SingleStep` independent on the group's `getNewton()` implementation

### LINKED ISSUE #14016: NOX: Make `NOX::Solver::SingleStep` independent on the group's `getNewton()` implementation
## Enhancement
Solver `NOX::Solver::SingleStep` reuses memory from the group:
https://github.com/trilinos/Trilinos/blob/618c4742e39bce83fbea98c1f930f51a389f71e9/packages/nox/src/NOX_Solver_SingleStep.C#L134-L138
The call to `getNewton()` throws exception for certain groups if they check that the Newton vector has been computed prior to the corresponding call. Surprisingly, not all groups do this: `NOX::Epetra::Group` and `NOX::Petsc::Group` have this check (i.e. may throw an exception), but `NOX::Thyra::Group` and `NOX::LAPACK::Group` - no.

This limitations has been spotted in our code 4C: https://github.com/4C-multiphysics/4C/issues/379. This lead to the appearance of a hacky member function in our group implementation (inherited from `NOX::Epetra::Group`) that would manually set flag `isValidNewton` to `true` such that the check `isNewton()` is successful. But that is just a way to circumvent the problem instead of resolving it.

One way to fix this bug would be to make the behavior consistent across groups by removing the check `isNewton()` inside `getNewton()`. However, in my opinion, it is a too strict requirement given the number of existing codes relying on these groups and, potentially, existence of other user group implementations which may adhere to the patterns from `NOX::Epetra::Group` and `NOX::Petsc::Group`.

Instead, I think, it is better to make `NOX::Solver::SingleStep` less dependent on the logic implemented inside a particular group. To this end, a separate vector is to be created in the solver to be used with the `applyJacobianInverse()` call. I will push a PR shortly with this proposal implemented. Test [Thyra_SingleStepSolver_1D.C](https://github.com/trilinos/Trilinos/blob/618c4742e39bce83fbea98c1f930f51a389f71e9/packages/nox/test/epetra/Thyra/Thyra_SingleStepSolver_1D.C.) (seems to a single test in Trilinos that uses `NOX::Solver::SingleStep`) passes.

This solution leads to a slight increase in memory consumption - an additional vector is created, however, improves robustness. An alternative solution would be to use `Group::computeNewton()` instead of manually calling `Group::applyJacobianInverse()`, but this need appeared due to the possibility of having Jacobian frozen (https://github.com/trilinos/Trilinos/issues/2394). Basically, we need to be able to take a RHS vector and a Jacobian from 2 different groups, and this requires certain trade-offs with the current `Group` interface. In fact, that what the earlier versions of `NOX::Solver::SingleStep` used to do: https://github.com/rppawlo/Trilinos/commit/bb3e41aefd8f34a157351f4fa84d370f420e23c8.

@trilinos/nox @rppawlo

### PR DESCRIPTION
**Pull request by vovannikov**
@trilinos/nox @rppawlo 

## Motivation
The current implementation of `NOX::Solver::SingleStep` is dependent on the behavior of `getNewton()` method of a particular group. The call to `getNewton()` throws an exception for certain groups if they check that the Newton vector has been computed prior to the corresponding call. Surprisingly, not all groups do this: `NOX::Epetra::Group` and `NOX::Petsc::Group` have this check (i.e. may throw an exception), but `NOX::Thyra::Group` and `NOX::LAPACK::Group` simply return the vector with no checks performed. The proposed modification makes `NOX::Solver::SingleStep` independent from this implementation detail.

## Related Issues
* Closes #14016

### CODE REVIEW

File: packages/nox/src/NOX_Solver_SingleStep.C [hunk 1]
```diff
@@ -132,7 +133,7 @@ bool NOX::Solver::SingleStep::try_step()
   Teuchos::RCP<NOX::Abstract::Group> jacobian = updateJacobian ? solnPtr : frozenJacobianPtr;
 
   // Reuse memory in group instead of new allocation for dir
```
Comment (rppawlo) [inline packages/nox/src/NOX_Solver_SingleStep.C:135]: Changes invalidate this comment. Could you remove the comment above?

Comment (vovannikov) [reply packages/nox/src/NOX_Solver_SingleStep.C]: Sure, I missed that. Done.
