### PR TITLE
Tpetra map get min global index

### LINKED ISSUE #2250: Tpetra: logic mistake in map getMinGlobalIndex/getMinAllGlobalIndex
When a rank holds no GIDs the map will return 0 as its min global index. 

@trilinos/tpetra 

@mhoemmen @csiefer2 

## Expectations
The map should return the true minimum GID across ranks and not `indexBase` when a rank holds no GIDs. A reasonable value needs to be returned by `map.getMinGlobalIndex()` on a rank with no GIDs.

## Current Behavior
As explained above, a map will `map.getMinAllGlobalIndex()` return `indexBase` if a process holds no GIDs. That is always wrong if the GIDs in the map are offset from IndexBase.

## Motivation and Context
If you have the following distribution of GIDs:
p0: [7, 8, 9]
p1:  [10, 11, 12]
p2: [13, 14, 15]
p3: []

map.getMinGlobalIndex() returns 0 on rank 3 and map.getMinAllGlobalIndex() returns 0. This type of GID partition happens after repartitioning a problem. I believe that most people will have 0 as the first index in maps, but this is not the case for multi physics problem represented by Xpetra BlockedMatrix.

## Definition of Done                                                 
- [ ] `getMinGlobalIndex()` needs to return a sensible value when no GIDs are on the local rank
- [ ] `getMinAllGlobalIndex()` needs to compute the min based on the range of GIDs used in the map.

## Possible Solution
I think that returning `Teuchos::OrdinalTraits<GlobalOrdinal>::max()` when calling getMinGlobalIndex on a rank that holds no GIDs is reasonable. Using `Teuchos::OrdinalTraits<GlobalOrdinal>::invalid()` instead of max() can create issues when using MPI_reduce(MIN,...) since invalid could return 0 if the `GlobalOrdinal` type is `int` or some signed type.

## Steps to Reproduce
Create a map using GIDs strictly higher than 0 and assign no GIDs to one rank, then call `getMinGlobalIndex()` and `getMinAllGlobalIndex()`

## Additional Information
It might be useful to check what Epetra is doing in this situation, it could have a work around or might have the same bug...

### PR DESCRIPTION
**Pull request by lucbv**
Change in the behavior of Tpetra map when a process holds no GID. The goal is to provide more logical returns from `getMinAllGlobalIndex()`

@trilinos/tpetra 

## Description
Change `minMyGID_` value to `Teuchos::OrdinalTraits<GlobalOrdinal>::max()` when a rank holds no GIDs.

## Motivation and Context
The current behavior is not logical and block repartitioning algorithm for `Xpetra::BlockedMatrix`

## Related Issues
* Closes  #2250 

## Checklist
- [x] My commit messages mention the appropriate GitHub issue numbers.
- [ ] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [x] These changes break backwards compatibility.

### CODE REVIEW

**Comment by lucbv** [comment]
I am now covering the nonuniform map case and I added two tests to check proper behavior.
I am running the checkin script locally to see that things are at least reasonable before removing [WIP] from title...

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+  using std::find;
+  using Teuchos::broadcast;
+  using Teuchos::OrdinalTraits;
+  using Teuchos::Comm;
+  using std::endl;
+
+  ////
+  TEUCHOS_UNIT_TEST_TEMPLATE_2_DECL( Map, getMinGlobalIndex_nonuniform, LO, GO )
+  {
+    typedef Map<LO,GO> Map;
```
Comment (mhoemmen) [inline packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: Please don't give a typedef the same name as a type; I'm not sure that's legit C++.

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp [hunk 2]
```diff
@@ -0,0 +1,212 @@
...
+    //
+
+    Map map (numGlobal, numLocal, indexBase, comm);
+    // create data to check validity of the map
+    const GO myMinGID =
+      (myRank == 0) ? std::numeric_limits<GO>::max() : (myRank - 1)*numLocal;
+    const GO myMaxGID =
+      (myRank == 0) ? std::numeric_limits<GO>::lowest() : myRank*numLocal - 1;
+    GO minAllGIDs, maxAllGIDs;
+    Teuchos::reduceAll<LO, GO>(*comm, Teuchos::REDUCE_MIN, myMinGID, outArg(minAllGIDs));
```
Comment (mhoemmen) [inline packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: The first template parameter of `Teuchos::reduceAll` should always be `int`, to match the template parameter of `Teuchos::Comm`.

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp [hunk 3]
```diff
@@ -0,0 +1,212 @@
...
+    std::cout << "p=" << myRank << " | map.getMaxGlobalIndex(): "
+              << map.getMaxGlobalIndex() << ", myMaxGID=" << myMaxGID << std::endl;
+    std::cout << "p=" << myRank << " | map.getMaxAllGlobalIndex(): "
+              << map.getMaxAllGlobalIndex() << ", maxAllGID=" << maxAllGIDs << std::endl;
+    //
+    TEST_EQUALITY(map.getGlobalNumElements(), numGlobal);
+    TEST_EQUALITY(map.getNodeNumElements(), numLocal);
+    TEST_EQUALITY(map.getIndexBase(), indexBase);
+    TEST_EQUALITY_CONST(map.getMinLocalIndex(), 0);
+    TEST_EQUALITY(map.getMaxLocalIndex(), numLocal - 1);
```
Comment (mhoemmen) [inline packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: The issue doesn't say anything about the behavior of `getMinLocalIndex` or `getMaxLocalIndex`, so the test should not test those methods.

Comment (mhoemmen) [reply packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: What I mean is that your test overconstrains the solution to the issue.  Currently, getMinLocalIndex always returns 0, even if the calling process has no indices.  You might like to change that behavior in the future, so that users could write a loop like this:
```
for (LO lid = map.getMinLocalIndex(); lid <= getMaxLocalIndex(); ++lid) { /* ... */ }
```
However, making that work is a separate issue.

File: packages/tpetra/core/test/Map/CMakeLists.txt [hunk 4]
```diff
@@ -189,3 +189,14 @@ TRIBITS_ADD_EXECUTABLE_AND_TEST(
...
   )
+
+
+TRIBITS_ADD_EXECUTABLE_AND_TEST(
+  Map_getMinGlobalIndex
+  SOURCES
+    Map_getMinGlobalIndex
+    ${TEUCHOS_STD_UNIT_TEST_MAIN}
+  COMM mpi
+  NUM_MPI_PROCS 4
```
Comment (mhoemmen) [inline packages/tpetra/core/test/Map/CMakeLists.txt]: It would be good to test both the 1 and > 1 number of processes cases.  Try this:
```
NUM_MPI_PROCS 1-4
```
Not sure if the following works but it would avoid a couple unnecessary executable runs:
```
NUM_MPI_PROCS 1 4
```

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp (hunk 1 above)
Comment (mhoemmen) [reply packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: Oh wait, MueLu normally does that.  I don't like it but if it's legit C++, I won't complain.

Comment (mhoemmen) [reply packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: Actually: If MueLu's "short names" normally does this, could this collide with MueLu's short names?  If so, please don't do it :-) .

**Comment by lucbv** [comment]
@mhoemmen, I have updated my test which also revealed a small problem in the case of the contiguous nonuniform map. I think that it should be fine now.
I ran the checkin script locally and changed a little the behavior of the Xpetra unit-test that check for correct maps in blocked operators. This test now passes fine.
There are two other tests failing:
- `1154 - Tempus_ExplicitRK_Staggered_FSA_MPI_1 (Timeout)`
- `1218 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_Serial_MPI_4 (Failed)`

I am fairly sure that the `Tempus` test timeout is not related to my changes and the failure in `Stokhos` is due to something that @csiefer2 pushed last week (at has been reverted since).

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp (hunk 1 above)
Comment (lucbv) [reply packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: Yeah, I lazily copied that bit from an other unit-test in `Tpetra`. I removed that typedef all together since I only use it once in the test.

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp (hunk 2 above)
Comment (lucbv) [reply packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: OK, switched template parameter to `int`.

File: packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp (hunk 3 above)
Comment (lucbv) [reply packages/tpetra/core/test/Map/Map_getMinGlobalIndex.cpp]: OK, I removed these two checks (again, lazy copy paste). I would be indeed a different issue although quite related to this one. We should make a note to discuss that later.

File: packages/tpetra/core/test/Map/CMakeLists.txt (hunk 4 above)
Comment (lucbv) [reply packages/tpetra/core/test/Map/CMakeLists.txt]: I made the change and I tested going from 1 to 4 mpi ranks. It works fine now.

**Comment by mhoemmen** [comment]
The Tempus test appears to be passing on the Dashboard, e.g., https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3395280

I'm OK with removing WIP though.
