### PR TITLE
Teuchos: fix the default values for help option for CommandLineProcessor

### LINKED ISSUE #585: Teuchos: CommandLineProcessor: depending on position --help may show incorrect default values
@trilinos/teuchos @bartlettroscoe 

```
$ ./MueLu_ReuseSequence.exe --xml=reuse_ml.xml  --help    --nx=400 --ny=400 --dim=2
...
--dim                  int           space dimension (default: --dim=3)

$ ./MueLu_ReuseSequence.exe --xml=reuse_ml.xml     --nx=400 --ny=400 --dim=2 --help
...
--dim                  int           space dimension (default: --dim=2)
```

### PR DESCRIPTION
**Pull request by aprokop**
Depending on whether help option was before or after some arguments on
the command line, it could affect the output. Specifically, the provided
command line values of other parameters could appear as the default ones
in the help output.

This patch fixes (or works around) the problem by first searching
through the parameters to find if help option is present.

Fix #585.

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
The change looks reasonable.  But I don't see any automated tests that are updated or changed because of this.  That means that this functionality could disappear and no one would notice for a long time.  See "All functionality will be covered by testing" and "Untested functionality is itself a bug" at:

* https://github.com/trilinos/Trilinos/wiki/Trilinos-Testing-Policy

**Comment by aprokop** [comment]
I'm not sure how to test this. It seems that you need an outside shell script to run some precompiled executable in two regimes, with --help in the beginning and at the end, dump the output into a file, and then do the comparison. I could write that but I'm not sure how well shell scripts could be integrated into CTest framework.

Another alternative is to somehow be able inside a test to redirect output to a string, and then compare  strings. I know how to redirect to a file (as we do in MueLu test) but not to a string buffer. My thought is to try to use `std::stringbuf`.

Please let me hear your thoughts.

**Comment by aprokop** [comment]
Added the test.

File: packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp [hunk 1]
```diff
@@ -196,7 +196,67 @@ int main( int argc, char* argv[] )
...
+    aux_argv[1] = &arg_n[0];
+    aux_argv[2] = &arg_h[0];
+
+    oldbuffer = std::cerr.rdbuf(&buffer2);   // redirect output
+    clp7.parse(aux_argc, aux_argv);
+    std::cerr.rdbuf(oldbuffer);              // redirect output back
+
+    if (verbose)
+      std::cout << "Test 7 :  CommandLineProcessor - Help position: ";
+    if (buffer1.str() != buffer2.str())
```
Comment (bartlettroscoe) [inline packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp]: Am I correct that this test only checks that the output is different?  Is there a way to check for the exact output you are looking for?

I was thinking that a test at the CTest level with a built example executable would do the trick.  I will pull this branch and take a look at writing a simpler test that more directly tests what you want.

Comment (bartlettroscoe) [inline packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp]: So if I you could give an example of  "could affect the output" and "the provided command line values of other parameters could appear as the default ones in the help output", it would make this CTest easy to capture what you are looking for.

**Comment by bartlettroscoe** [comment]
> I'm not sure how to test this.

BTW, sorry I did not get back to you sooner.  I was flying to ABQ and could not get on my laptop that night.  I just now got this this email.

**Comment by aprokop** [comment]
> Can you give an example "could affect the output" and "the provided command line values of other parameters could appear as the default ones in the help output"?

See an example in #585.

File: packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp (hunk 1 above)
Comment (aprokop) [inline packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp]: Yes, this tests only that the output is unchanged. I did not want the test depend on the exact style of output, as any change in it would require changing this test too. So, no magic sed-like command for parsing out the output value in square brackets which corresponds to default.

Comment (bartlettroscoe) [inline packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp]: Okay, that makes sense.  That is actually a stronger test that I imagined it was.

**Comment by bartlettroscoe** [comment]
> > Can you give an example "could affect the output" and "the provided command line values of other parameters could appear as the default ones in the help output"?
>
> See an example in #585.

Okay, yes I see.  That is a clear example.  I should have noticed the reference above.

If you don't mind, to be super safe, I can merge this and then run the checkin-test-sems.sh script ensure that this does not break anything in Trilinos.  I can do this a part of another push that I need to do.

**Comment by aprokop** [comment]
Sure, go ahead. I run checkin locally when I push, but I don't use SEMS (as I have no access to those anymore), and I typically do `--no-enable-fwd-packages` (though, in this case, I probably would not).

**Comment by bartlettroscoe** [comment]
I am in the process of testing and pushing this branch now ...

**Comment by bartlettroscoe** [comment]
Should be merged and ready to use.
