### PR TITLE
Amesos2: Potential fix for issue #2270

### LINKED ISSUE #2270: New timed-out Amesos2 tests in Trilinos-atdm-sems-gcc-7-2-0 build on 2/20/2018
**CC:** @trilinos/amesos2

##  Next Action Status 

The tests were disabled in all `Trilinos_ENABLE_DEBUG=ON` builds on 2/22/2018 (see [below](https://github.com/trilinos/Trilinos/issues/2270#issuecomment-367815146)).  Next: Fix the tests so that they pass?

## Description

The tests:

* Amesos2_KLU2_UnitTests_MPI_2
* Amesos2_Superlu_UnitTests_MPI_2

timed out at 10 minutes in the build `Trilinos-atdm-sems-gcc-7-2-0` this morning as shown at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=3396946

Prior to this morning, these tests were taking:

* Amesos2_KLU2_UnitTests_MPI_2: 1.5s
* Amesos2_Superlu_UnitTests_MPI_2: 1.7s

It looks like these tests are hanging due to an exception being thrown?

## Steps to Reproduce

Using the `do-configure` script:

```
#!/bin/bash
cmake \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/sems/atdm/SEMSATDMSettings.cmake,cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake \
-DDART_TESTING_TIMEOUT:STRING=300.0 \
-DTrilinos_ENABLE_TESTS:BOOL=ON \
-DCTEST_BUILD_FLAGS=-j10 \
-DCTEST_PARALLEL_LEVEL=10 \
"$@" \
$TRILINOS_DIR
```

Anyone should be able to reproduce these failures on any SNL COE RHEL6 machine as shown below:

```
$ cd <some_build_dir>/

$ source $TRILINOS_DIR/cmake/std/sems/atdm/load_atdm_7.2_dev_env.sh

$ ./do-configure -DTrilinos_ENABLE_Amesos2=ON

$ make -j16

$ ctest -j16
```

NOTE: The timeout like `-DDART_TESTING_TIMEOUT:STRING=300.0` is important or ctest will never end.

### PR DESCRIPTION
**Pull request by ndellingwood**
Fix multi-vector get1dCopy code error for non-contiguous GID case.
Re-enable tests when DEBUG is enabled.

@trilinos/amesos2 

## Description

Fix #2270 for broken non-contiguous GID cases (found in debug builds).

## How Has This Been Tested?
Local laptop (gcc/6.3) with mpi and debug modes enabled. 

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.

### CODE REVIEW

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 1]
```diff
@@ -211,23 +211,14 @@ namespace Amesos2 {
           const size_t lclNumRows = redist_mv.getLocalLength();
           for (size_t j = 0; j < redist_mv.getNumVectors(); ++j) {
             auto av_j = av(lda*j, lclNumRows);
-            auto X_j = redist_mv.getVector(j);
+            //auto X_j = redist_mv.getVector(j);
             auto X_lcl_j_2d = redist_mv.template getLocalView<host_execution_space> ();
             auto X_lcl_j_1d = Kokkos::subview (X_lcl_j_2d, Kokkos::ALL (), j);
             for ( size_t i = 0; i < lclNumRows; ++i ) {
               av_j[i] = X_lcl_j_1d(i);
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: This is broken with respect to UVM -- you'll need a fence before accessing these data on host.  That can be a separate issue, though.

Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: You could just do a `deep_copy` here instead of writing a for loop.

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 2]
```diff
@@ -335,7 +326,7 @@ namespace Amesos2 {
       // num_vecs = 1; stride does not matter
       auto mv_view_to_modify_2d = mv_->template getLocalView<host_execution_space>();
       for ( size_t i = 0; i < lda; ++i ) {
-        mv_view_to_modify_2d(i,0) = new_data[i];
+        mv_view_to_modify_2d(i,0) = new_data[i]; // Only one vector
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: Why not do a `deep_copy` instead of writing a for loop?

Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: @mhoemmen thanks for feedback! This was code I mostly worked on during my first go at using Tpetra awhile back, I wasn't sure if `deep_copy` from an `ArrayView` (`new_data`) and a 1d View was supported - I'm supposing it must be based on the suggestion.

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp (hunk 1 above)
Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: Good catch, I'll fix it now otherwise it may end up in a list of things that keeps growing.

**Comment by srajama1** [comment]
@ndellingwood : PR testing is failing, should I wait for that to be fixed before reviewing ?

**Comment by ndellingwood** [comment]
@srajama1 I think the PR testing issues were due to some other script issues addressed by #3302 unrelated to this PR, so go ahead and give a look though I have a couple small updates to push if you'd rather wait for that. I'm going to add a `fence()` following one of the multi-vector syncs in case UVM is in use; also I didn't realize `deep_copy` may work with an `ArrayView` as source or target, so I'll also add this in for faster copying instead of element-wise copy via for loop that's in there now.

**Comment by mhoemmen** [comment]
@ndellingwood wrote:
> also I didn't realize `deep_copy` may work with an ArrayView as source or target

Not sure about that -- probably not.  You'll have to turn the ArrayView into an unmanaged `Kokkos::View<..., Kokkos::HostSpace>`.  There may be a function in TeuchosKokkosCompat for that.

**Comment by srajama1** [comment]
I suggest keeping a WIP tag until you are done.

**Comment by ndellingwood** [comment]
@mhoemmen I replaced loop for element-wise copy with use of `std::memcpy`, also added `fence`s - do these look like they are in the correct place?

**Comment by ndellingwood** [comment]
@srajama1 just pushed extra changes to add a `fence` if UVM is used and replaced a some element-wise copies with use of `std::memcpy`. I think it should be ready now for review so I'll leave in the queue since the testing may take awhile, but if more changes are requested I'll put the WIP tag on to finish.

**Comment by ndellingwood** [comment]
For reference from local testing:
Test project /Users/ndellin/Research/trilinos/Trilinos/Build/Amesos2BaskerMPI-debug
```
    Start 1: Amesos2_KLU2_UnitTests_MPI_2
1/8 Test #1: Amesos2_KLU2_UnitTests_MPI_2 .........................   Passed    0.13 sec
    Start 2: Amesos2_Basker_UnitTests_MPI_2
2/8 Test #2: Amesos2_Basker_UnitTests_MPI_2 .......................   Passed    0.15 sec
    Start 3: Amesos2_SolverFactory_UnitTests_MPI_4
3/8 Test #3: Amesos2_SolverFactory_UnitTests_MPI_4 ................   Passed    0.16 sec
    Start 4: Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4
4/8 Test #4: Amesos2_Tpetra_MultiVector_Adapter_UnitTests_MPI_4 ...   Passed    0.06 sec
    Start 5: Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4
5/8 Test #5: Amesos2_Tpetra_CrsMatrix_Adapter_UnitTests_MPI_4 .....   Passed    0.10 sec
    Start 6: Amesos2_Epetra_MultiVector_Adapter_UnitTests_MPI_4
6/8 Test #6: Amesos2_Epetra_MultiVector_Adapter_UnitTests_MPI_4 ...   Passed    0.06 sec
    Start 7: Amesos2_Epetra_RowMatrix_Adapter_UnitTests_MPI_4
7/8 Test #7: Amesos2_Epetra_RowMatrix_Adapter_UnitTests_MPI_4 .....   Passed    0.06 sec
    Start 8: Amesos2_CrsMatrix_Adapter_Consistency_Tests_MPI_4
8/8 Test #8: Amesos2_CrsMatrix_Adapter_Consistency_Tests_MPI_4 ....   Passed    0.14 sec

100% tests passed, 0 tests failed out of 8
```

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 3]
```diff
@@ -211,12 +212,9 @@ namespace Amesos2 {
           const size_t lclNumRows = redist_mv.getLocalLength();
           for (size_t j = 0; j < redist_mv.getNumVectors(); ++j) {
             auto av_j = av(lda*j, lclNumRows);
-            //auto X_j = redist_mv.getVector(j);
             auto X_lcl_j_2d = redist_mv.template getLocalView<host_execution_space> ();
             auto X_lcl_j_1d = Kokkos::subview (X_lcl_j_2d, Kokkos::ALL (), j);
-            for ( size_t i = 0; i < lclNumRows; ++i ) {
-              av_j[i] = X_lcl_j_1d(i);
-            }
+            std::memcpy( &(av_j[0]), (X_lcl_j_1d.data()), sizeof( decltype(X_lcl_j_1d(0)) )*lclNumRows );
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: The `sizeof` thing _will_ break for Stokhos and Sacado dynamic-length Scalar types.  How about this instead:
```c++
using val_type = Kokkos::ArithTraits<Scalar>::val_type; // whatever Scalar is
Kokkos::View<val_type*, Kokkos::HostSpace> avk (reinterpret_cast<val_type*> (av.getRawPtr ()), av.size ());
Kokkos::deep_copy (avk, _lcl_j_1d);
```

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 4]
```diff
@@ -384,17 +380,15 @@ namespace Amesos2 {
           const size_t lclNumRows = redist_mv.getLocalLength();
           for (size_t j = 0; j < redist_mv.getNumVectors(); ++j) {
             auto av_j = new_data(lda*j, lclNumRows);
-            //auto X_j = redist_mv.getVector(j);
             auto X_lcl_j_2d = redist_mv.template getLocalView<host_execution_space> ();
             auto X_lcl_j_1d = Kokkos::subview (X_lcl_j_2d, Kokkos::ALL (), j);
-            for ( size_t i = 0; i < lclNumRows; ++i ) {
-              X_lcl_j_1d(i) = av_j[i];
-            }
+            std::memcpy( (X_lcl_j_1d.data()), &(av_j[0]), sizeof( decltype(X_lcl_j_1d(0)) )*lclNumRows );
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: See above.

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 5]
```diff
@@ -384,17 +380,15 @@ namespace Amesos2 {
...
           }
         }
 
         typedef typename multivec_t::node_type::memory_space memory_space;
         redist_mv.template sync <memory_space> ();
+        Kokkos::fence(); // For UVM
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: `sync` invokes `fence`, so you don't have to fence again here.

**Comment by srajama1** [comment]
There are comments from @mhoemmen about UQ types. I think this is important.

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp (hunk 3 above)
Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: @mhoemmen I didn't think about Fad types, thanks for suggested fix.

**Comment by ndellingwood** [comment]
Added WIP label, more changes needed. 
@mhoemmen Made the suggested change (required some extra `const_cast` trickery to get compiling). Can you look over again and see if this looks ready for a retest?

**Comment by ndellingwood** [comment]
The unit tests pass, here are those exercising the functionality:
```
    Start 1: Amesos2_KLU2_UnitTests_MPI_2
1/8 Test #1: Amesos2_KLU2_UnitTests_MPI_2 .........................   Passed    0.13 sec
    Start 2: Amesos2_Basker_UnitTests_MPI_2
2/8 Test #2: Amesos2_Basker_UnitTests_MPI_2 .......................   Passed    0.16 sec
```

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 6]
```diff
@@ -211,23 +212,14 @@ namespace Amesos2 {
...
             auto av_j = av(lda*j, lclNumRows);
-            auto X_j = redist_mv.getVector(j);
             auto X_lcl_j_2d = redist_mv.template getLocalView<host_execution_space> ();
             auto X_lcl_j_1d = Kokkos::subview (X_lcl_j_2d, Kokkos::ALL (), j);
-            for ( size_t i = 0; i < lclNumRows; ++i ) {
-              av_j[i] = X_lcl_j_1d(i);
-            }
+
+            using val_type = typename decltype( X_lcl_j_1d )::value_type;
+            Kokkos::View<val_type*, Kokkos::HostSpace> umavj ( const_cast< val_type* > ( reinterpret_cast<const val_type*> ( av_j.getRawPtr () ) ), av_j.size () );
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: How come `av_j` is const?  Now is not the time to dig into that, though ;-) .

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp (hunk 2 above)
Comment (mhoemmen) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: (Just to clarify -- the only way to use `deep_copy` with `ArrayView` right now is to turn the `ArrayView` into an unowned `HostSpace` `View`.  You did that above :) .)

Comment (mhoemmen) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: You'll also want to fix this bit in the same way that you fixed it above.  Also, if you know that the MultiVector has only one column, you could turn that 2-D View into a 1-D View first, before doing the copy.

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp [hunk 7]
```diff
@@ -392,12 +383,12 @@ namespace Amesos2 {
...
-            auto X_j = redist_mv.getVector(j);
             auto X_lcl_j_2d = redist_mv.template getLocalView<host_execution_space> ();
             auto X_lcl_j_1d = Kokkos::subview (X_lcl_j_2d, Kokkos::ALL (), j);
-            for ( size_t i = 0; i < lclNumRows; ++i ) {
-              X_lcl_j_1d(i) = av_j[i];
-            }
+
+            using val_type = typename decltype( X_lcl_j_1d )::value_type;
+            Kokkos::View<val_type*, Kokkos::HostSpace> umavj ( const_cast< val_type* > ( reinterpret_cast<const val_type*> ( av_j.getRawPtr () ) ), av_j.size () );
+            Kokkos::deep_copy (umavj, X_lcl_j_1d);
```
Comment (mhoemmen) [inline packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: 1. This code begs for a refactor -- this function ("copy from an ArrayView to a MultiVector") seems to come up a few times.
2. Does `new_data` come from a MultiVector?  If so, you could just `Tpetra::deep_copy` between the two MultiVectors.

Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: @mhoemmen: "this function ("copy from an ArrayView to a MultiVector") seems to come up a few times"

Yeah, we've reimplemented some optimizations from Amesos to avoid this for single process cases when the data pointer can be used directly without worrying about collectives to bring all data to the root proc. Adding @srajama1, we can discuss some possible options, estimate amount of work, availability etc.

"Does `new_data` come from a MultiVector"
No, `new_data` is an ArrayView storing the result (on root proc) of the solve. It needs to be copied back and redistributed to the MultiVector passed in through the `solve(...)` call.

Comment (srajama1) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: @ndellingwood : Can you file a different issue for optimizing this code. Let us get the PR with the current changes pushed in and we can look at optimizing this as a next step.

Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: @srajama1 sounds good :)

File: packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp (hunk 6 above)
Comment (ndellingwood) [reply packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp]: The RHS MV (i.e. 'B') is stored as const in the MVAdapter (after being copied on root proc) to prevent modification, which is why `av_j` ends up being `const`.
