### PR TITLE
Intrepid2: fix for #10714

### LINKED ISSUE #10714: Intrepid2: Cuda non-UVM test failure in multiple tests
## Bug Report
@trilinos/intrepid2 

### Description
The following unit tests are failing Cuda builds with UVM disabled as the default device memory space:
```
  319 - Intrepid2_unit-test_Projection_test_convergence_QUAD_Serial_DOUBLE_MPI_1 (Failed)
  321 - Intrepid2_unit-test_Projection_test_convergence_TRI_Serial_DOUBLE_MPI_1 (Failed)
  323 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_QUAD_Serial_DOUBLE_MPI_1 (Failed)
  325 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_TRI_Serial_DOUBLE_MPI_1 (Failed)
  327 - Intrepid2_unit-test_Projection_test_interpolation_projection_QUAD_Serial_DOUBLE_MPI_1 (Failed)
  329 - Intrepid2_unit-test_Projection_test_interpolation_projection_TRI_Serial_DOUBLE_MPI_1 (Failed)
  331 - Intrepid2_unit-test_Projection_test_convergence_QUAD_CUDA_DOUBLE_MPI_1 (Failed)
  333 - Intrepid2_unit-test_Projection_test_convergence_TRI_CUDA_DOUBLE_MPI_1 (Failed)
  335 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_QUAD_CUDA_DOUBLE_MPI_1 (Failed)
  337 - Intrepid2_unit-test_Projection_test_DeRham_commutativity_TRI_CUDA_DOUBLE_MPI_1 (Failed)
  339 - Intrepid2_unit-test_Projection_test_interpolation_projection_QUAD_CUDA_DOUBLE_MPI_1 (Failed)
  341 - Intrepid2_unit-test_Projection_test_interpolation_projection_TRI_CUDA_DOUBLE_MPI_1 (Failed)
```

A common output error message is
```
Kokkos::View ERROR: attempt to access inaccessible memory space
```

Though there may be other types of error as well (I didn't go through all the test output carefully)

### Steps to Reproduce
1. SHA1:  a0654795305b5d5fdbbd18d7123452cd4316f24e
2. Configure script:  (weaver testbed, rhel7W queue)
```bash
# Load modules
module purge
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
unset CUDA_LAUNCH_BLOCKING

# Configure
cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="14" \
 -DCMAKE_CXX_FLAGS="-pedantic -Wall" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DKokkos_ENABLE_CUDA_UVM=OFF \
 -DTrilinos_ENABLE_Intrepid2=ON \
 -DIntrepid2_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_Sacado=ON \
$TRILINOS_DIR
```

### PR DESCRIPTION
**Pull request by mperego**
A view was created without specifying the default space, creating issues when not using UVM.

@trilinos/intrepid2

## Motivation

Fixes #10714

### CODE REVIEW

File: packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp [hunk 1]
```diff
@@ -262,7 +262,7 @@ namespace Intrepid2 {
           \param  cellTopoKey     [in]  - key of the cell topology of the parameterized domain (1- and 2-subcells)
           \param  cellOrt         [in]  - cell orientation number (zero is aligned with shards default configuration
       */
-      template<typename pointType>
+      template<typename DeviceType, typename pointType>
```
Comment (kyungjoo-kim) [inline packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:265]: Why do we need this KOKKOS_INLINE_FUNCTION ? The function interface does not seem to allow this on device as it uses cell topology. This function is a host only function. It also means that this does not require device type.

File: packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HVOL.hpp [hunk 2]
```diff
@@ -177,7 +177,7 @@ getCoeffMatrix_HVOL(OutputViewType &output, /// this is device view
   auto cellTagToOrdinal = cellBasis.getAllDofOrdinal();
 
   double jacDet;
-  Intrepid2::Impl::OrientationTools::getJacobianDetOfOrientationMap(&jacDet,cellBaseKey,cellOrt);
+  Intrepid2::Impl::OrientationTools::getJacobianDetOfOrientationMap<host_device_type>(&jacDet,cellBaseKey,cellOrt);
```
Comment (kyungjoo-kim) [inline packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HVOL.hpp:180]: this does not have to be templated.

File: packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyPoints.hpp [hunk 3]
```diff
@@ -371,33 +371,33 @@ namespace Intrepid2 {
...
-        jacobian = Kokkos::View<pointType**>(jacobianDet,1,1);
+        jacobian = Kokkos::View<pointType**,DeviceType>(jacobianDet,1,1);
         getLineJacobian(jacobian, cellOrt);
         break;
       }
       case shards::Triangle<>::key :
       {
           pointType jac[4] = {};
-          jacobian = Kokkos::View<pointType**>(jac,2,2);
+          jacobian = Kokkos::View<pointType**,DeviceType>(jac,2,2);
```
Comment (kyungjoo-kim) [inline packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyPoints.hpp:392]: here, you wrap the jac array that is definitely host array. it is meaningless wrap with template argument of device type as it must be host memory space.

**Review by kyungjoo-kim — CHANGES_REQUESTED** [review]
it does not make sense to use template device type for your functions. used temporary array requires that it must be host memory.

File: packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp (hunk 1 above)
Comment (mperego) [reply packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp:265]: I don't need it to be KOKKOS_INLINE_FUNCTION, but it can be, and I used it before on device. It uses the topology Key,  not the topology. We do this all the time.

File: packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyPoints.hpp [hunk 4]
```diff
@@ -371,33 +371,33 @@ namespace Intrepid2 {
...
-    template<typename pointType>
+    template<typename DeviceType, typename pointType>
     KOKKOS_INLINE_FUNCTION
     void
     OrientationTools::
     getJacobianDetOfOrientationMap(pointType* jacobianDet,
                            const unsigned cellTopoKey,
                            const ordinal_type cellOrt) {
-      Kokkos::View<pointType**> jacobian;
+      Kokkos::View<pointType**,DeviceType> jacobian;
```
[the remark this answers is not in the document]
Comment (kyungjoo-kim) [reply packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyPoints.hpp:381]: it is callable but the interface seems to be very erroneous. 1) we do not know where the pointer comes from, 2) I don't think that it is a good idea that we always assume that the thread local temporary array matches to the templated device memory space.

[the remark this answers is not in the document]
Comment (mperego) [reply packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyPoints.hpp]: I agree the interface is not great. I decided to get rid of the function. As for the array, I think we make that assumption in several places.

**Review by kyungjoo-kim — APPROVED** [review]
simple
