### PR TITLE
Tpetra: Allow CrsMatrix with StaticProfile to resize during import/export

### LINKED ISSUE #5164: Tpetra: Allow CrsMatrix import/export to change its graph's structure
## Enhancement
@trilinos/tpetra 

PR #4147 allows import/export operations to  change the structure of a `CrsGraph`.  Importantly, the user cannot change the structure directly, the structure changes happen in internal `CrsGraph` methods.

@kddevin and @mhoemmen should `CrsMatrix` provide the same functionality?

The answer to whether or not `CrsMatrix` does provide the functionality will have implications on many tests that fail with deprecated code OFF.

### PR DESCRIPTION
**Pull request by tjfulle**
@trilinos/tpetra 

## Description
Allow CrsMatrix with StaticProfile to resize during import/export

## Motivation and Context
See #5164 

## Related Issues

* Closes #5164 

## How Has This Been Tested?
Tpetra tests pass locally

### CODE REVIEW

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 1]
```diff
@@ -5609,9 +5609,9 @@ namespace Tpetra {
         os << *prefix << "Target is StaticProfile; do CRS padding" << endl;
         std::cerr << os.str ();
       }
-      auto padding = computeCrsPaddingNew (srcRowGraph, numSameIDs,
-                                           permuteToLIDs, permuteFromLIDs);
-      this->applyCrsPadding (padding);
+      auto padding =
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: This is fine for now, but in the future, we should have a special case for when the target has a const graph.  If so, then we don't need to compute padding at all, since the target's structure can't change.

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 2]
```diff
@@ -5724,7 +5727,7 @@ namespace Tpetra {
     Kokkos::deep_copy(row_ptrs_beg, this->k_rowPtrs_);
 
     const size_t N = (row_ptrs_beg.extent(0) == 0 ? 0 : row_ptrs_beg.extent(0) - 1);
-      row_ptrs_type row_ptrs_end("row_ptrs_end", N);
+    row_ptrs_type row_ptrs_end("row_ptrs_end", N);
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: In the future, let's allocate this Kokkos::View without initializing, if that makes sense.

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 3]
```diff
@@ -5779,137 +5781,167 @@ namespace Tpetra {
   Kokkos::UnorderedMap<LocalOrdinal, size_t, typename Node::device_type>
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: In the future, when we get rid of template parameters, we'll want to get `device_type` from RowGraph, not from Node.

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 4]
```diff
@@ -5779,137 +5781,167 @@ namespace Tpetra {
...
+      const GO src_gid = src_row_map.getGlobalElement(tgt_lid);
+      auto num_src_entries = source.getNumEntriesInGlobalRow(src_gid);
+
+      if (num_src_entries == 0)
+        continue;
+
+      insert_result result;
+      const GO tgt_gid = rowMap_->getGlobalElement(tgt_lid);
+      if (padAll) {
+        result = padding.insert(tgt_lid, num_src_entries);
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: Right now, we just want things to compile and pass tests.  All the following comments are for the future.

I think you could use two 1-D `Kokkos::View`s to store padding information.  There are actually two sets of data over which to compute padding: sames, and permutes.  There's no reason why you need to store both in a single data structure, as long as the client can map from local row index to required padding.  The first data structure, for sames, could just be a 1-D `Kokkos::View`, since it's just indexed by `0 .. numSameIDs - 1`.  That would let you use a much smaller hash table for the second data structure.  Alternately, you could index the "permutes" padding data structure by the k in `permuteFromLIDs[k]`.  That would let you use a 1-D `Kokkos::View` as well.

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 5]
```diff
@@ -5779,137 +5781,167 @@ namespace Tpetra {
...
+        size_t check_row_length = 0;
+        src_row_inds.resize(num_src_entries);
+        source.getGlobalRowCopy(src_gid, src_row_inds(), check_row_length);
+
+        auto num_tgt_entries = this->getNumEntriesInGlobalRow(tgt_gid);
+        tgt_row_inds.resize(num_tgt_entries);
+        this->getGlobalRowCopy(tgt_gid, tgt_row_inds(), check_row_length);
+
+        size_t how_much_padding = 0;
+        for (const auto& src_row_ind : src_row_inds) {
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: References are bigger than values in this case, so you might as well just use `auto` instead of `const auto&` here.

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp [hunk 6]
```diff
@@ -2434,6 +2436,7 @@ namespace Tpetra {
           // curOffset, the range is empty.
           const LO numIndInSeq = (endOffset - curOffset);
           if (numIndInSeq != 0) {
+            rowInfo = graph.getRowInfo(lclRow);  // KDD 5/19 Need fresh RowInfo in each loop iteration
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: Not really.  `insertGlobalValuesImpl` actually updates its `rowInfo` argument (it's a read + write argument).  It should have the correct values on exit.  Calling `getRowInfo` can be a bit expensive, which is why the `insert*ValuesImpl` and other methods separate that out.

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp [hunk 7]
```diff
@@ -6615,6 +6618,98 @@ namespace Tpetra {
...
+      refill_num_row_entries = true;
+      auto num_row_entries = myGraph_->k_numRowEntries_;
+      Kokkos::parallel_for("Fill end row pointers", range_policy(0, N),
+                           KOKKOS_LAMBDA(const size_t i){
+                             row_ptr_end(i) = row_ptr_beg(i) + num_row_entries(i);
+                           }
+                           );
+
+    } else {
+      // mfh If packed storage, don't need row_ptr_end to be separate allocation;
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: What about this comment?

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp [hunk 8]
```diff
@@ -6615,6 +6618,98 @@ namespace Tpetra {
...
+                           );
+    }
+
+    using values_type = typename local_matrix_type::values_type;
+    values_type values("values", k_values1D_.size());
+    Kokkos::deep_copy(values, k_values1D_);
+
+    if(myGraph_->isGloballyIndexed()) {
+      using indices_type = typename crs_graph_type::t_GlobalOrdinal_1D;
+      indices_type indices("indices", myGraph_->k_gblInds1D_.extent(0));
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: Do a view allocation without initializing here.

File: packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp [hunk 9]
```diff
@@ -6615,6 +6618,98 @@ namespace Tpetra {
...
+      padCrsArrays<row_ptrs_type,indices_type,values_type,padding_type>(row_ptr_beg, row_ptr_end, indices, values, padding);
+      myGraph_->k_gblInds1D_ = indices;
+      TEUCHOS_TEST_FOR_EXCEPTION_CLASS_FUNC(
+          values.size() != indices.size(),
+          std::logic_error,
+          "After padding, values and indices should be same size");
+    }
+    else {
+      using indices_type = typename local_graph_type::entries_type::non_const_type;
+      indices_type indices("indices", myGraph_->k_lclInds1D_.extent(0));
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp]: Do a view allocation without initializing here.

File: packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp [hunk 10]
```diff
@@ -106,10 +109,13 @@ pad_crs_arrays(
...
     }, additional_size_needed);
 
-  if (additional_size_needed == 0) return;
+  if (additional_size_needed == 0)
+    return;
 
   // The indices array must be resized and the row_ptr arrays shuffled
   auto indices_new = uninitialized_view<Indices>("ind new", indices.size()+additional_size_needed);
+  auto values_new = uninitialized_view<Values>("val new", pad_values ? values.size()+additional_size_needed : 0);
+  Kokkos::deep_copy(values_new, Teuchos::ScalarTraits<typename Values::value_type>::zero());
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp]: `Kokkos::View` allocation initializes with zero by default; you could save a line of code here by relying on that.

File: packages/tpetra/core/test/CrsMatrix/CrsMatrix_StaticImportExport.cpp [hunk 11]
```diff
@@ -0,0 +1,232 @@
...
+  auto A = rcp(new matrix_type(map, 3, Tpetra::StaticProfile));
+
+  // const size_t numMyElements = map->getNodeNumElements ();
+  // The list of global elements owned by this MPI process.
+  const Tpetra::global_size_t num_gbl_inds = map->getGlobalNumElements();
+  auto my_gbl_elems = map->getNodeElementList();
+  for (auto it : my_gbl_elems) {
+    const auto gbl_row = map->getGlobalElement(it);
+    if (gbl_row == 0)
+      A->insertGlobalValues(gbl_row, tuple(gbl_row, gbl_row+1), tuple(two, neg_one));
```
Comment (mhoemmen) [inline packages/tpetra/core/test/CrsMatrix/CrsMatrix_StaticImportExport.cpp]: Everybody's favorite matrix ;-P

File: packages/tpetra/core/test/CrsMatrix/CrsMatrix_StaticImportExport.cpp [hunk 12]
```diff
@@ -0,0 +1,232 @@
...
+  }
+  B->fillComplete();
+
+  auto loc_num_errs = 0;
+
+  // The test below uses the host Tpetra::CrsMatrix interface to
+  // compare matrix values.  Thus, we need to do a fence before
+  // comparing matrix values, in order to ensure that changes made on
+  // device are visible on host.
+  execution_space::fence();
```
Comment (mhoemmen) [inline packages/tpetra/core/test/CrsMatrix/CrsMatrix_StaticImportExport.cpp]: `fence()` as a static method has been deprecated in Kokkos.  Do this instead:
```c++
execution_space ().fence ();
```

File: packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp [hunk 13]
```diff
@@ -890,21 +890,6 @@ inline void tupleToArray(Array<T> &arr, const tuple &tup)
       GO r = map->getMinGlobalIndex();
       TEST_THROW( matrix.insertGlobalValues( r, tuple(r+1), tuple(ST::one()) ), std::runtime_error );
     }
-    if (numImages > 1) {
```
Comment (mhoemmen) [inline packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp]: Do we still want this test here?

**Comment by kddevin** [comment]
@tjfulle Does Tpetra test TpetraCore_CrsMatrix_NonlocalAfterResume pass for you with TPETRA_ENABLE_DEPRECATED_CODE=OFF?  With my branch and this PR merged into it, this test still hangs for me.  All other Tpetra tests are fine.  Some Teko tests still fail; I will look at them.

**Comment by mhoemmen** [comment]
@kddevin Don't forget to avail yourself of the `TPETRA_VERBOSE=1` environment variable setting.

**Comment by kddevin** [comment]
Good suggestion, @mhoemmen .  Thanks.  Stay tuned.

**Comment by tjfulle** [comment]
@mhoemmen, as you noted, this is a stop gap for getting dynamic profile deprecated.  per our previous discussions, I think this whole area of Tpetra could use some serious clean up.

@kddevin, this PR is only to add matrix resizing during import/export.  I suspect this will help with #5065, but probably is not a complete fix.  Let’s chat tomorrow about syncing our efforts to finish #5065

**Comment by tjfulle** [comment]
Arg - failed to build with complex - should be an easy fix.  I'll look at the other test failures too.

File: packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp [hunk 14]
```diff
@@ -112,37 +112,39 @@ pad_crs_arrays(
...
 
+  using ptrs_value_type = typename RowPtr::non_const_value_type;
+  using inds_value_type = typename Indices::non_const_value_type;
+  using vals_value_type = typename Values::non_const_value_type;
+
   // The indices array must be resized and the row_ptr arrays shuffled
   auto indices_new = uninitialized_view<Indices>("ind new", indices.size()+additional_size_needed);
   auto values_new = uninitialized_view<Values>("val new", pad_values ? values.size()+additional_size_needed : 0);
-  Kokkos::deep_copy(values_new, Teuchos::ScalarTraits<typename Values::value_type>::zero());
+  Kokkos::deep_copy(values_new, vals_value_type(0.0));
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp]: You could also use `Kokkos::ArithTraits<vals_value_type>::zero()`, though this is fine (even for integer or complex types).

File: packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp [hunk 15]
```diff
@@ -112,37 +112,39 @@ pad_crs_arrays(
...
 
   // mfh: Not so fussy about this not being a kernel initially,
   // since we're adding a new feature upon which existing code does not rely,
   // namely Export/Import to a StaticProfile CrsGraph.  However, watch out
   // for fence()ing relating to UVM.
   auto this_row_beg = row_ptr_beg(0);
   auto this_row_end = row_ptr_end(0);
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp]: For the future: `Kokkos::deep_copy` now supports copying from a 0-D device View to a value in host memory.  Thus, you could do this:
```c++
ptrs_value_type this_row_beg;
Kokkos::deep_copy (this_row_beg, Kokkos::subview (row_ptr_beg, 0));
```

**Comment by mhoemmen** [comment]
@micahahoward FYI, this is the complicated issue I was talking about that we wanted to finish before trying host-pinned buffers (getting that to compile required touching all of this code which is currently in flux and really needs to be right).

File: packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp (hunk 15 above)
Comment (tjfulle) [reply packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp]: I still have some work to do to build/pass tests on Cuda.  Is this preferred?  If so, I'll make the change now.

Comment (mhoemmen) [reply packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp]: @tjfulle I wouldn't worry about this for now.  You're accessing every row, so it will likely be faster just to let UVM do its thing.  I would prefer that we spent future effort on making this into a parallel kernel on device.  Thanks though!

**Comment by tjfulle** [comment]
Hmmm, the PR tester does not seem to be building the most recent commit.

**Comment by tjfulle** [comment]
Hmmm, passes on all platforms but Linux+intel17.  These 4 Zoltan2 tests fail with that combination:
- `Zoltan2_TpetraRowGraphInput_MPI_4`
- `Zoltan2_TpetraRowMatrixInput_MPI_4`
- `Zoltan2_XpetraCrsGraphInput_MPI_4`
- `Zoltan2_XpetraTraits_MPI_4`

They all report “PASS”, but dangling RCPs cause a test failure.

@kddevin, do these sound familiar?  Any ideas?  If not, I can get a debut build going with intel to try and track it down.

**Comment by kddevin** [comment]
@tjfulle 
I have not seen failures in these Zoltan2 tests before.  
All of these tests do roughly the following:
- read a very simple matrix from a file onto four processors (using Tpetra's matrix-market reader)
- collect the matrix or graph onto one processor using Tpetra's Import.  I believe they call importAndFillComplete for the CrsMatrix (which is not reporting problems) and doImport for the CrsGraph (which is reporting problems).  I'd have to look a little more closely to see how we're testing RowMatrix.  

I'd start with XpetraCrsGraphInput.cpp.  If we fix one, we'll likely fix them all.  

Unfortunately, I will not have time to look at it today, but I am happy to work on it tomorrow if it can wait until then.

**Comment by tjfulle** [comment]
@kddevin I'll take a look to see if I see anything.  If I run in to problems, I'll let you know.

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp (hunk 4 above)
Comment (tjfulle) [reply packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: yep, when this is done, I have some ideas along the lines you mention above to get rid of `UnorderedMap` in favor of a `Kokkos::View`

**Comment by tjfulle** [comment]
The error on intel comes down to this function: https://github.com/trilinos/Trilinos/pull/5268/files#diff-90fa5171ebff6b0e9646050da6ce8bd3R5869

I'll take a detailed look at how this function differs from similar code in the master branch to see why it errors and master doesn't.  `valgrind` got me in the ballpark, hopefully `idb` can get me the rest of the way.

**Comment by tjfulle** [comment]
@mhoemmen, do you see anything obvious in `CrsGraph::computeCrsPaddingForPermutedIDs` that would lead to dangling `RCP`?

**Comment by mhoemmen** [comment]
@tjfulle Nothing looks obviously wrong in this function.  You could add a debug-mode all-reduce check in DistObject to see whether all the MPI processes actually make it through the routine.  It's entirely possible that the Zoltan2 tests in question only check if Process 0 made it through.  You could also check whether the input Map / Comm is null; I'm not sure whether that could happen due to subcommunicator stuff.

**Comment by tjfulle** [comment]
Ughhh, the sems installation of mpich loaded with the Intel17 pull request environment does not have debug support (options `-tv` or `-debug` not recognized).  I'll have to rebuild with openmpi (which was built with debug support)

**Comment by mhoemmen** [comment]
> Ughhh, the sems installation of mpich loaded with the Intel17 pull request environment does not have debug support (options `-tv` or `-debug` not recognized). 

:-(  Can you get away with not building the TPLs at least?

**Comment by tjfulle** [comment]
Sems has an Intel/openmpi stack, so I can just swapped the mpich and openmpi modules and rebuilt Trilinos.  I’m firing up totalview as we speak.

File: packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp [hunk 16]
```diff
@@ -5837,12 +5833,14 @@ namespace Tpetra {
       }
       else {
         size_t check_row_length = 0;
-        src_row_inds.resize(num_src_entries);
-        source.getGlobalRowCopy(src_gid, src_row_inds(), check_row_length);
+        std::vector<GO> src_row_inds(num_src_entries);
```
Comment (mhoemmen) [inline packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp]: Tim and I talked on the phone about this.  As far as he can tell, some issue with Teuchos memory management classes' debug-mode checking caused the test failures.  That's why he replaced the `Teuchos::Array` with `std::vector` here.

@tjfulle , you could use exactly the same `resize` logic for `std::vector` as for `Teuchos::Array`; it should work fine.  In fact, you don't have to resize the vector if it already has enough space; just resize if you need more space, and always give `Teuchos::ArrayView`'s constructor `num_src_entries` instead of `src_row_inds.size()` as its size.

**Comment by mhoemmen** [comment]
@tjfulle CONGRATS !!! :-D 

As another data point: I've noticed before that Intel 17 is a bit buggy where GCC and Clang are not.
