### PR TITLE
Galeri muelu fix

### LINKED ISSUE #2060: Galeri: fix rotational modes for Xpetra
Galeri generates wrong rotational modes for elasticity (both 2D and 3D) for Xpetra (`src-xpetra`) due to mismatched dimensions of coordinates and nullspace vectors. The solution is trivial: do `y[i/NSDim_]` instead of `y[i]`, for example.

Also need to update MueLu's Driver to use `nullspace` as that was part of the reason that was never exposed.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #2060.

### CODE REVIEW

File: packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp [hunk 1]
```diff
@@ -125,7 +125,7 @@ namespace Galeri {
     template <typename Scalar, typename LocalOrdinal, typename GlobalOrdinal, typename Map, typename Matrix, typename MultiVector>
     Teuchos::RCP<Matrix> Elasticity2DProblem<Scalar,LocalOrdinal,GlobalOrdinal,Map,Matrix,MultiVector>::BuildMatrix() {
       using Teuchos::SerialDenseMatrix;
-      typedef Teuchos::ScalarTraits<SC> TST;
+      typedef Teuchos::ScalarTraits<SC> STS;
```
Comment (jhux2) [inline packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp]: This is not a big deal to me, but why did you change TST to STS?

File: packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp [hunk 2]
```diff
@@ -402,27 +402,27 @@ namespace Galeri {
...
-        norms2[i] = norms2[0] / norms2[i];
-      norms2[0] = TST::magnitude(TST::one());
+      Teuchos::Array<typename STS::magnitudeType> norms2(numVectors);
       this->Nullspace_->norm2(norms2);
-      Teuchos::Array<Scalar> norms2scalar(numVectors);
       for (int i = 1; i < numVectors; i++)
+        norms2[i] = norms2[0] / norms2[i];
+      norms2[0] = STS::magnitude(STS::one());
+      Teuchos::Array<SC> norms2scalar(numVectors);
+      for (int i = 0; i < numVectors; i++)
```
Comment (jhux2) [inline packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp]: For the purposes of SA multigrid, this normalization with the first nullspace vector doesn't seem useful to me, as the QR process will handle any poor scaling.

Previously, was the first vector getting scaled by zero?!

File: packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp [hunk 3]
```diff
@@ -383,13 +383,13 @@ namespace Galeri {
...
+      Teuchos::Array<typename STS::magnitudeType> norms2(numVectors);
+      this->Nullspace_->norm2(norms2);
       for (int i = 1; i < numVectors; i++)
         norms2[i] = norms2[0] / norms2[i];
-      norms2[0] = TST::magnitude(TST::one());
-      this->Nullspace_->norm2(norms2);
+      norms2[0] = STS::magnitude(STS::one());
       Teuchos::Array<SC> norms2scalar(numVectors);
-      for (int i = 1; i < numVectors; i++)
+      for (int i = 0; i < numVectors; i++)
```
Comment (jhux2) [inline packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp]: For the purposes of SA multigrid, this normalization with the first nullspace vector doesn't seem useful to me, as the QR process will handle any poor scaling.

Previously, was the first vector getting scaled by zero?!

File: packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp (hunk 1 above)
Comment (aprokop) [reply packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp]: Cause it's that way in Xpetra/MueLu... And I don't recall why.

File: packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp (hunk 3 above)
Comment (aprokop) [reply packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp]: > For the purposes of SA multigrid, this normalization with the first nullspace vector doesn't seem useful to me, as the QR process will handle any poor scaling.

Sure, it may not be necessary.

> Previously, was the first vector getting scaled by zero?!

Yep, the root of your troubles.

**Comment by jhux2** [comment]
Looks good to me.

**Comment by aprokop** [comment]
@jhux2 I updated the PR:
- Changed back from STS to TST
- Removed scaling of the first vector
  It did not make any sense, as all other vectors would get `norms[0]` norm, while the first one would get norm=1.

File: packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp [hunk 4]
```diff
@@ -402,27 +402,26 @@ namespace Galeri {
...
       Teuchos::Array<typename TST::magnitudeType> norms2(numVectors);
-      for (int i = 1; i < numVectors; i++)
-        norms2[i] = norms2[0] / norms2[i];
-      norms2[0] = TST::magnitude(TST::one());
       this->Nullspace_->norm2(norms2);
-      Teuchos::Array<Scalar> norms2scalar(numVectors);
       for (int i = 1; i < numVectors; i++)
+        norms2[i] = norms2[0] / norms2[i];
+      Teuchos::Array<SC> norms2scalar(numVectors);
+      for (int i = 0; i < numVectors; i++)
```
Comment (jhux2) [inline packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp]: The idea is that all vectors except the 0th one should be scaled, and the 0th one should be unchanged.

Note that norms2[0] = ||Nullspace[0]||, however, so in fact the call to `this->Nullspace_->scale(norms2scalar)` will scale the 0th vector by its original norm.

Comment (aprokop) [reply packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp]: You are right, I thought I was being smart... 
Pushed the update.
