### PR TITLE
ShyLU: Removing dependency on MueLu, reorganization of tests, and restructuring the Thyra interface of FROSch

### LINKED ISSUE #3846: ShyLU/FROSch: config flags not properly included
@trilinos/shylu 

## Expectations
Enable a proper inclusion of the define flags `HAVE_SHYLU_DDFROSCH_EPETRAEXT` and `HAVE_EPETRAEXT_HDF5` in the test  `ShyLU_DDFROSch_twolevelblockinputfiles.exe` defined in `packages/shyly/shylu_dd/frosch/tests/TwoLevelPreconditionerBlockInputFiles/main.cpp`.

## Current Behavior
The two flags `HAVE_SHYLU_DDFROSCH_EPETRAEXT` and `HAVE_EPETRAEXT_HDF5` seem not to be included into the test. 

## Motivation and Context
The tests just prints the parameter list to screen and then does _not_ perform any computations. Hence, it always passes without doing the actual testing.

## Definition of Done
- [ ] Guarantee proper inclusion of all necessary define flags.

## Possible Solution
For now, I manually included `ShyLU_DDFROSch_config.h` and `EpetraExt_config.h` at the very top of the list of header inclusions. Not sure, if this is an appropriate fix to be committed.

## Steps to Reproduce
In your build directory, execute the test `packages/shyly/shylu_dd/frosch/tests/TwoLevelPreconditionerBlockInputFiles/ShyLU_DDFROSch_twolevelblockinputfiles.exe`. The tests just prints the parameter list to screen and then does _not_ perform any computations. Hence, it always passes without doing the actual testing.

## Your Environment
- **Relevant repo SHA1s:**  cb7bb14910bd76d554926f6a0c3d5c5353f0cef9
- **Relevant configure flags or configure script:**  
[do-configure-trilinos_shylu2.txt](https://github.com/trilinos/Trilinos/files/2571642/do-configure-trilinos_shylu2.txt)
- **Operating system and version:**  Ubuntu 16.04
- **Compiler and TPL versions:**  

## Additional Information
* Configure log file:  
[configure.log](https://github.com/trilinos/Trilinos/files/2571634/configure.log)

## Interested Parties
@searhein

### PR DESCRIPTION
**Pull request by searhein**
@trilinos/shylu 

## Description

This PR convert many minor changes in FROSch:
- The dependency of FROSch on MueLu has been removed. In the tests, we now always call Belos through Thyra. 
- Missing ifdefs for optional dependencies have been added. This should also fix #3846.
- The FROSch tests have been reorganized to remove redundancies and to make sure that all relevant `SchwarzOperator`s are being tested.
- The previous Thyra interfaces for `TwoLevelPreconditioner` and `TwoLevelBlockPreconditioner` have been merged and the other `SchwarzPreconditioner`s have been added to the Thyra interface.
- Some minor issues have been fixed along the way.

## Checklist

- [ ] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by mhoemmen** [comment]
Test failure looks legit:
```
terminate called after throwing an instance of 'Xpetra::Exceptions::RuntimeError'
  what():  /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp:232:

Throw number = 1

Throw test that evaluated to true: true

Xpetra::EpetraCrsMatrix only available for GO=int or GO=long long with EpetraNode (Serial or OpenMP depending on configuration)  what():  /scratch/trilinos/workspace/trilinos-folder/Trilinos_pullrequest_gcc_4.8.4/Trilinos/packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp:232:
```

**Comment by mhoemmen** [comment]
Marking as WIP, since the test fails consistently.

**Comment by mayrmt** [comment]
I'm trying to build this branch, but I get some more errors due to missing or disabled packages. Looks like some configuration checks are still missing.

Here they the errors:
```
src-trilinos/packages/shylu/shylu_dd/frosch/test/Import_Tpetra/main.cpp:48:25: fatal error: Galeri_Maps.h: No such file or directory
```
```
src-trilinos/packages/shylu/shylu_dd/frosch/test/Import_Tpetra/main.cpp:59:30: fatal error: BelosOperatorT.hpp: No such file or directory
```
When enabling packages `Galeri` and `Belos`, the build works just fine. 

@searhein Should we add a safety check to capture such errors?

**Comment by searhein** [comment]
@mayrmt Thanks for this comment. I am working on this branch at the moment and I will add the safety checks later today.

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp [hunk 1]
```diff
@@ -149,149 +140,272 @@ namespace FROSch {
...
+            } else {
+                translations[i] = Teuchos::null;
+            }
+        }
+        
+        for (UN k=0; k<this->DofsPerNode_[blockId]; k++) {
+            UN ii=0;
+            for (UN i=0; i<entitySet->getNumEntities(); i++) {
+                for (UN j=0; j<entitySet->getEntity(i)->getNumNodes(); j++) {
+                    translations[k]->replaceLocalValue(entitySet->getEntity(i)->getGammaDofID(j,k),ii,1.0);
```
Comment (chochmuth) [inline packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp]: We can use `i` of for-loop instead of `ii` in `translations[k]->replaceLocalValue(entitySet->getEntity(i)->getGammaDofID(j,k),ii,1.0);`

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp [hunk 2]
```diff
@@ -149,149 +140,272 @@ namespace FROSch {
...
+                    // Rotation 3
+                    rx = 0;
+                    ry = z;
+                    rz = -y;
+                    rotations[2]->replaceLocalValue(entitySet->getEntity(i)->getGammaDofID(j,0),ii,rx);
+                    rotations[2]->replaceLocalValue(entitySet->getEntity(i)->getGammaDofID(j,1),ii,ry);
+                    rotations[2]->replaceLocalValue(entitySet->getEntity(i)->getGammaDofID(j,2),ii,rz);
+                }
+            }
+            ii++;
```
Comment (chochmuth) [inline packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp]: see above, use `i` instead of `ii`.

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp (hunk 1 above)
Comment (searhein) [reply packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp]: Thank you for this comment. I completely missed this. I just pushed a small commit to get rid of the ii.

File: packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp (hunk 2 above)
Comment (searhein) [reply packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp]: I modified the code accordingly.

**Comment by srajama1** [comment]
This is a big commit, let us merge this after the holidays.

**Comment by srajama1** [comment]
@searhein We can merge this when you are back at work.

**Comment by searhein** [comment]
@srajama1 I am back to work. Today, I included some additional minor changes suggested by @mayrmt. Please approve the PR and merge it. Thank you.

**Comment by srajama1** [comment]
@searhein The merge button doesn't show in github because @chochmuth has to click approve as well. His current review status is marked as commented, so it will not let me merge.

**Comment by srajama1** [comment]
@chochmuth Thank you ! Merging it now.
