### PR TITLE
Tpetra: Fix #12898, Teuchos: absolute float array compare

### LINKED ISSUE #12898: tpetra:  TpetraCore_CrsMatrix_UnitTests4_MPI_4 fails in cuda builds
@trilinos/tpetra
@brian-kelley
@csiefer2 

### Description

We're seeing the test `TpetraCore_CrsMatrix_UnitTests4_MPI_4` fail in cuda builds. We use cuda 12.3, and we enable cusparse in our builds. 

The failures look like:

```
CrsMatrix_int_longlong_double_Tpetra_KokkosCompat_KokkosCudaWrapperNode_ApplyHelpers_UnitTest ...
Comparing exact == norm ... passed
Comparing exact == norm ... passed
did_we_batch = true == should_we_batch = true : passed
Comparing exact == norm ...
Error, relErr(exact[0],norm[0]) = relErr(0,3.8858e-11) = 0.999994 <= tol = 4.44089e-16: failed!

Error, relErr(exact[1],norm[1]) = relErr(0,3.88294e-11) = 0.999994 <= tol = 4.44089e-16: failed!
Comparing exact == norm ... passed
did_we_batch = true == should_we_batch = true : passed
Comparing exact == norm ...
```

The failures happen in the `ApplyHelpers` test. Here, spmv operations are computed in two different ways, first using a usual way, and then using a "batched" way. The test requires equality of the results, with a very restrictive tolerance basically up to machine precision.

It appears that something has changed the algorithm that is used in at least one of the two ways in which the spmv is computed. As a result, the result is still OK, but the test fails because the result is no longer the same up to machine precision.  

- https://github.com/trilinos/Trilinos/blob/f5169f5738f2b73bdcc393dbc8ee893e41c6f8ac/packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp#L1135

I do not know why the failure shows up in our but seemingly not your Trilinos cuda tests.

The failures might have something to do with:
- https://github.com/trilinos/Trilinos/pull/12852

### PR DESCRIPTION
**Pull request by brian-kelley**
@trilinos/tpetra 
@trilinos/teuchos 

## Motivation

Fixes #12898 , and adds a testing macro ``TEST_ABSOLUTE_COMPARE_FLOATING_ARRAYS( a1, a2, tol )``
to Teuchos that might be useful in other contexts.

## Testing

Tested by first enabling the nondeterministic cuSPARSE SpMV algorithm, making `` TpetraCore_CrsMatrix_UnitTests4_MPI_4`` fail just like in #12898. Then applied these changes and checked that the test now passes.

### CODE REVIEW

File: packages/teuchos/core/src/Teuchos_LocalTestingHelpers.hpp [hunk 1]
```diff
@@ -189,6 +189,19 @@
     if (!result) success = false; \
   }
 
+/** \brief Assert that a1.size()==a2.size() and |a[i]-b[i]| <= tol, i=0....
+ *
+ * Works for any object types that support a1[i], a1.size(), a2[j], and
```
Comment (maartenarnst) [inline packages/teuchos/core/src/Teuchos_LocalTestingHelpers.hpp:194]:
```suggestion
 * Works for all object types that support a1[i], a1.size(), a2[j], and
```

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp [hunk 2]
```diff
@@ -258,6 +258,28 @@ bool compareFloatingArrays(
   Teuchos::FancyOStream &out
   );
 
+/** \brief Compare if two array objects are the same up to an absolute
+ * difference: elements <tt>a1[i]</tt> and <tt>a2[i]</tt> are considered
+ * the same if <tt>|a1[i]-a2[i]| <= tol</tt>.
+ *
+ * This function works with any two array objects are the same size and have
```
Comment (maartenarnst) [inline packages/teuchos/core/src/Teuchos_TestingHelpers.hpp:265]:
```suggestion
 * This function works with any two array objects that are of the same size and have
```

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp [hunk 3]
```diff
@@ -258,6 +258,28 @@ bool compareFloatingArrays(
...
+ * the same element value types.  The function is templated on the container
+ * types and therefore can compare any two objects that have size() and
+ * operator[](i) defined. <tt>Teuchos::ScalarTraits</tt> must have a specialization
+ * for the element type.
+ *
+ * \returns Returns <tt>true</tt> if the compare and <tt>false</tt> otherwise.
```
Comment (maartenarnst) [inline packages/teuchos/core/src/Teuchos_TestingHelpers.hpp:271]: “If the compare” seems a bit weird. Could it be “if the comparison holds”?

File: packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp [hunk 4]
```diff
@@ -1127,12 +1139,12 @@ inline void tupleToArray(Array<T> &arr, const tuple &tup)
...
         compare.norm1(norm());
         if (ST::isOrdinal) {TEST_COMPARE_ARRAYS(exact,norm);}
-        else{TEST_COMPARE_FLOATING_ARRAYS(exact,norm,2.0*testingTol<Mag>());}
+        else{TEST_ABSOLUTE_COMPARE_FLOATING_ARRAYS(exact,norm,absNorm*testingTol<Mag>());}
         
         compare.update(ONE,Y2a,-ONE,Y2b,ZERO);
         compare.norm1(norm());
         if (ST::isOrdinal) {TEST_COMPARE_ARRAYS(exact,norm);}
-        else {TEST_COMPARE_FLOATING_ARRAYS(exact,norm,2.0*testingTol<Mag>());}
+        else {TEST_ABSOLUTE_COMPARE_FLOATING_ARRAYS(exact,norm,absNorm*testingTol<Mag>());}
```
Comment (maartenarnst) [inline packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp:1147]: Have you had a chance to look at the order of magnitude we can expect for `absNorm*testingTol<Mag>()`? And how stringent it is as compared with the error that we were seeing?

**Review by maartenarnst — COMMENTED** [review]
Hi @brian-kelley. Thanks for the work on this! That’s a good idea indeed to take this as an opportunity to add the new Teuchos macro.

File: packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp (hunk 4 above)
Comment (brian-kelley) [reply packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp:1147]: @maartenarnst Yes, absNorm ended up being fairly large (roughly 2x10^5 on all the ranks) which explains why the absolute error seemed high (1x10^-11) between two consecutive applies.

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp (hunk 3 above)
Comment (brian-kelley) [reply packages/teuchos/core/src/Teuchos_TestingHelpers.hpp]: I agree, I copy-pasted that but it doesn't make sense. For the new function I just spelled out the formula for exactly what's being compared, since I think that's readable enough.

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp (hunk 2 above)
Comment (brian-kelley) [reply packages/teuchos/core/src/Teuchos_TestingHelpers.hpp]: Thanks @maartenarnst , I actually took the part about "same size" out completely because it's not really a precondition - you can pass different sized a1,a2 and it will correctly return false in that case.

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp [hunk 5]
```diff
@@ -726,5 +748,52 @@ bool Teuchos::compareFloatingArrays(
...
+  const Array1 &a1, const std::string &a1_name,
+  const Array2 &a2, const std::string &a2_name,
+  const ScalarMag &tol,
+  Teuchos::FancyOStream &out
+  )
+{
+  using Teuchos::as;
+  using Teuchos::ScalarTraits;
+
+  // This figures out what the elements of Array1 and Array2 are (result of their [] operators)
```
[the remark this answers is not in the document]
Comment (brian-kelley) [reply packages/teuchos/core/src/Teuchos_TestingHelpers.hpp]: I ended up with "// Determine the element types of Array1 and Array2", more concise that way

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp [hunk 6]
```diff
@@ -726,5 +748,52 @@ bool Teuchos::compareFloatingArrays(
...
+  using Elem1 = std::remove_const_t<std::remove_reference_t<decltype(std::declval<Array1>()[0])>>;
```
[the remark this answers is not in the document]
Comment (brian-kelley) [reply packages/teuchos/core/src/Teuchos_TestingHelpers.hpp]: Yes, good idea

**Comment by brian-kelley** [comment]
Thanks for the detailed review @maartenarnst , I think I have addressed your comments

**Comment by brian-kelley** [comment]
@trilinos/framework Just a heads up, looks like the clang-format check failed the last 2 builds with
```
Error: Response status code does not indicate success: 429 (Too Many Requests).
```

**Comment by achauphan** [comment]
@brian-kelley this job runs on GitHub's provided default runners and looks like the runner it got placed on has some connection issues. Good news is, with GitHub Actions, you can actually manually rerun the job unlike with the AutoTester system (clicking on the job's 'details' link and on top-right 're-run failed jobs'). 

I've gone a head and rerun the job and it looks like it completed successfully!

**Comment by brian-kelley** [comment]
@achauphan Thanks for the tip!

**Review by maartenarnst — APPROVED** [review]
Thanks @brian-kelley! Ok indeed for the small things that I had spotted.  It looks good!

File: packages/teuchos/core/src/Teuchos_TestingHelpers.hpp [hunk 7]
```diff
@@ -258,6 +263,30 @@ bool compareFloatingArrays(
...
+ * for the element type.
+ *
+ * \returns Returns <tt>true</tt> if <tt>a1.size() == a2.size()</tt> and
+ *   <tt>|a1[i]-a2[i]| <= tol</tt> for all <tt>0 <= i < a1.size()</tt>.
+ *   Otherwise returns <tt>false</tt>.
+ *
+ * \ingroup teuchos_testing_grp
+ */
+template<class Array1, class Array2, class ScalarMag>
+bool compareFloatingArraysAbsolute(
```
Comment (bartlettroscoe) [inline packages/teuchos/core/src/Teuchos_TestingHelpers.hpp:283]: Technically, we could unit test this function to ensure that it behaves as we expect.  But I see that the current function `Teuchos::compareFloatingArrays()` (which I added 16 years ago in commit 23ce08e7e6d 😊) did not have a unit test for this so no big deal.   (But this function is easy enough to manually check that it works as it should while writing unit tests so not much risk there.  In fact, I aways start with a failing test, look at the output, and then make the test pass, which tests the unit testing infrastructure.)

**Review by bartlettroscoe — APPROVED** [review]
The Teuchos code looks good to me.  @brian-kelley thanks for taking the time to add this new test support code and thanks to @maartenarnst for your detailed review feedback!
