### PR TITLE
Tpetra: Assemble RHS in finite element assemble examples (#2660)

### LINKED ISSUE #2660: Tpetra: Finite Element Assembly Examples Don't Assemble RHS
We should fix that.  Also, this is a great opportunity to do use FEMultiVector.

(Would add labels, github's website doesn't work right on Windows)

@tpetra

### PR DESCRIPTION
**Pull request by tjfulle**
@trilinos/tpetra 

## Description
Assemble RHS in finite element assemble examples 

## Motivation and Context
So examples are more complete

## Related Issues

* Closes #2660

## How Has This Been Tested?
Tpetra tests pass locally with gcc7.2.0/openmpi3.0.0

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

### CODE REVIEW

**Comment by tjfulle** [comment]
Sorry for spamming you @mhoemmen , but I think both @william76 and @csiefer2 are out for the next while.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp [hunk 1]
```diff
@@ -200,9 +202,12 @@ int executeInsertGlobalIndicesDP(const comm_ptr_t& comm, const struct CmdLineOpt
   RCP<TimeMonitor> timerElementLoopMatrix = rcp(new TimeMonitor(*TimeMonitor::getNewTimer("3) ElementLoop  (Matrix)")));
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp]: I've expressed my feelings about `RCP<TimeMonitor>` before.  No worries for now, though :-) .

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp [hunk 2]
```diff
@@ -90,7 +90,13 @@ void ReferenceQuad4(scalar_2d_array_t & elementMatrix) {
   }
 }
 
-
+// RHS vector for the reference quad.
+// This can be thought of as a unit source being equally distributed to the
+// 4 nodes of the quad.
+void ReferenceQuad4RHS(Teuchos::Array<Scalar>& rhs) {
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp]: OK for now, but think about replacing all Teuchos::Array with std::vector or Kokkos::View.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp [hunk 3]
```diff
@@ -223,6 +229,8 @@ int executeInsertGlobalIndicesDP(const comm_ptr_t& comm, const struct CmdLineOpt
     // - populate the values array
     // - add the values to the crs_matrix.
     // Note: hardcoded 4 here because we're using quads.
+    Teuchos::Array<global_ordinal_t> rows(4);
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp]: See above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp [hunk 4]
```diff
@@ -223,6 +229,8 @@ int executeInsertGlobalIndicesDP(const comm_ptr_t& comm, const struct CmdLineOpt
     // - populate the values array
     // - add the values to the crs_matrix.
     // Note: hardcoded 4 here because we're using quads.
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp]: Rather than a note, why not this?
```
constexpr int dof_per_element = 4; // or size_t or whatever
```

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp [hunk 5]
```diff
@@ -226,9 +226,11 @@ int executeTotalElementLoopDP(const comm_ptr_t& comm, const struct CmdLineOpts&
   RCP<TimeMonitor> timerElementLoopMatrix = rcp(new TimeMonitor(*TimeMonitor::getNewTimer("3) ElementLoop  (Matrix)")));
 
   RCP<matrix_t> crs_matrix = rcp(new matrix_t(crs_graph));
+  RCP<multivector_t> rhs = rcp(new multivector_t(crs_graph->getRowMap(), 1));
 
   scalar_2d_array_t element_matrix;
   Kokkos::resize(element_matrix, 4, 4);
+  Teuchos::Array<Scalar> element_rhs(4);
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp]: See above.

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp [hunk 6]
```diff
@@ -64,6 +65,7 @@ typedef typename Tpetra::Map<>             map_t;
 typedef typename Tpetra::CrsGraph<>        graph_t;
 typedef typename Tpetra::CrsMatrix<Scalar> matrix_t;
 typedef typename Tpetra::Export<>          export_t;
+typedef typename Tpetra::MultiVector<Scalar> multivector_t;
 
 // NOTE: Arrays are hardwired for QUAD4
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp]: See note above (just stick a constexpr `dof_per_elt` in this file & you're done :D ).

File: packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp [hunk 7]
```diff
@@ -266,6 +272,7 @@ int executeLocalElementLoopDP(const comm_ptr_t& comm, const struct CmdLineOpts&
 
       // For Type-2 Assembly, we only sumInot the overlapping crs_matrix.
```
Comment (mhoemmen) [inline packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp]: typo: "sumInto" not "sumInot"

**Comment by tjfulle** [comment]
Thanks @mhoemmen!  The original code is not mine, I just through in the RHS assembly.  I'll tag @william76 so he can see your comments and address them as he further develops the assembly examples.

I'll replace the few `Teuchos::Array`s I put in with `Kokkos::View` and push.

**Comment by mhoemmen** [comment]
@tjfulle wrote:
> I'll replace the few `Teuchos::Array`s I put in with `Kokkos::View` and push.

No worries -- can leave for later -- also not worth adding `Kokkos::View` unless you plan to make it work on the GPU.  Thanks!

**Comment by tjfulle** [comment]
Okay, I'll just merge the PR then and leave the `Teuchos::Array` for when the examples are made to run on the GPU.
