### PR TITLE
Two potential fixes for issue 183, just for review purposes.

### LINKED ISSUE #183: Build failure with Ifpack2, Zoltan2, and AMD TPL
At commit 17ccfa78c106fd86812563a4ab3d50ceace9c13a, I configure Trilinos with simply:

```
cmake \
  -DTPL_ENABLE_AMD:BOOL=YES \
  -DBUILD_SHARED_LIBS:BOOL=YES \
  -DTrilinos_ENABLE_Zoltan2:BOOL=YES \
  -DTrilinos_ENABLE_Ifpack2:BOOL=YES \
  ..
```

During build, I get the following error:

```
In file included from /ptmp/Trilinos/packages/zoltan2/src/algorithms/order/Zoltan2_OrderingAlgorithms.hpp:53:0,
                 from /ptmp/Trilinos/packages/zoltan2/src/problems/Zoltan2_OrderingProblem.hpp:54,
                 from /ptmp/Trilinos/packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp:68,
                 from /ptmp/Trilinos/build/build-zoltan2-amd/packages/ifpack2/src/Ifpack2_AdditiveSchwarz.hpp:2,
                 from /ptmp/Trilinos/packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp:47,
                 from /ptmp/Trilinos/build/build-zoltan2-amd/packages/ifpack2/src/Ifpack2_Details_Factory.hpp:2,
                 from /ptmp/Trilinos/packages/ifpack2/src/Ifpack2_Factory_decl.hpp:48,
                 from /ptmp/Trilinos/build/build-zoltan2-amd/packages/ifpack2/src/Ifpack2_Factory.hpp:1,
                 from /ptmp/Trilinos/packages/ifpack2/src/Ifpack2_Details_LinearSolverFactory_def.hpp:54,
                 from /ptmp/Trilinos/build/build-zoltan2-amd/packages/ifpack2/src/Ifpack2_Details_LinearSolverFactory.hpp:2,
                 from /ptmp/Trilinos/packages/ifpack2/src/Ifpack2_Details_registerLinearSolverFactory.cpp:45:
/ptmp/Trilinos/packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp: In instantiation of 'int Zoltan2::AlgAMD<Adapter>::order(const Teuchos::RCP<Zoltan2::OrderingSolution<typename Adapter::lno_t, typename Adapter::gno_t> >&) [with Adapter = Zoltan2::MatrixAdapter<Xpetra::RowMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Xpetra::RowMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >; typename Adapter::gno_t = long long int; typename Adapter::lno_t = int]':
/ptmp/Trilinos/packages/zoltan2/src/problems/Zoltan2_OrderingProblem.hpp:229:11:   required from 'void Zoltan2::OrderingProblem<Adapter>::solve(bool) [with Adapter = Zoltan2::XpetraRowMatrixAdapter<Xpetra::RowMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >, Xpetra::RowMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> > >]'
/ptmp/Trilinos/packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp:1517:5:   required from 'void Ifpack2::AdditiveSchwarz<MatrixType, LocalInverseType>::setup() [with MatrixType = Tpetra::RowMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >; LocalInverseType = Ifpack2::Preconditioner<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >]'
/ptmp/Trilinos/packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp:1134:11:   required from 'void Ifpack2::AdditiveSchwarz<MatrixType, LocalInverseType>::initialize() [with MatrixType = Tpetra::RowMatrix<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >; LocalInverseType = Ifpack2::Preconditioner<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >]'
/ptmp/Trilinos/packages/ifpack2/src/Ifpack2_Details_registerLinearSolverFactory.cpp:76:1:   required from here
/ptmp/Trilinos/packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp:154:70: error: no matching function for call to 'Zoltan2::AMDTraits<int>::order(const size_t&, const int*, const long long int*, lno_t*&, double [5], double [20])'
                              edgeIds.getRawPtr(), perm, Control, Info);
                                                                      ^
/ptmp/Trilinos/packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp:77:9: note: candidate: int Zoltan2::AMDTraits<int>::order(int, const int*, const int*, int*, double*, double*)
     int order(int n, const int *Ap, const int *Ai, int *perm,
         ^
/ptmp/Trilinos/packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp:77:9: note:   no known conversion for argument 3 from 'const long long int*' to 'const int*'
packages/ifpack2/src/CMakeFiles/ifpack2.dir/build.make:62: recipe for target 'packages/ifpack2/src/CMakeFiles/ifpack2.dir/Ifpack2_Details_registerLinearSolverFactory.cpp.o' failed
make[2]: *** [packages/ifpack2/src/CMakeFiles/ifpack2.dir/Ifpack2_Details_registerLinearSolverFactory.cpp.o] Error 1
CMakeFiles/Makefile2:6589: recipe for target 'packages/ifpack2/src/CMakeFiles/ifpack2.dir/all' failed
make[1]: *** [packages/ifpack2/src/CMakeFiles/ifpack2.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by srajama1**
@kddevin : Can you look over these two potential fixes for issue 183 ? Both have pros and cons.

One use lno_t for calling AMD other uses SuiteSparse_long for AMD but has to downgrade the permutation as perm in OrderingSolution uses lno_t. Both will resolve #183 for now. There is an ifdef in the code that splits these two options.

### CODE REVIEW

File: packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp [hunk 1]
```diff
@@ -146,6 +149,10 @@ class AlgAMD : public Algorithm<Adapter>
       // wgts are ignored in AMD
       model->getEdgeList(edgeIds, offsets, wgts);
 
+#if AMD_WITH_LNO_T
+    {
+
+      // SR: We will always call AMD with lno_t
```
Comment (kddevin) [inline packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp]: From the comments, it sounds as is SuiteSparse can be compiled with SuiteSparse_long == long or SuiteSparse_long == long long.  Is that correct?
If so, what happens in this case when lno_t == long long but SuiteSparse_long = long?  Will the AMD_WITH_LNO_T version work?

**Comment by srajama1** [comment]
Yes, Suitesparse picks it automatically to be 64 bit (long in Unix, and __int64 in windows). It can be overridden during compiling SuiteSparse to be "long long" as well.

The int/32-bit version of SuiteSparse is always there, irrespective what happens with long. So if the type conversions with Teuchos:as works, then AMD will work fine in the lno_t case as well.

File: packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp (hunk 1 above)
Comment (srajama1) [inline packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp]: I realized I didn't correctly answer your second question. If long and long long are both 64 bit, this won't be a problem.  I assume you are asking what if Suitesparse_long was 32 bits. In this case, we will (might ?) get a error from Teuchos::as. I don't think any of the tests used lno_t as long long.

Comment (srajama1) [inline packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp]: Answering my one question. You are right, this won't work. It will result in a compile error. I will go with the AMD_WITH_GNO_T as the result. Thanks !

**Comment by srajama1** [comment]
@kddevin : Ready to be pushed if that is ok with you.

100% tests passed, 0 tests failed out of 118

Label Time Summary:
Ifpack2    =  25.70 sec
Zoltan2    =  75.52 sec

File: packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp [hunk 2]
```diff
@@ -146,22 +149,49 @@ class AlgAMD : public Algorithm<Adapter>
...
+      // We will use the lno_t for local ordering
       lno_t *perm;
       perm = (lno_t *) (solution->getPermutationRCP().getRawPtr());
 
-      lno_t result = AMDobj.order(nVtx, offsets.getRawPtr(),
-                             edgeIds.getRawPtr(), perm, Control, Info);
+      SuiteSparse_long *amd_offsets, *amd_edgeIds;
+      TPL_Traits<SuiteSparse_long, const lno_t>::ASSIGN_ARRAY(&amd_offsets,
+             offsets);
+      // This might through depending on how SuiteSparse was compiled
```
Comment (kddevin) [inline packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp]: "throw"?
