### PR TITLE
MueLu: fixing the count of aggregated nodes in refactored Phase2a of aggregation, see #6325

### LINKED ISSUE #6325: MueLu: Phase2a of refactored aggregation wrongly counts aggregated nodes
## Bug Report
@trilinos/muelu 

### Description
There is a bug in refactored aggregation that leads to the wrong number of aggregated nodes after phase 2a. This sometimes leads to unaggregated nodes or to have a negative number of unaggregated nodes.

### PR DESCRIPTION
**Pull request by lucbv**
A piece of logic is wrong in the algorithms that counts
how many nodes have been aggregated in Phase2a of aggregation.
This commit fixes that by individually counting every node
that is being aggregated instead of counting all the nodes in
a newly formed aggregate, at once.

@trilinos/muelu 

## Motivation
All bugs shall be fixed, but this is also generating a failing test in Empire and blocking the adoption of the latest refactored setup of MueLu.

## Related Issues

* Closes #6325
* Blocks 
* Is blocked by 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Stakeholder Feedback
Empire: @cgcgcg will check that the failing test is fixed after this modification is applied.
ExaWind: @lucbv checked that ExaWind is not negatively affected by these changes.

## Testing
Local tests have been performed and @cgcgcg will apply locally these changes to test these with Empire

### CODE REVIEW

File: packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_def.hpp [hunk 1]
```diff
@@ -165,13 +165,13 @@ namespace MueLu {
                                         if(graph.isLocalNeighborVertex(neigh) &&
                                            aggStat(neigh) == READY &&
                                            aggSize < maxNodesPerAggregate) {
```
Comment (cgcgcg) [inline packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_def.hpp]: Unrelated note: once `aggSize` hits `maxNodesPerAggregate` in the loop above, this condition is always false.

Comment (lucbv) [reply packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_def.hpp]: Changed the logic so that a partial aggregate is now form as it was the case in the non-refactored code.
