### PR TITLE
ShyLU: Fixed test link errors #5618

### LINKED ISSUE #5618: ShyLU: build failures with Tpetra's deprecated code disabled
## Bug Report
@trilinos/shylu 

Part of: #5602 

### Description

With Tpetra's deprecated code disabled, ShyLU fails to build with the configuration at `GlobalOrdinal=long long int` at: https://github.com/trilinos/Trilinos/issues/5602#issuecomment-516594843 (removing the lines disabling ShyLU, of course)

The build failure could be due to `GlobalOrdinal=long long int`, or Epetra being disabled?

### PR DESCRIPTION
**Pull request by brian-kelley**
Fixed link errors in several ShyLU_DDFROSch tests, where the global ordinal was
unknowingly hardcoded as int. Made Xpetra pick a reasonable default GlobalOrdinal.

@trilinos/xpetra 
@trilinos/shylu 

## Description

Building with Tpetra GO=long long (but not GO=int) caused the failure, because Xpetra structrues were not instantiated with *_int_int_node. The reason why GO was hardcoded to int in ShyLU is because ShyLU used the Xpetra "default types" to define Scalar, LO, GO and NO. In Xpetra_DefaultTypes.hpp, GO was hardcoded to int, regardless of what was enabled in CMake. So this commit adds logic in Xpetra to choose a reasonable default GlobalOrdinal based on what is enabled: if Tpetra is enabled, the default GO of Tpetra is chosen. Then if Epetra 64-bit GO is enabled, long long is used. Otherwise, int is used.

## Motivation and Context

This fixes a ShyLU build failure as part of the Tpetra deprecated code removal (#5602).

## How Has This Been Tested?

This was built with Tpetra GO=long long enabled, GO=int disabled, Epetra disabled, and deprecated code disabled. Most tests in FROSch failed to build before, but now build and run successfully (except for the two in #5617, which were fixed separately).

## Checklist

- [x] My commit messages mention the appropriate GitHub issue numbers.
- [x] My code follows the code style of the affected package(s).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] No new compiler warnings were introduced.
- [ ] These changes break backwards compatibility.

I didn't say that all existing tests passed, because some other fixes (see #5602) for tests in this configuration have not made it to develop branch yet. The tests affected by these changes do pass.

### CODE REVIEW

File: packages/xpetra/src/Headers/Xpetra_UseDefaultTypes.hpp [hunk 1]
```diff
@@ -54,7 +54,19 @@
 // Define default data types
 typedef double Scalar;
 typedef int LocalOrdinal;
+
+// Choose global ordinal based on enabled underlying libraries
+#ifdef HAVE_XPETRA_TPETRA
+typedef typename Tpetra::Map<>::global_ordinal_type GlobalOrdinal;
```
Comment (mhoemmen) [inline packages/xpetra/src/Headers/Xpetra_UseDefaultTypes.hpp]: Brian and I talked about this in person today.  I suggested adding `#error` if Epetra and Tpetra are enabled but Tpetra's default ordinal type is not `int`.  That's already an error in Xpetra and it might already catch that case at configure time, but just in case, it would be good to add a test here.

File: packages/xpetra/src/Map/Xpetra_Map.hpp [hunk 2]
```diff
@@ -75,14 +75,29 @@ namespace Xpetra {
 # endif
 #endif
 
+  namespace Details
+  {
+    //Check for the default Tpetra GlobalOrdinal (long long)
+    #ifdef HAVE_XPETRA_TPETRA
```
Comment (mhoemmen) [inline packages/xpetra/src/Map/Xpetra_Map.hpp]: See above.  Also, perhaps we should consolidate these two "test the macros" things in a single place.

**Comment by searhein** [comment]
@brian-kelley Thanks for fixing this and #5637.
