### PR TITLE
Tpetra:  Unit test for #9116

### LINKED ISSUE #9116: Tpetra:  some imports fail when TPETRA_ASSUME_CUDA_AWARE_MPI=0
## Bug Report
@trilinos/tpetra 

### Description
@rcknaus reported errors in Tpetra multivector export when TPETRA_ASSUME_CUDA_AWARE_MPI=0 after #8821 was merged
https://github.com/Exawind/nalu-wind/issues/858

### PR DESCRIPTION
**Pull request by kddevin**
@trilinos/tpetra 

## Motivation
Adding a unit test for #9116 
Exercises case where communication is done on host (MPI is not CUDA_AWARE) but packing/unpacking is done on device.

## Related Issues

* Closes #9116 
* Blocks 
* Is blocked by 
* Follows #9117 
* Precedes 
* Related to 
* Part of 
* Composed of 

## Testing

With develop branch, test FAILS with TPETRA_ASSUME_CUDA_AWARE_MPI=0 and PASSES with TPETRA_ASSUME_CUDA_AWARE_MPI=1, replicating behavior in #9116 
With #9116, test PASSES regardless of TPETRA_ASSUME_CUDA_AWARE_MPI value.
Tested on ascicgpu

### CODE REVIEW

**Review by jhux2 — DISMISSED** [review]
lgtm

File: packages/tpetra/core/test/ImportExport/Bug9116.cpp [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+// fail with TPETRA_ASSUME_CUDA_AWARE_MPI=0.
+
+  using map_t = Tpetra::Map<>;
+  using vector_t = Tpetra::Vector<Scalar>;
+  using lno_t = typename map_t::local_ordinal_type;
+  using gno_t = typename map_t::global_ordinal_type;
+  using import_t = Tpetra::Import<lno_t, gno_t>;
+
+  auto comm = Tpetra::getDefaultComm();
+  int me = comm->getRank();
```
Comment (jhux2) [inline packages/tpetra/core/test/ImportExport/Bug9116.cpp:70]: Looks like the autotester chokes on `me` because the variable is unused.

**Review by jhux2 — APPROVED** [review]
lgtm
