### PR TITLE
Xpetra: Fix for CheckRepairMainDiagonal

### LINKED ISSUE #3041: Xpetra/Epetra Undefined Reference when Compiling MueLu Test
@trilinos/muelu @trilinos/xpetra 

Compiling Trilinos (with tests) for KNL on Argonne Theta. I am using the Master branch.

Using:
*  Cray MPI
*  Intel 18.2 Compiler
*  OpenMP enabled

```
[100%] Built target MueLu_Viz
[100%] Built target MueLu_Convergence
[100%] Linking CXX executable MueLu_Driver.exe
Warning:
 Headers and libraries from cray-libsci/18.04.1 will be ignored because they conflict with -mkl.

../../../kokkos/core/src/libkokkoscore.a(Kokkos_Profiling_Interface.cpp.o): In function `Kokkos::Profiling::initialize()':

../../../kokkos/core/src/libkokkoscore.a(Kokkos_Profiling_Interface.cpp.o): In function `Kokkos::Profiling::initialize()':
Kokkos_Profiling_Interface.cpp:(.text+0x5c5): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `int main_<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Teuchos::CommandLineProcessor&, Xpetra::UnderlyingLib&, int, char**)':
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x31ca): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&)'
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x3213): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&)'
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `int main_<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Teuchos::CommandLineProcessor&, Xpetra::UnderlyingLib&, int, char**)':
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x31ca): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&)'
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x3213): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&)'
```

### PR DESCRIPTION
**Pull request by cgcgcg**
@trilinos/xpetra 

## Motivation
Fix debug check in `CheckRepairMainDiagonal`. Seems to get rid of #6882. 

Hopefully fix #3041

### CODE REVIEW

File: packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp [hunk 1]
```diff
@@ -453,7 +453,7 @@ class MatrixUtils {
     Ac->getLocalDiagCopy(*diagVec);
 
     LocalOrdinal lZeroDiags = 0;
-    Teuchos::ArrayRCP< Scalar > diagVal = diagVec->getDataNonConst(0);
+    Teuchos::ArrayRCP< const Scalar > diagVal = diagVec->getData(0);
```
Comment (jhux2) [inline packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp:456]: Huh, that's interesting.

Comment (cgcgcg) [reply packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp:456]: The diagonal is modified by building a new matrix, not by modifying this view.
